replace into games (name, console_name) values ( "007 - GoldenEye", "Nintendo 64");
replace into games (name, console_name) values ( "007 - The World Is Not Enough", "Nintendo 64");
replace into games (name, console_name) values ( "1080 Snowboarding", "Nintendo 64");
replace into games (name, console_name) values ( "AeroFighters Assault", "Nintendo 64");
replace into games (name, console_name) values ( "AeroGauge", "Nintendo 64");
replace into games (name, console_name) values ( "Aidyn Chronicles - The First Mage", "Nintendo 64");
replace into games (name, console_name) values ( "All Star Tennis '99", "Nintendo 64");
replace into games (name, console_name) values ( "All-Star Baseball '99", "Nintendo 64");
replace into games (name, console_name) values ( "All-Star Baseball 2000", "Nintendo 64");
replace into games (name, console_name) values ( "All-Star Baseball 2001", "Nintendo 64");
replace into games (name, console_name) values ( "Armorines - Project S.W.A.R.M.", "Nintendo 64");
replace into games (name, console_name) values ( "Army Men - Air Combat", "Nintendo 64");
replace into games (name, console_name) values ( "Army Men - Sarge's Heroes", "Nintendo 64");
replace into games (name, console_name) values ( "Army Men - Sarge's Heroes 2", "Nintendo 64");
replace into games (name, console_name) values ( "Asteroids Hyper 64", "Nintendo 64");
replace into games (name, console_name) values ( "Automobili Lamborghini", "Nintendo 64");
replace into games (name, console_name) values ( "Banjo-Kazooie", "Nintendo 64");
replace into games (name, console_name) values ( "Banjo-Tooie", "Nintendo 64");
replace into games (name, console_name) values ( "Bassmasters 2000", "Nintendo 64");
replace into games (name, console_name) values ( "Batman Beyond - Return of the Joker", "Nintendo 64");
replace into games (name, console_name) values ( "BattleTanx", "Nintendo 64");
replace into games (name, console_name) values ( "BattleTanx - Global Assault", "Nintendo 64");
replace into games (name, console_name) values ( "Battlezone - Rise of the Black Dogs", "Nintendo 64");
replace into games (name, console_name) values ( "Beetle Adventure Racing!", "Nintendo 64");
replace into games (name, console_name) values ( "Big Mountain 2000", "Nintendo 64");
replace into games (name, console_name) values ( "Bio F.R.E.A.K.S.", "Nintendo 64");
replace into games (name, console_name) values ( "Blast Corps", "Nintendo 64");
replace into games (name, console_name) values ( "Blues Brothers 2000", "Nintendo 64");
replace into games (name, console_name) values ( "Body Harvest", "Nintendo 64");
replace into games (name, console_name) values ( "Bomberman 64", "Nintendo 64");
replace into games (name, console_name) values ( "Bomberman 64 - The Second Attack!", "Nintendo 64");
replace into games (name, console_name) values ( "Bomberman Hero", "Nintendo 64");
replace into games (name, console_name) values ( "Bottom of the 9th", "Nintendo 64");
replace into games (name, console_name) values ( "Brunswick Circuit Pro Bowling", "Nintendo 64");
replace into games (name, console_name) values ( "Buck Bumble", "Nintendo 64");
replace into games (name, console_name) values ( "Bug's Life, A", "Nintendo 64");
replace into games (name, console_name) values ( "Bust-A-Move '99", "Nintendo 64");
replace into games (name, console_name) values ( "Bust-A-Move 2 - Arcade Edition", "Nintendo 64");
replace into games (name, console_name) values ( "California Speed", "Nintendo 64");
replace into games (name, console_name) values ( "Carmageddon 64", "Nintendo 64");
replace into games (name, console_name) values ( "Castlevania", "Nintendo 64");
replace into games (name, console_name) values ( "Castlevania - Legacy of Darkness", "Nintendo 64");
replace into games (name, console_name) values ( "Chameleon Twist", "Nintendo 64");
replace into games (name, console_name) values ( "Chameleon Twist 2", "Nintendo 64");
replace into games (name, console_name) values ( "Charlie Blast's Territory", "Nintendo 64");
replace into games (name, console_name) values ( "Chopper Attack", "Nintendo 64");
replace into games (name, console_name) values ( "Clay Fighter - Sculptor's Cut", "Nintendo 64");
replace into games (name, console_name) values ( "Clay Fighter 63 1-3", "Nintendo 64");
replace into games (name, console_name) values ( "Command & Conquer", "Nintendo 64");
replace into games (name, console_name) values ( "Conker's Bad Fur Day", "Nintendo 64");
replace into games (name, console_name) values ( "Cruis'n Exotica", "Nintendo 64");
replace into games (name, console_name) values ( "Cruis'n USA", "Nintendo 64");
replace into games (name, console_name) values ( "Cruis'n World", "Nintendo 64");
replace into games (name, console_name) values ( "CyberTiger", "Nintendo 64");
replace into games (name, console_name) values ( "Dark Rift", "Nintendo 64");
replace into games (name, console_name) values ( "Deadly Arts", "Nintendo 64");
replace into games (name, console_name) values ( "Destruction Derby 64", "Nintendo 64");
replace into games (name, console_name) values ( "Diddy Kong Racing", "Nintendo 64");
replace into games (name, console_name) values ( "Donald Duck - Goin' Quackers", "Nintendo 64");
replace into games (name, console_name) values ( "Donkey Kong 64", "Nintendo 64");
replace into games (name, console_name) values ( "Doom 64", "Nintendo 64");
replace into games (name, console_name) values ( "Dr. Mario 64", "Nintendo 64");
replace into games (name, console_name) values ( "Dual Heroes", "Nintendo 64");
replace into games (name, console_name) values ( "Duck Dodgers Starring Daffy Duck", "Nintendo 64");
replace into games (name, console_name) values ( "Duke Nukem - Zero Hour", "Nintendo 64");
replace into games (name, console_name) values ( "Duke Nukem 64", "Nintendo 64");
replace into games (name, console_name) values ( "ECW Hardcore Revolution", "Nintendo 64");
replace into games (name, console_name) values ( "Earthworm Jim 3D", "Nintendo 64");
replace into games (name, console_name) values ( "Elmo's Letter Adventure", "Nintendo 64");
replace into games (name, console_name) values ( "Elmo's Number Journey", "Nintendo 64");
replace into games (name, console_name) values ( "Excitebike 64", "Nintendo 64");
replace into games (name, console_name) values ( "Extreme-G", "Nintendo 64");
replace into games (name, console_name) values ( "Extreme-G XG2", "Nintendo 64");
replace into games (name, console_name) values ( "F-1 World Grand Prix", "Nintendo 64");
replace into games (name, console_name) values ( "F-Zero X", "Nintendo 64");
replace into games (name, console_name) values ( "F1 Pole Position 64", "Nintendo 64");
replace into games (name, console_name) values ( "FIFA - Road to World Cup 98", "Nintendo 64");
replace into games (name, console_name) values ( "FIFA 99", "Nintendo 64");
replace into games (name, console_name) values ( "FIFA Soccer 64", "Nintendo 64");
replace into games (name, console_name) values ( "Fighter Destiny 2", "Nintendo 64");
replace into games (name, console_name) values ( "Fighters Destiny", "Nintendo 64");
replace into games (name, console_name) values ( "Fighting Force 64", "Nintendo 64");
replace into games (name, console_name) values ( "Flying Dragon", "Nintendo 64");
replace into games (name, console_name) values ( "Forsaken 64", "Nintendo 64");
replace into games (name, console_name) values ( "Fox Sports College Hoops '99", "Nintendo 64");
replace into games (name, console_name) values ( "Frogger 2", "Nintendo 64");
replace into games (name, console_name) values ( "GT64 - Championship Edition", "Nintendo 64");
replace into games (name, console_name) values ( "Gauntlet Legends", "Nintendo 64");
replace into games (name, console_name) values ( "Gex 3 - Deep Cover Gecko", "Nintendo 64");
replace into games (name, console_name) values ( "Gex 64 - Enter the Gecko", "Nintendo 64");
replace into games (name, console_name) values ( "Glover", "Nintendo 64");
replace into games (name, console_name) values ( "Goemon's Great Adventure", "Nintendo 64");
replace into games (name, console_name) values ( "Golden Nugget 64", "Nintendo 64");
replace into games (name, console_name) values ( "Harvest Moon 64", "Nintendo 64");
replace into games (name, console_name) values ( "Hercules - The Legendary Journeys", "Nintendo 64");
replace into games (name, console_name) values ( "Hexen", "Nintendo 64");
replace into games (name, console_name) values ( "Hey You, Pikachu!", "Nintendo 64");
replace into games (name, console_name) values ( "Hot Wheels - Turbo Racing", "Nintendo 64");
replace into games (name, console_name) values ( "Hybrid Heaven", "Nintendo 64");
replace into games (name, console_name) values ( "Hydro Thunder", "Nintendo 64");
replace into games (name, console_name) values ( "Iggy's Reckin' Balls", "Nintendo 64");
replace into games (name, console_name) values ( "In-Fisherman - Bass Hunter 64", "Nintendo 64");
replace into games (name, console_name) values ( "Indiana Jones and the Infernal Machine", "Nintendo 64");
replace into games (name, console_name) values ( "Indy Racing 2000", "Nintendo 64");
replace into games (name, console_name) values ( "International Superstar Soccer '98", "Nintendo 64");
replace into games (name, console_name) values ( "International Superstar Soccer 2000", "Nintendo 64");
replace into games (name, console_name) values ( "International Superstar Soccer 64", "Nintendo 64");
replace into games (name, console_name) values ( "International Track & Field 2000", "Nintendo 64");
replace into games (name, console_name) values ( "Jeopardy!", "Nintendo 64");
replace into games (name, console_name) values ( "Jeremy McGrath Supercross 2000", "Nintendo 64");
replace into games (name, console_name) values ( "Jet Force Gemini", "Nintendo 64");
replace into games (name, console_name) values ( "John Romero's Daikatana", "Nintendo 64");
replace into games (name, console_name) values ( "Ken Griffey Jr.'s Slugfest", "Nintendo 64");
replace into games (name, console_name) values ( "Killer Instinct Gold", "Nintendo 64");
replace into games (name, console_name) values ( "Kirby 64 - The Crystal Shards", "Nintendo 64");
replace into games (name, console_name) values ( "Knife Edge - Nose Gunner", "Nintendo 64");
replace into games (name, console_name) values ( "Knockout Kings 2000", "Nintendo 64");
replace into games (name, console_name) values ( "Kobe Bryant's NBA Courtside", "Nintendo 64");
replace into games (name, console_name) values ( "LEGO Racers", "Nintendo 64");
replace into games (name, console_name) values ( "Legend of Zelda, The - Majora's Mask", "Nintendo 64");
replace into games (name, console_name) values ( "Legend of Zelda, The - Ocarina of Time", "Nintendo 64");
replace into games (name, console_name) values ( "Lode Runner 3-D", "Nintendo 64");
replace into games (name, console_name) values ( "MRC - Multi Racing Championship", "Nintendo 64");
replace into games (name, console_name) values ( "Mace - The Dark Age", "Nintendo 64");
replace into games (name, console_name) values ( "Madden Football 64", "Nintendo 64");
replace into games (name, console_name) values ( "Madden NFL 2000", "Nintendo 64");
replace into games (name, console_name) values ( "Madden NFL 2001", "Nintendo 64");
replace into games (name, console_name) values ( "Madden NFL 2002", "Nintendo 64");
replace into games (name, console_name) values ( "Madden NFL 99", "Nintendo 64");
replace into games (name, console_name) values ( "Magical Tetris Challenge", "Nintendo 64");
replace into games (name, console_name) values ( "Major League Baseball featuring Ken Griffey Jr.", "Nintendo 64");
replace into games (name, console_name) values ( "Mario Golf", "Nintendo 64");
replace into games (name, console_name) values ( "Mario Kart 64", "Nintendo 64");
replace into games (name, console_name) values ( "Mario Party", "Nintendo 64");
replace into games (name, console_name) values ( "Mario Party 2", "Nintendo 64");
replace into games (name, console_name) values ( "Mario Party 3", "Nintendo 64");
replace into games (name, console_name) values ( "Mario Tennis", "Nintendo 64");
replace into games (name, console_name) values ( "Mega Man 64", "Nintendo 64");
replace into games (name, console_name) values ( "Mia Hamm Soccer 64", "Nintendo 64");
replace into games (name, console_name) values ( "Mickey no Racing Challenge USA", "Nintendo 64");
replace into games (name, console_name) values ( "Mickey's Speedway USA", "Nintendo 64");
replace into games (name, console_name) values ( "Micro Machines 64 Turbo", "Nintendo 64");
replace into games (name, console_name) values ( "Midway's Greatest Arcade Hits Vol. 1", "Nintendo 64");
replace into games (name, console_name) values ( "Mike Piazza's StrikeZone", "Nintendo 64");
replace into games (name, console_name) values ( "Milo's Astro Lanes", "Nintendo 64");
replace into games (name, console_name) values ( "Mischief Makers", "Nintendo 64");
replace into games (name, console_name) values ( "Mission Impossible", "Nintendo 64");
replace into games (name, console_name) values ( "Monaco Grand Prix", "Nintendo 64");
replace into games (name, console_name) values ( "Monopoly", "Nintendo 64");
replace into games (name, console_name) values ( "Monster Truck Madness 64", "Nintendo 64");
replace into games (name, console_name) values ( "Mortal Kombat 4", "Nintendo 64");
replace into games (name, console_name) values ( "Mortal Kombat Mythologies - Sub-Zero", "Nintendo 64");
replace into games (name, console_name) values ( "Mortal Kombat Trilogy", "Nintendo 64");
replace into games (name, console_name) values ( "Ms. Pac-Man - Maze Madness", "Nintendo 64");
replace into games (name, console_name) values ( "Mystical Ninja Starring Goemon", "Nintendo 64");
replace into games (name, console_name) values ( "NASCAR 2000", "Nintendo 64");
replace into games (name, console_name) values ( "NASCAR 99", "Nintendo 64");
replace into games (name, console_name) values ( "NBA Courtside 2 featuring Kobe Bryant", "Nintendo 64");
replace into games (name, console_name) values ( "NBA Hangtime", "Nintendo 64");
replace into games (name, console_name) values ( "NBA Jam 2000", "Nintendo 64");
replace into games (name, console_name) values ( "NBA Jam 99", "Nintendo 64");
replace into games (name, console_name) values ( "NBA Live 2000", "Nintendo 64");
replace into games (name, console_name) values ( "NBA Live 99", "Nintendo 64");
replace into games (name, console_name) values ( "NBA Showtime - NBA on NBC", "Nintendo 64");
replace into games (name, console_name) values ( "NBA in the Zone '98", "Nintendo 64");
replace into games (name, console_name) values ( "NBA in the Zone '99", "Nintendo 64");
replace into games (name, console_name) values ( "NBA in the Zone 2000", "Nintendo 64");
replace into games (name, console_name) values ( "NFL Blitz", "Nintendo 64");
replace into games (name, console_name) values ( "NFL Blitz - Special Edition", "Nintendo 64");
replace into games (name, console_name) values ( "NFL Blitz 2000", "Nintendo 64");
replace into games (name, console_name) values ( "NFL Blitz 2001", "Nintendo 64");
replace into games (name, console_name) values ( "NFL Quarterback Club 2000", "Nintendo 64");
replace into games (name, console_name) values ( "NFL Quarterback Club 2001", "Nintendo 64");
replace into games (name, console_name) values ( "NFL Quarterback Club 98", "Nintendo 64");
replace into games (name, console_name) values ( "NFL Quarterback Club 99", "Nintendo 64");
replace into games (name, console_name) values ( "NHL 99", "Nintendo 64");
replace into games (name, console_name) values ( "NHL Blades of Steel '99", "Nintendo 64");
replace into games (name, console_name) values ( "NHL Breakaway 98", "Nintendo 64");
replace into games (name, console_name) values ( "NHL Breakaway 99", "Nintendo 64");
replace into games (name, console_name) values ( "Nagano Winter Olympics '98", "Nintendo 64");
replace into games (name, console_name) values ( "Namco Museum 64", "Nintendo 64");
replace into games (name, console_name) values ( "New Tetris, The", "Nintendo 64");
replace into games (name, console_name) values ( "Nightmare Creatures", "Nintendo 64");
replace into games (name, console_name) values ( "Nuclear Strike 64", "Nintendo 64");
replace into games (name, console_name) values ( "O.D.T.", "Nintendo 64");
replace into games (name, console_name) values ( "Off Road Challenge", "Nintendo 64");
replace into games (name, console_name) values ( "Ogre Battle 64 - Person of Lordly Caliber", "Nintendo 64");
replace into games (name, console_name) values ( "Olympic Hockey Nagano '98", "Nintendo 64");
replace into games (name, console_name) values ( "PGA European Tour", "Nintendo 64");
replace into games (name, console_name) values ( "Paper Mario", "Nintendo 64");
replace into games (name, console_name) values ( "Paperboy", "Nintendo 64");
replace into games (name, console_name) values ( "Penny Racers", "Nintendo 64");
replace into games (name, console_name) values ( "Perfect Dark", "Nintendo 64");
replace into games (name, console_name) values ( "Pilotwings 64", "Nintendo 64");
replace into games (name, console_name) values ( "Pokemon Puzzle League", "Nintendo 64");
replace into games (name, console_name) values ( "Pokemon Snap", "Nintendo 64");
replace into games (name, console_name) values ( "Pokemon Snap Station", "Nintendo 64");
replace into games (name, console_name) values ( "Pokemon Stadium", "Nintendo 64");
replace into games (name, console_name) values ( "Pokemon Stadium 2", "Nintendo 64");
replace into games (name, console_name) values ( "Polaris SnoCross", "Nintendo 64");
replace into games (name, console_name) values ( "Power Rangers - Lightspeed Rescue", "Nintendo 64");
replace into games (name, console_name) values ( "Powerpuff Girls, The - Chemical X-Traction", "Nintendo 64");
replace into games (name, console_name) values ( "Quake 64", "Nintendo 64");
replace into games (name, console_name) values ( "Quake II", "Nintendo 64");
replace into games (name, console_name) values ( "Quest 64", "Nintendo 64");
replace into games (name, console_name) values ( "RR64 - Ridge Racer 64", "Nintendo 64");
replace into games (name, console_name) values ( "Rally Challenge 2000", "Nintendo 64");
replace into games (name, console_name) values ( "Rampage - World Tour", "Nintendo 64");
replace into games (name, console_name) values ( "Rampage 2 - Universal Tour", "Nintendo 64");
replace into games (name, console_name) values ( "Rat Attack!", "Nintendo 64");
replace into games (name, console_name) values ( "Rayman 2 - The Great Escape", "Nintendo 64");
replace into games (name, console_name) values ( "Razor Freestyle Scooter", "Nintendo 64");
replace into games (name, console_name) values ( "Re-Volt", "Nintendo 64");
replace into games (name, console_name) values ( "Ready 2 Rumble Boxing", "Nintendo 64");
replace into games (name, console_name) values ( "Ready 2 Rumble Boxing - Round 2", "Nintendo 64");
replace into games (name, console_name) values ( "Resident Evil 2", "Nintendo 64");
replace into games (name, console_name) values ( "Road Rash 64", "Nintendo 64");
replace into games (name, console_name) values ( "Roadsters Trophy", "Nintendo 64");
replace into games (name, console_name) values ( "Robotech - Crystal Dreams", "Nintendo 64");
replace into games (name, console_name) values ( "Robotron 64", "Nintendo 64");
replace into games (name, console_name) values ( "Rocket - Robot on Wheels", "Nintendo 64");
replace into games (name, console_name) values ( "Rugrats - Scavenger Hunt", "Nintendo 64");
replace into games (name, console_name) values ( "Rugrats in Paris - The Movie", "Nintendo 64");
replace into games (name, console_name) values ( "Rush 2 - Extreme Racing USA", "Nintendo 64");
replace into games (name, console_name) values ( "S.C.A.R.S.", "Nintendo 64");
replace into games (name, console_name) values ( "San Francisco Rush - Extreme Racing", "Nintendo 64");
replace into games (name, console_name) values ( "San Francisco Rush 2049", "Nintendo 64");
replace into games (name, console_name) values ( "Scooby-Doo! - Classic Creep Capers", "Nintendo 64");
replace into games (name, console_name) values ( "Shadow Man", "Nintendo 64");
replace into games (name, console_name) values ( "Shadowgate 64 - Trials of the Four Towers", "Nintendo 64");
replace into games (name, console_name) values ( "Snowboard Kids", "Nintendo 64");
replace into games (name, console_name) values ( "Snowboard Kids 2", "Nintendo 64");
replace into games (name, console_name) values ( "South Park", "Nintendo 64");
replace into games (name, console_name) values ( "South Park - Chef's Luv Shack", "Nintendo 64");
replace into games (name, console_name) values ( "South Park Rally", "Nintendo 64");
replace into games (name, console_name) values ( "Space Invaders", "Nintendo 64");
replace into games (name, console_name) values ( "SpaceStation Silicon Valley", "Nintendo 64");
replace into games (name, console_name) values ( "Spider-Man", "Nintendo 64");
replace into games (name, console_name) values ( "Star Fox 64", "Nintendo 64");
replace into games (name, console_name) values ( "Star Soldier - Vanishing Earth", "Nintendo 64");
replace into games (name, console_name) values ( "Star Wars - Rogue Squadron", "Nintendo 64");
replace into games (name, console_name) values ( "Star Wars - Shadows of the Empire", "Nintendo 64");
replace into games (name, console_name) values ( "Star Wars Episode I - Battle for Naboo", "Nintendo 64");
replace into games (name, console_name) values ( "Star Wars Episode I - Racer", "Nintendo 64");
replace into games (name, console_name) values ( "StarCraft 64", "Nintendo 64");
replace into games (name, console_name) values ( "Starshot - Space Circus Fever", "Nintendo 64");
replace into games (name, console_name) values ( "Stunt Racer 64", "Nintendo 64");
replace into games (name, console_name) values ( "Super Bowling", "Nintendo 64");
replace into games (name, console_name) values ( "Super Mario 64", "Nintendo 64");
replace into games (name, console_name) values ( "Super Smash Bros.", "Nintendo 64");
replace into games (name, console_name) values ( "Supercross 2000", "Nintendo 64");
replace into games (name, console_name) values ( "Superman", "Nintendo 64");
replace into games (name, console_name) values ( "Tarzan", "Nintendo 64");
replace into games (name, console_name) values ( "Tetrisphere", "Nintendo 64");
replace into games (name, console_name) values ( "Tigger's Honey Hunt", "Nintendo 64");
replace into games (name, console_name) values ( "Tom Clancy's Rainbow Six", "Nintendo 64");
replace into games (name, console_name) values ( "Tom and Jerry in Fists of Furry", "Nintendo 64");
replace into games (name, console_name) values ( "Tonic Trouble", "Nintendo 64");
replace into games (name, console_name) values ( "Tony Hawk's Pro Skater", "Nintendo 64");
replace into games (name, console_name) values ( "Tony Hawk's Pro Skater 2", "Nintendo 64");
replace into games (name, console_name) values ( "Tony Hawk's Pro Skater 3", "Nintendo 64");
replace into games (name, console_name) values ( "Top Gear Hyper-Bike", "Nintendo 64");
replace into games (name, console_name) values ( "Top Gear Overdrive", "Nintendo 64");
replace into games (name, console_name) values ( "Top Gear Rally", "Nintendo 64");
replace into games (name, console_name) values ( "Top Gear Rally 2", "Nintendo 64");
replace into games (name, console_name) values ( "Toy Story 2", "Nintendo 64");
replace into games (name, console_name) values ( "Transformers - Beast Wars Transmetals", "Nintendo 64");
replace into games (name, console_name) values ( "Triple Play 2000", "Nintendo 64");
replace into games (name, console_name) values ( "Turok - Dinosaur Hunter", "Nintendo 64");
replace into games (name, console_name) values ( "Turok - Rage Wars", "Nintendo 64");
replace into games (name, console_name) values ( "Turok 2 - Seeds of Evil", "Nintendo 64");
replace into games (name, console_name) values ( "Turok 3 - Shadow of Oblivion", "Nintendo 64");
replace into games (name, console_name) values ( "Twisted Edge - Extreme Snowboarding", "Nintendo 64");
replace into games (name, console_name) values ( "V-Rally Edition 99", "Nintendo 64");
replace into games (name, console_name) values ( "Vigilante 8", "Nintendo 64");
replace into games (name, console_name) values ( "Vigilante 8 - 2nd Offense", "Nintendo 64");
replace into games (name, console_name) values ( "Virtual Chess 64", "Nintendo 64");
replace into games (name, console_name) values ( "Virtual Pool 64", "Nintendo 64");
replace into games (name, console_name) values ( "WCW Backstage Assault", "Nintendo 64");
replace into games (name, console_name) values ( "WCW Mayhem", "Nintendo 64");
replace into games (name, console_name) values ( "WCW Nitro", "Nintendo 64");
replace into games (name, console_name) values ( "WCW vs. nWo - World Tour", "Nintendo 64");
replace into games (name, console_name) values ( "WCW-nWo Revenge", "Nintendo 64");
replace into games (name, console_name) values ( "WWF Attitude", "Nintendo 64");
replace into games (name, console_name) values ( "WWF No Mercy", "Nintendo 64");
replace into games (name, console_name) values ( "WWF War Zone", "Nintendo 64");
replace into games (name, console_name) values ( "WWF WrestleMania 2000", "Nintendo 64");
replace into games (name, console_name) values ( "Waialae Country Club - True Golf Classics", "Nintendo 64");
replace into games (name, console_name) values ( "War Gods", "Nintendo 64");
replace into games (name, console_name) values ( "Wave Race 64", "Nintendo 64");
replace into games (name, console_name) values ( "Wayne Gretzky's 3D Hockey", "Nintendo 64");
replace into games (name, console_name) values ( "Wayne Gretzky's 3D Hockey '98", "Nintendo 64");
replace into games (name, console_name) values ( "Wetrix", "Nintendo 64");
replace into games (name, console_name) values ( "Wheel of Fortune", "Nintendo 64");
replace into games (name, console_name) values ( "WinBack - Covert Operations", "Nintendo 64");
replace into games (name, console_name) values ( "Wipeout 64", "Nintendo 64");
replace into games (name, console_name) values ( "World Cup 98", "Nintendo 64");
replace into games (name, console_name) values ( "World Driver Championship", "Nintendo 64");
replace into games (name, console_name) values ( "Worms Armageddon", "Nintendo 64");
replace into games (name, console_name) values ( "Xena - Warrior Princess - The Talisman of Fate", "Nintendo 64");
replace into games (name, console_name) values ( "Yoshi's Story", "Nintendo 64");
