replace into games (name, console_name) values ( '3D Pocket Pool', 'Game Boy Color');
replace into games (name, console_name) values ( '3D Ultra Pinball: Thrillride', 'Game Boy Color');
replace into games (name, console_name) values ( '4x4 World Trophy', 'Game Boy Color');
replace into games (name, console_name) values ( '10 Pin Bowling', 'Game Boy Color');
replace into games (name, console_name) values ( '102 Dalmatians: Puppies to the Rescue', 'Game Boy Color');
replace into games (name, console_name) values ( '1942', 'Game Boy Color');
replace into games (name, console_name) values ( '720', 'Game Boy Color');
replace into games (name, console_name) values ( 'Action Man: Search for Base X', 'Game Boy Color');
replace into games (name, console_name) values ( 'Airforce Delta', 'Game Boy Color');
replace into games (name, console_name) values ( 'Aladdin', 'Game Boy Color');
replace into games (name, console_name) values ( 'Alfred Chicken', 'Game Boy Color');
replace into games (name, console_name) values ( 'Alice in Wonderland', 'Game Boy Color');
replace into games (name, console_name) values ( 'Aliens: Thanatos Encounter', 'Game Boy Color');
replace into games (name, console_name) values ( 'All-Star Baseball 2000', 'Game Boy Color');
replace into games (name, console_name) values ( 'All-Star Baseball 2001', 'Game Boy Color');
replace into games (name, console_name) values ( 'All-Star Tennis 2000', 'Game Boy Color');
replace into games (name, console_name) values ( 'Alone in the Dark: The New Nightmare', 'Game Boy Color');
replace into games (name, console_name) values ( 'Animorphs', 'Game Boy Color');
replace into games (name, console_name) values ( 'Antz', 'Game Boy Color');
replace into games (name, console_name) values ( 'Antz Racing', 'Game Boy Color');
replace into games (name, console_name) values ( 'Armada FX Racers', 'Game Boy Color');
replace into games (name, console_name) values ( 'Armorines: Project Swarm', 'Game Boy Color');
replace into games (name, console_name) values ( 'Army Men', 'Game Boy Color');
replace into games (name, console_name) values ( 'Army Men 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Army Men: Air Combat', 'Game Boy Color');
replace into games (name, console_name) values ( 'Army Men: Sarges Heroes 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Arthurs Absolutely Fun Day', 'Game Boy Color');
replace into games (name, console_name) values ( 'Astérix: Search for Dogmatix', 'Game Boy Color');
replace into games (name, console_name) values ( 'Atlantis: The Lost Empire', 'Game Boy Color');
replace into games (name, console_name) values ( 'Austin Powers: Oh Behave', 'Game Boy Color');
replace into games (name, console_name) values ( 'Austin Powers: Welcome to My Underground Lair!', 'Game Boy Color');
replace into games (name, console_name) values ( 'Other Life: Azure Dreams', 'Game Boy Color');
replace into games (name, console_name) values ( 'Babe and Friends', 'Game Boy Color');
replace into games (name, console_name) values ( 'Baby Felix Halloween', 'Game Boy Color');
replace into games (name, console_name) values ( 'Backgammon', 'Game Boy Color');
replace into games (name, console_name) values ( 'Ballistic', 'Game Boy Color');
replace into games (name, console_name) values ( 'Barbie Fashion Pack Games', 'Game Boy Color');
replace into games (name, console_name) values ( 'Barbie Magic Genie Adventure', 'Game Boy Color');
replace into games (name, console_name) values ( 'Barbie Ocean Discovery', 'Game Boy Color');
replace into games (name, console_name) values ( 'Barbie Pet Rescue', 'Game Boy Color');
replace into games (name, console_name) values ( 'Barbie Kelly Club', 'Game Boy Color');
replace into games (name, console_name) values ( 'Bass Masters Classic', 'Game Boy Color');
replace into games (name, console_name) values ( 'Batman Beyond: Return of the Joker', 'Game Boy Color');
replace into games (name, console_name) values ( 'Batman: Chaos in Gotham', 'Game Boy Color');
replace into games (name, console_name) values ( 'Battleship', 'Game Boy Color');
replace into games (name, console_name) values ( 'Battletanx', 'Game Boy Color');
replace into games (name, console_name) values ( 'Bear in the Big Blue House', 'Game Boy Color');
replace into games (name, console_name) values ( 'Beast Wars: Transformers', 'Game Boy Color');
replace into games (name, console_name) values ( 'Beauty and the Beast: A Board Game Adventure', 'Game Boy Color');
replace into games (name, console_name) values ( 'Billy Bobs Huntin n Fishin', 'Game Boy Color');
replace into games (name, console_name) values ( 'Bionic Commando: Elite Forces', 'Game Boy Color');
replace into games (name, console_name) values ( 'Black Bass Lure Fishing', 'Game Boy Color');
replace into games (name, console_name) values ( 'Blade', 'Game Boy Color');
replace into games (name, console_name) values ( 'Blaster Master: Enemy Below', 'Game Boy Color');
replace into games (name, console_name) values ( 'Blues Clues Alphabet Book', 'Game Boy Color');
replace into games (name, console_name) values ( 'Boarder Zone', 'Game Boy Color');
replace into games (name, console_name) values ( 'Bob the Builder', 'Game Boy Color');
replace into games (name, console_name) values ( 'Bomberman Max: Blue Champion', 'Game Boy Color');
replace into games (name, console_name) values ( 'Bomberman Max: Red Challenger', 'Game Boy Color');
replace into games (name, console_name) values ( 'Bomberman Quest', 'Game Boy Color');
replace into games (name, console_name) values ( 'Bubble Bobble', 'Game Boy Color');
replace into games (name, console_name) values ( 'Buffy the Vampire Slayer', 'Game Boy Color');
replace into games (name, console_name) values ( 'Bugs Bunny Crazy Castle 3', 'Game Boy Color');
replace into games (name, console_name) values ( 'Bugs Bunny Crazy Castle 4', 'Game Boy Color');
replace into games (name, console_name) values ( 'A Bugs Life', 'Game Boy Color');
replace into games (name, console_name) values ( 'Bust A Move 4', 'Game Boy Color');
replace into games (name, console_name) values ( 'Bust A Move Millennium', 'Game Boy Color');
replace into games (name, console_name) values ( 'Buzz Lightyear of Star Command', 'Game Boy Color');
replace into games (name, console_name) values ( 'Caesars Palace 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Cannon Fodder', 'Game Boy Color');
replace into games (name, console_name) values ( 'Carl Lewis Athletics 2000', 'Game Boy Color');
replace into games (name, console_name) values ( 'Carmageddon', 'Game Boy Color');
replace into games (name, console_name) values ( 'Casper the Friendly Ghost', 'Game Boy Color');
replace into games (name, console_name) values ( 'Catwoman', 'Game Boy Color');
replace into games (name, console_name) values ( 'Catz', 'Game Boy Color');
replace into games (name, console_name) values ( 'Centipede', 'Game Boy Color');
replace into games (name, console_name) values ( 'Championship Motocross 2001 featuring Ricky Carmichael', 'Game Boy Color');
replace into games (name, console_name) values ( 'Chase H.Q. Secret Police', 'Game Boy Color');
replace into games (name, console_name) values ( 'Chessmaster', 'Game Boy Color');
replace into games (name, console_name) values ( 'Chicken Run', 'Game Boy Color');
replace into games (name, console_name) values ( 'Colin McRae Rally', 'Game Boy Color');
replace into games (name, console_name) values ( 'Commander Keen', 'Game Boy Color');
replace into games (name, console_name) values ( 'Conkers Pocket Tales', 'Game Boy Color');
replace into games (name, console_name) values ( 'Cool Bricks', 'Game Boy Color');
replace into games (name, console_name) values ( 'Croc: Legend of the Gobbos', 'Game Boy Color');
replace into games (name, console_name) values ( 'Croc 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Cruisn Exotica', 'Game Boy Color');
replace into games (name, console_name) values ( 'Crystalis', 'Game Boy Color');
replace into games (name, console_name) values ( 'Cubix: Robots for Everyone Race n Robots', 'Game Boy Color');
replace into games (name, console_name) values ( 'Cyber Tiger Woods Golf', 'Game Boy Color');
replace into games (name, console_name) values ( 'Daffy Duck - Fowl Play', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dance Dance Revolution GB', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dance Dance Revolution GB2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dance Dance Revolution GB3', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dance Dance Revolution GB Disney Mix', 'Game Boy Color');
replace into games (name, console_name) values ( 'Oha Star Dance Dance Revolution GB', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dancing Furby', 'Game Boy Color');
replace into games (name, console_name) values ( 'Daikatana', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dave Mirra Freestyle BMX', 'Game Boy Color');
replace into games (name, console_name) values ( 'David Beckham Soccer', 'Game Boy Color');
replace into games (name, console_name) values ( 'Deer Hunter', 'Game Boy Color');
replace into games (name, console_name) values ( 'Defender/Joust', 'Game Boy Color');
replace into games (name, console_name) values ( 'Déjà Vu I & II', 'Game Boy Color');
replace into games (name, console_name) values ( 'Denki Blocks', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dexters Laboratory: Robot Rampage', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dinosaurus', 'Game Boy Color');
replace into games (name, console_name) values ( 'Disneys Dinosaur', 'Game Boy Color');
replace into games (name, console_name) values ( 'Diva Starz: Mall Mania', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dogz', 'Game Boy Color');
replace into games (name, console_name) values ( 'Donald Duck: Goin Quackers', 'Game Boy Color');
replace into games (name, console_name) values ( 'Donkey Kong Country', 'Game Boy Color');
replace into games (name, console_name) values ( 'Donkey Kong GB: Dinky Kong & Dixie Kong', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dougs Big Game', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dracula: Crazy Vampire', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dragon Ball Z: Legendary Super Warriors', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dragon Dance', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dragon Tales Adventure', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dragon Tales: Dragon Wings', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dragon Warrior I & II', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dragon Warrior III', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dragon Warrior Monsters', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dragon Warrior Monsters II: Cobis Journey', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dragon Warrior Monsters II: Taras Adventure', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dragons Lair', 'Game Boy Color');
replace into games (name, console_name) values ( 'Driver', 'Game Boy Color');
replace into games (name, console_name) values ( 'Dropzone', 'Game Boy Color');
replace into games (name, console_name) values ( 'Duke Nukem', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Dukes of Hazzard', 'Game Boy Color');
replace into games (name, console_name) values ( 'Earthworm Jim: Menace 2 the Galaxy', 'Game Boy Color');
replace into games (name, console_name) values ( 'ECW Hardcore Revolution', 'Game Boy Color');
replace into games (name, console_name) values ( 'Elevator Action EX', 'Game Boy Color');
replace into games (name, console_name) values ( 'Elmo in Grouchland', 'Game Boy Color');
replace into games (name, console_name) values ( 'Elmos 123s', 'Game Boy Color');
replace into games (name, console_name) values ( 'Elmos ABCs', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Emperors New Groove', 'Game Boy Color');
replace into games (name, console_name) values ( 'ESPN International Track & Field', 'Game Boy Color');
replace into games (name, console_name) values ( 'ESPN National Hockey Night', 'Game Boy Color');
replace into games (name, console_name) values ( 'ET and the Cosmic Garden', 'Game Boy Color');
replace into games (name, console_name) values ( 'ET Digital Companion', 'Game Boy Color');
replace into games (name, console_name) values ( 'ET Escape From Planet Earth', 'Game Boy Color');
replace into games (name, console_name) values ( 'European Super League', 'Game Boy Color');
replace into games (name, console_name) values ( 'Evel Knievel', 'Game Boy Color');
replace into games (name, console_name) values ( 'Extreme Ghostbusters', 'Game Boy Color');
replace into games (name, console_name) values ( 'Extreme Sports with the Berenstain Bears', 'Game Boy Color');
replace into games (name, console_name) values ( 'F1 Championship Season 2000', 'Game Boy Color');
replace into games (name, console_name) values ( 'F1 Racing Championship', 'Game Boy Color');
replace into games (name, console_name) values ( 'F1 World Grand Prix', 'Game Boy Color');
replace into games (name, console_name) values ( 'F1 World Grand Prix II', 'Game Boy Color');
replace into games (name, console_name) values ( 'F-18 Thunder Strike', 'Game Boy Color');
replace into games (name, console_name) values ( 'FA Premier League Stars 2001', 'Game Boy Color');
replace into games (name, console_name) values ( 'FIFA 2000', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Fish Files', 'Game Boy Color');
replace into games (name, console_name) values ( 'Fisher Price Rescue Heroes Fire Frenzy', 'Game Boy Color');
replace into games (name, console_name) values ( 'Fix and Foxi', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Flintstones Starring in Burgertime in Bedrock', 'Game Boy Color');
replace into games (name, console_name) values ( 'Flipper and Lopaka', 'Game Boy Color');
replace into games (name, console_name) values ( 'Force 21', 'Game Boy Color');
replace into games (name, console_name) values ( 'Formula One 2000', 'Game Boy Color');
replace into games (name, console_name) values ( 'Fort Boyard', 'Game Boy Color');
replace into games (name, console_name) values ( 'Frogger', 'Game Boy Color');
replace into games (name, console_name) values ( 'Frogger 2: Swampys Revenge', 'Game Boy Color');
replace into games (name, console_name) values ( 'Galaga: Destination Earth', 'Game Boy Color');
replace into games (name, console_name) values ( 'Game & Watch Gallery 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Game & Watch Gallery 3', 'Game Boy Color');
replace into games (name, console_name) values ( 'Gex: Enter the Gecko', 'Game Boy Color');
replace into games (name, console_name) values ( 'Gex: Deep Cover Gecko', 'Game Boy Color');
replace into games (name, console_name) values ( 'Ghosts n Goblins', 'Game Boy Color');
replace into games (name, console_name) values ( 'Gift', 'Game Boy Color');
replace into games (name, console_name) values ( 'Gobs of Games', 'Game Boy Color');
replace into games (name, console_name) values ( 'Godzilla: The Series', 'Game Boy Color');
replace into games (name, console_name) values ( 'Godzilla: The Series - Monster Wars', 'Game Boy Color');
replace into games (name, console_name) values ( 'Gold and Glory: The Road to El Dorado', 'Game Boy Color');
replace into games (name, console_name) values ( 'Golden Goal', 'Game Boy Color');
replace into games (name, console_name) values ( 'Grand Theft Auto', 'Game Boy Color');
replace into games (name, console_name) values ( 'Grand Theft Auto 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Gremlins Unleashed', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Grinch', 'Game Boy Color');
replace into games (name, console_name) values ( 'Halloween Racer', 'Game Boy Color');
replace into games (name, console_name) values ( 'Hamtaro: Tomodachi Daisakusen Dechu', 'Game Boy Color');
replace into games (name, console_name) values ( 'Hamtaro: Ham-Hams Unite!', 'Game Boy Color');
replace into games (name, console_name) values ( 'Hands of Time', 'Game Boy Color');
replace into games (name, console_name) values ( 'Harley Davidson: Race Across America', 'Game Boy Color');
replace into games (name, console_name) values ( 'Harry Potter and the Chamber of Secrets', 'Game Boy Color');
replace into games (name, console_name) values ( 'Harry Potter and the Sorcerers Stone', 'Game Boy Color');
replace into games (name, console_name) values ( 'Harvest Moon', 'Game Boy Color');
replace into games (name, console_name) values ( 'Harvest Moon 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Harvest Moon 3', 'Game Boy Color');
replace into games (name, console_name) values ( 'Hello Kittys Cube Frenzy', 'Game Boy Color');
replace into games (name, console_name) values ( 'Hercules: The Legendary Journeys', 'Game Boy Color');
replace into games (name, console_name) values ( 'Heroes of Might and Magic', 'Game Boy Color');
replace into games (name, console_name) values ( 'Heroes of Might and Magic 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Hexcite', 'Game Boy Color');
replace into games (name, console_name) values ( 'Hole in One Golf', 'Game Boy Color');
replace into games (name, console_name) values ( 'Hollywood Pinball', 'Game Boy Color');
replace into games (name, console_name) values ( 'Hot Wheels Stunt Track Driver', 'Game Boy Color');
replace into games (name, console_name) values ( 'Hoyle Card Games', 'Game Boy Color');
replace into games (name, console_name) values ( 'Hoyle Casino', 'Game Boy Color');
replace into games (name, console_name) values ( 'Hugo 2.5', 'Game Boy Color');
replace into games (name, console_name) values ( 'Hugo: Black Diamond Fever', 'Game Boy Color');
replace into games (name, console_name) values ( 'Hugo: The Evil Mirror', 'Game Boy Color');
replace into games (name, console_name) values ( 'Hype: The Time Quest', 'Game Boy Color');
replace into games (name, console_name) values ( 'Indiana Jones and the Infernal Machine', 'Game Boy Color');
replace into games (name, console_name) values ( 'Inspector Gadget: Operation Madkactus', 'Game Boy Color');
replace into games (name, console_name) values ( 'International Karate', 'Game Boy Color');
replace into games (name, console_name) values ( 'International Rally', 'Game Boy Color');
replace into games (name, console_name) values ( 'International Superstar Soccer 99', 'Game Boy Color');
replace into games (name, console_name) values ( 'International Superstar Soccer 2000', 'Game Boy Color');
replace into games (name, console_name) values ( 'International Track & Field', 'Game Boy Color');
replace into games (name, console_name) values ( 'Jeff Gordon XS Racing', 'Game Boy Color');
replace into games (name, console_name) values ( 'Jeremy McGraths Supercross 2000', 'Game Boy Color');
replace into games (name, console_name) values ( 'Jimmy Whites Cueball', 'Game Boy Color');
replace into games (name, console_name) values ( 'Jumpstart Dino Adventure Field Trip', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Jungle Book: Mowglis Wild Adventure', 'Game Boy Color');
replace into games (name, console_name) values ( 'Keep the Balance', 'Game Boy Color');
replace into games (name, console_name) values ( 'Keitai Denju Telefang - Power Version', 'Game Boy Color');
replace into games (name, console_name) values ( 'Keitai Denju Telefang - Speed Version', 'Game Boy Color');
replace into games (name, console_name) values ( 'Ken Griffey Jrs Slugfest', 'Game Boy Color');
replace into games (name, console_name) values ( 'Kirby Tilt n Tumble', 'Game Boy Color');
replace into games (name, console_name) values ( 'Kirikou', 'Game Boy Color');
replace into games (name, console_name) values ( 'Klax', 'Game Boy Color');
replace into games (name, console_name) values ( 'Klustar', 'Game Boy Color');
replace into games (name, console_name) values ( 'Knockout Kings', 'Game Boy Color');
replace into games (name, console_name) values ( 'Konami GB Collection Vol.1', 'Game Boy Color');
replace into games (name, console_name) values ( 'Konami GB Collection Vol.2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Konami GB Collection Vol.3', 'Game Boy Color');
replace into games (name, console_name) values ( 'Konami GB Collection Vol.4', 'Game Boy Color');
replace into games (name, console_name) values ( 'Koto Battle: Tengai no Moribito', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Land Before Time', 'Game Boy Color');
replace into games (name, console_name) values ( 'Las Vegas Cool Hand', 'Game Boy Color');
replace into games (name, console_name) values ( 'Laura', 'Game Boy Color');
replace into games (name, console_name) values ( 'Legend of the River King', 'Game Boy Color');
replace into games (name, console_name) values ( 'Legend of the River King 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Legend of Zelda: Links Awakening DX', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Legend of Zelda: Oracle of Ages', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Legend of Zelda: Oracle of Seasons', 'Game Boy Color');
replace into games (name, console_name) values ( 'Lego Alpha Team', 'Game Boy Color');
replace into games (name, console_name) values ( 'Lego Island 2: The Bricksters Revenge', 'Game Boy Color');
replace into games (name, console_name) values ( 'Lego Racers', 'Game Boy Color');
replace into games (name, console_name) values ( 'Lego Stunt Rally', 'Game Boy Color');
replace into games (name, console_name) values ( 'Lemmings & Oh No! More Lemmings', 'Game Boy Color');
replace into games (name, console_name) values ( 'Lil Monster', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Lion King: Simbas Mighty Adventure', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Little Mermaid 2: Pinball Frenzy', 'Game Boy Color');
replace into games (name, console_name) values ( 'Little Nicky', 'Game Boy Color');
replace into games (name, console_name) values ( 'Logical', 'Game Boy Color');
replace into games (name, console_name) values ( 'Looney Tunes', 'Game Boy Color');
replace into games (name, console_name) values ( 'Looney Tunes Collector: Alert!', 'Game Boy Color');
replace into games (name, console_name) values ( 'Looney Tunes: Carrot Crazy', 'Game Boy Color');
replace into games (name, console_name) values ( 'Looney Tunes: Marvin Strikes Back!', 'Game Boy Color');
replace into games (name, console_name) values ( 'Looney Tunes Racing', 'Game Boy Color');
replace into games (name, console_name) values ( 'Looney Tunes Twouble!', 'Game Boy Color');
replace into games (name, console_name) values ( 'Lucky Luke', 'Game Boy Color');
replace into games (name, console_name) values ( 'Lucky Luke: Desperado Train', 'Game Boy Color');
replace into games (name, console_name) values ( 'Lufia: The Legend Returns', 'Game Boy Color');
replace into games (name, console_name) values ( 'M&Ms Mini Madness', 'Game Boy Color');
replace into games (name, console_name) values ( 'Madden NFL 2000', 'Game Boy Color');
replace into games (name, console_name) values ( 'Madden NFL 2001', 'Game Boy Color');
replace into games (name, console_name) values ( 'Madden NFL 2002', 'Game Boy Color');
replace into games (name, console_name) values ( 'Magical Drop', 'Game Boy Color');
replace into games (name, console_name) values ( 'Magical Tetris Challenge', 'Game Boy Color');
replace into games (name, console_name) values ( 'Magi-Nation', 'Game Boy Color');
replace into games (name, console_name) values ( 'Marble Madness', 'Game Boy Color');
replace into games (name, console_name) values ( 'Mario Golf', 'Game Boy Color');
replace into games (name, console_name) values ( 'Mario Tennis', 'Game Boy Color');
replace into games (name, console_name) values ( 'Mary-Kate & Ashley: Crush Course', 'Game Boy Color');
replace into games (name, console_name) values ( 'Mary-Kate & Ashley: Get a Clue', 'Game Boy Color');
replace into games (name, console_name) values ( 'Mary-Kate & Ashley: Pocket Planner', 'Game Boy Color');
replace into games (name, console_name) values ( 'Mary-Kate & Ashley: Winners Circle', 'Game Boy Color');
replace into games (name, console_name) values ( 'Mask of Zorro', 'Game Boy Color');
replace into games (name, console_name) values ( 'Mat Hoffmans Pro BMX', 'Game Boy Color');
replace into games (name, console_name) values ( 'Matchbox Caterpillar Construction Zone', 'Game Boy Color');
replace into games (name, console_name) values ( 'Matchbox Emergency Patrol', 'Game Boy Color');
replace into games (name, console_name) values ( 'Maya The Bee & Her Friends', 'Game Boy Color');
replace into games (name, console_name) values ( 'Maya The Bee - Garden Adventures', 'Game Boy Color');
replace into games (name, console_name) values ( 'Mega Man Xtreme', 'Game Boy Color');
replace into games (name, console_name) values ( 'Mega Man Xtreme 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Men in Black: The Series', 'Game Boy Color');
replace into games (name, console_name) values ( 'Men in Black: The Series 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Merlin', 'Game Boy Color');
replace into games (name, console_name) values ( 'Metal Gear: Ghost Babel', 'Game Boy Color');
replace into games (name, console_name) values ( 'Metal Walker', 'Game Boy Color');
replace into games (name, console_name) values ( 'Mia Hamm Soccer Shootout', 'Game Boy Color');
replace into games (name, console_name) values ( 'Mickeys Racing Adventure', 'Game Boy Color');
replace into games (name, console_name) values ( 'Mickeys Speedway USA', 'Game Boy Color');
replace into games (name, console_name) values ( 'Micro Machines 1&2 Twin Turbo', 'Game Boy Color');
replace into games (name, console_name) values ( 'Micro Machines V3', 'Game Boy Color');
replace into games (name, console_name) values ( 'Micro Maniacs', 'Game Boy Color');
replace into games (name, console_name) values ( 'Microsoft Entertainment Pak', 'Game Boy Color');
replace into games (name, console_name) values ( 'Microsoft Pinball Arcade', 'Game Boy Color');
replace into games (name, console_name) values ( 'Microsoft Puzzle Collection', 'Game Boy Color');
replace into games (name, console_name) values ( 'Millennium Winter Sports', 'Game Boy Color');
replace into games (name, console_name) values ( 'Missile Command', 'Game Boy Color');
replace into games (name, console_name) values ( 'Mission: Impossible', 'Game Boy Color');
replace into games (name, console_name) values ( 'Mobile Golf', 'Game Boy Color');
replace into games (name, console_name) values ( 'Monkey Puncher', 'Game Boy Color');
replace into games (name, console_name) values ( 'Monopoly', 'Game Boy Color');
replace into games (name, console_name) values ( 'DX Monopoly GB', 'Game Boy Color');
replace into games (name, console_name) values ( 'Monster Rancher BattleCard GB', 'Game Boy Color');
replace into games (name, console_name) values ( 'Monster Rancher Explorer', 'Game Boy Color');
replace into games (name, console_name) values ( 'Monsters, Inc', 'Game Boy Color');
replace into games (name, console_name) values ( 'Montezumas Return', 'Game Boy Color');
replace into games (name, console_name) values ( 'Moomins Tale', 'Game Boy Color');
replace into games (name, console_name) values ( 'Moon Patrol & Spy Hunter', 'Game Boy Color');
replace into games (name, console_name) values ( 'Moorhen 3 - The Chicken Chase!', 'Game Boy Color');
replace into games (name, console_name) values ( 'Mortal Kombat 4', 'Game Boy Color');
replace into games (name, console_name) values ( 'Motocross Maniacs 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Mr. Driller', 'Game Boy Color');
replace into games (name, console_name) values ( 'Mr. Nutz', 'Game Boy Color');
replace into games (name, console_name) values ( 'Ms. Pac-Man', 'Game Boy Color');
replace into games (name, console_name) values ( 'MTV Sports: T.J. Lavin’s Ultimate BMX', 'Game Boy Color');
replace into games (name, console_name) values ( 'MTV Sports: Pure Ride', 'Game Boy Color');
replace into games (name, console_name) values ( 'MTV Sports: Skateboarding featuring Andy Macdonald', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Mummy', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Mummy Returns', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Muppets', 'Game Boy Color');
replace into games (name, console_name) values ( 'NASCAR 2000', 'Game Boy Color');
replace into games (name, console_name) values ( 'NASCAR Challenge', 'Game Boy Color');
replace into games (name, console_name) values ( 'NASCAR Heat', 'Game Boy Color');
replace into games (name, console_name) values ( 'NASCAR Racers', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Nations: Land of Legends', 'Game Boy Color');
replace into games (name, console_name) values ( 'NBA 3 on 3 featuring Kobe Bryant', 'Game Boy Color');
replace into games (name, console_name) values ( 'NBA Hoopz', 'Game Boy Color');
replace into games (name, console_name) values ( 'NBA In the Zone', 'Game Boy Color');
replace into games (name, console_name) values ( 'NBA In the Zone 2000', 'Game Boy Color');
replace into games (name, console_name) values ( 'NBA Jam 99', 'Game Boy Color');
replace into games (name, console_name) values ( 'NBA Jam 2001', 'Game Boy Color');
replace into games (name, console_name) values ( 'NBA Showtime', 'Game Boy Color');
replace into games (name, console_name) values ( 'The New Adventures of Mary-Kate & Ashley', 'Game Boy Color');
replace into games (name, console_name) values ( 'NFL Blitz', 'Game Boy Color');
replace into games (name, console_name) values ( 'NFL Blitz 2000', 'Game Boy Color');
replace into games (name, console_name) values ( 'NFL Blitz 2001', 'Game Boy Color');
replace into games (name, console_name) values ( 'NHL 2000', 'Game Boy Color');
replace into games (name, console_name) values ( 'NHL Blades of Steel 99', 'Game Boy Color');
replace into games (name, console_name) values ( 'NHL Blades of Steel 2000', 'Game Boy Color');
replace into games (name, console_name) values ( 'Nicktoons Racing', 'Game Boy Color');
replace into games (name, console_name) values ( 'No Fear Downhill Mountain Biking', 'Game Boy Color');
replace into games (name, console_name) values ( 'Noddy and the Birthday Party', 'Game Boy Color');
replace into games (name, console_name) values ( 'NSYNC: Get to the Show', 'Game Boy Color');
replace into games (name, console_name) values ( 'NYR: New York Race', 'Game Boy Color');
replace into games (name, console_name) values ( 'Oide Rascal', 'Game Boy Color');
replace into games (name, console_name) values ( 'Obelix', 'Game Boy Color');
replace into games (name, console_name) values ( 'Oddworld Adventures II', 'Game Boy Color');
replace into games (name, console_name) values ( 'OLeary Manager 2000', 'Game Boy Color');
replace into games (name, console_name) values ( 'Other Life: Azure Dreams', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pac-Man', 'Game Boy Color');
replace into games (name, console_name) values ( 'Paperboy', 'Game Boy Color');
replace into games (name, console_name) values ( 'Papyrus', 'Game Boy Color');
replace into games (name, console_name) values ( 'Perfect Dark', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pitfall: Beyond the Jungle', 'Game Boy Color');
replace into games (name, console_name) values ( 'Planet of the Apes', 'Game Boy Color');
replace into games (name, console_name) values ( 'Player Manager 2001', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pocket Bomberman', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pocket Bowling', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pocket GT Racer', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pocket Music', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pocket Racing', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pocket Soccer', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pokémon Card GB2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pokémon Crystal', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pokémon Gold', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pokémon Pinball', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pokémon Puzzle Challenge', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pokémon Silver', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pokémon Trading Card Game', 'Game Boy Color');
replace into games (name, console_name) values ( 'Polaris Snocross', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pong', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pooh and Tiggers Hunny Safari', 'Game Boy Color');
replace into games (name, console_name) values ( 'Popn Music', 'Game Boy Color');
replace into games (name, console_name) values ( 'Popn Pop', 'Game Boy Color');
replace into games (name, console_name) values ( 'Portal Runner', 'Game Boy Color');
replace into games (name, console_name) values ( 'Power Quest', 'Game Boy Color');
replace into games (name, console_name) values ( 'Power Rangers Time Force', 'Game Boy Color');
replace into games (name, console_name) values ( 'Power Rangers Lightspeed Rescue', 'Game Boy Color');
replace into games (name, console_name) values ( 'Power Spike Pro Beach Volleyball', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Powerpuff Girls: Bad Mojo Jojo', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Powerpuff Girls: Battle Him', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Powerpuff Girls: Paint the Townsville Green', 'Game Boy Color');
replace into games (name, console_name) values ( 'Prince Naseem Boxing', 'Game Boy Color');
replace into games (name, console_name) values ( 'Prince of Persia', 'Game Boy Color');
replace into games (name, console_name) values ( 'Project S-11', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pro Darts', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pro Pool', 'Game Boy Color');
replace into games (name, console_name) values ( 'Puchi Carat', 'Game Boy Color');
replace into games (name, console_name) values ( 'Puyo Puyo SUN', 'Game Boy Color');
replace into games (name, console_name) values ( 'Puyo Puyo~n', 'Game Boy Color');
replace into games (name, console_name) values ( 'Puzzle Master', 'Game Boy Color');
replace into games (name, console_name) values ( 'Puzzled', 'Game Boy Color');
replace into games (name, console_name) values ( 'Q-Bert', 'Game Boy Color');
replace into games (name, console_name) values ( 'Qix Adventure', 'Game Boy Color');
replace into games (name, console_name) values ( 'Quest: Brians Journey', 'Game Boy Color');
replace into games (name, console_name) values ( 'Quest: Fantasy Challenge', 'Game Boy Color');
replace into games (name, console_name) values ( 'Quest for Camelot', 'Game Boy Color');
replace into games (name, console_name) values ( 'Qui Qui', 'Game Boy Color');
replace into games (name, console_name) values ( 'R-Type DX', 'Game Boy Color');
replace into games (name, console_name) values ( 'Rainbow Six', 'Game Boy Color');
replace into games (name, console_name) values ( 'Rainbow Islands', 'Game Boy Color');
replace into games (name, console_name) values ( 'Rampage: World Tour', 'Game Boy Color');
replace into games (name, console_name) values ( 'Rampage 2: Universal Tour', 'Game Boy Color');
replace into games (name, console_name) values ( 'Rampart', 'Game Boy Color');
replace into games (name, console_name) values ( 'Rats!', 'Game Boy Color');
replace into games (name, console_name) values ( 'Rayman', 'Game Boy Color');
replace into games (name, console_name) values ( 'Rayman 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Razor Freestyle Scooter', 'Game Boy Color');
replace into games (name, console_name) values ( 'Ready 2 Rumble', 'Game Boy Color');
replace into games (name, console_name) values ( 'Reservoir Rat', 'Game Boy Color');
replace into games (name, console_name) values ( 'Resident Evil Gaiden', 'Game Boy Color');
replace into games (name, console_name) values ( 'Return of the Ninja', 'Game Boy Color');
replace into games (name, console_name) values ( 'Revelations: The Demon Slayer', 'Game Boy Color');
replace into games (name, console_name) values ( 'Rhino Rumble', 'Game Boy Color');
replace into games (name, console_name) values ( 'Rip-Tide Racer', 'Game Boy Color');
replace into games (name, console_name) values ( 'Road Champs: BXS Stunt Biking', 'Game Boy Color');
replace into games (name, console_name) values ( 'Road Rash', 'Game Boy Color');
replace into games (name, console_name) values ( 'Roadsters 98', 'Game Boy Color');
replace into games (name, console_name) values ( 'Roadsters Trophy', 'Game Boy Color');
replace into games (name, console_name) values ( 'Robin Hood', 'Game Boy Color');
replace into games (name, console_name) values ( 'Robopon Sun, Star, and Moon Versions', 'Game Boy Color');
replace into games (name, console_name) values ( 'RoboCop', 'Game Boy Color');
replace into games (name, console_name) values ( 'Robot Wars: Metal Mayhem', 'Game Boy Color');
replace into games (name, console_name) values ( 'Rocket Power: Gettin Air', 'Game Boy Color');
replace into games (name, console_name) values ( 'Rocky Mountain Trophy Hunter', 'Game Boy Color');
replace into games (name, console_name) values ( 'Roland Garros French Open', 'Game Boy Color');
replace into games (name, console_name) values ( 'Ronaldo V-Soccer', 'Game Boy Color');
replace into games (name, console_name) values ( 'Roswell Conspiracies: Aliens, Myths & Legends', 'Game Boy Color');
replace into games (name, console_name) values ( 'Rox', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Rugrats Movie', 'Game Boy Color');
replace into games (name, console_name) values ( 'Rugrats in Paris: The Movie', 'Game Boy Color');
replace into games (name, console_name) values ( 'Rugrats: Time Travelers', 'Game Boy Color');
replace into games (name, console_name) values ( 'Rugrats: Totally Angelica', 'Game Boy Color');
replace into games (name, console_name) values ( 'Sabrina the Animated Series: Spooked!', 'Game Boy Color');
replace into games (name, console_name) values ( 'Sabrina the Animated Series: Zapped!', 'Game Boy Color');
replace into games (name, console_name) values ( 'San Francisco Rush 2049', 'Game Boy Color');
replace into games (name, console_name) values ( 'Santa Claus Junior', 'Game Boy Color');
replace into games (name, console_name) values ( 'Scrabble', 'Game Boy Color');
replace into games (name, console_name) values ( 'Scooby Doo! Classic Creep Capers', 'Game Boy Color');
replace into games (name, console_name) values ( 'Sesame Street Sports', 'Game Boy Color');
replace into games (name, console_name) values ( 'Sgt Rock: On the Frontline', 'Game Boy Color');
replace into games (name, console_name) values ( 'Shadowgate Classic', 'Game Boy Color');
replace into games (name, console_name) values ( 'Shamus', 'Game Boy Color');
replace into games (name, console_name) values ( 'Shanghai Pocket', 'Game Boy Color');
replace into games (name, console_name) values ( 'Shantae', 'Game Boy Color');
replace into games (name, console_name) values ( 'Shaun Palmers Pro Snowboarder', 'Game Boy Color');
replace into games (name, console_name) values ( 'Shrek: Fairytale Freakdown', 'Game Boy Color');
replace into games (name, console_name) values ( 'Simpsons, The: Night of the Living Treehouse of Horror', 'Game Boy Color');
replace into games (name, console_name) values ( 'Smurfs Nightmare, The', 'Game Boy Color');
replace into games (name, console_name) values ( 'Snoopy Tennis', 'Game Boy Color');
replace into games (name, console_name) values ( 'Snow White and the Seven Dwarfs', 'Game Boy Color');
replace into games (name, console_name) values ( 'Soccer Manager', 'Game Boy Color');
replace into games (name, console_name) values ( 'Space Invaders', 'Game Boy Color');
replace into games (name, console_name) values ( 'Space Marauder', 'Game Boy Color');
replace into games (name, console_name) values ( 'Space Station Silicon Valley', 'Game Boy Color');
replace into games (name, console_name) values ( 'Spawn', 'Game Boy Color');
replace into games (name, console_name) values ( 'Speedy Gonzales: Aztec Adventure', 'Game Boy Color');
replace into games (name, console_name) values ( 'Spider-Man', 'Game Boy Color');
replace into games (name, console_name) values ( 'Spider-Man 2: The Sinister Six', 'Game Boy Color');
replace into games (name, console_name) values ( 'Spike and Suzy', 'Game Boy Color');
replace into games (name, console_name) values ( 'Spirou: The Robot Invasion', 'Game Boy Color');
replace into games (name, console_name) values ( 'SpongeBob SquarePants: The Legend of the Lost Spatula', 'Game Boy Color');
replace into games (name, console_name) values ( 'Spy vs. Spy', 'Game Boy Color');
replace into games (name, console_name) values ( 'Star Wars Episode I: Obi-Wans Adventures', 'Game Boy Color');
replace into games (name, console_name) values ( 'Star Wars: Episode I Racer', 'Game Boy Color');
replace into games (name, console_name) values ( 'Star Wars: Yoda Stories', 'Game Boy Color');
replace into games (name, console_name) values ( 'Street Fighter Alpha', 'Game Boy Color');
replace into games (name, console_name) values ( 'Stuart Little The Journey Home', 'Game Boy Color');
replace into games (name, console_name) values ( 'Super Breakout', 'Game Boy Color');
replace into games (name, console_name) values ( 'Supercross Freestyle', 'Game Boy Color');
replace into games (name, console_name) values ( 'Suzuki Alstare Extreme Racing', 'Game Boy Color');
replace into games (name, console_name) values ( 'Super Mario Bros. Deluxe', 'Game Boy Color');
replace into games (name, console_name) values ( 'Super Robot Wars – Link Battler', 'Game Boy Color');
replace into games (name, console_name) values ( 'Survival Kids', 'Game Boy Color');
replace into games (name, console_name) values ( 'Survival Kids 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'SWIV', 'Game Boy Color');
replace into games (name, console_name) values ( 'Taxi 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Taxi 3', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tazmanian Devil: Munching Madness', 'Game Boy Color');
replace into games (name, console_name) values ( 'Disneys Tarzan', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tech Deck Skateboarding', 'Game Boy Color');
replace into games (name, console_name) values ( 'Test Drive 6', 'Game Boy Color');
replace into games (name, console_name) values ( 'Test Drive 2001', 'Game Boy Color');
replace into games (name, console_name) values ( 'Test Drive Cycles', 'Game Boy Color');
replace into games (name, console_name) values ( 'Test Drive Le Mans', 'Game Boy Color');
replace into games (name, console_name) values ( 'Test Drive Off-Road 3', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tetris DX', 'Game Boy Color');
replace into games (name, console_name) values ( 'Thomas the Tank Engine & Friends', 'Game Boy Color');
replace into games (name, console_name) values ( 'Three Lions', 'Game Boy Color');
replace into games (name, console_name) values ( 'Thunderbirds', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tiger Woods PGA Tour 2000', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tintin in Tibet', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tiny Toon Adventures: Buster Saves the Day', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tiny Toon Adventures: Dizzys Candy Quest', 'Game Boy Color');
replace into games (name, console_name) values ( 'Titus the Fox', 'Game Boy Color');
replace into games (name, console_name) values ( 'TNN Outdoors Fishing Champ', 'Game Boy Color');
replace into games (name, console_name) values ( 'TOCA; Touring Car Championship', 'Game Boy Color');
replace into games (name, console_name) values ( 'Toki Tori', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tom and Jerry', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tom and Jerry in Mouse Attacks', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tom and Jerry: Mouse Hunt', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tomb Raider', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tomb Raider: Curse of the Sword', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tonic Trouble', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tonka Construction Site', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tonka Raceway', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tony Hawks Pro Skater', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tony Hawks Pro Skater 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tony Hawks Pro Skater 3', 'Game Boy Color');
replace into games (name, console_name) values ( 'Toobin', 'Game Boy Color');
replace into games (name, console_name) values ( 'Toonsylvania', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tootuff', 'Game Boy Color');
replace into games (name, console_name) values ( 'Top Gear Pocket', 'Game Boy Color');
replace into games (name, console_name) values ( 'Top Gear Pocket 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Top Gun: Firestorm', 'Game Boy Color');
replace into games (name, console_name) values ( 'Total Soccer 2000', 'Game Boy Color');
replace into games (name, console_name) values ( 'Towers: Lord Baniffs Deceit', 'Game Boy Color');
replace into games (name, console_name) values ( 'Toy Story 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Toy Story Racer', 'Game Boy Color');
replace into games (name, console_name) values ( 'Trick Boarder', 'Game Boy Color');
replace into games (name, console_name) values ( 'Triple Play 2001', 'Game Boy Color');
replace into games (name, console_name) values ( 'Trouballs', 'Game Boy Color');
replace into games (name, console_name) values ( 'Turok 2: Seeds of Evil', 'Game Boy Color');
replace into games (name, console_name) values ( 'Turok 3: Shadow of Oblivion', 'Game Boy Color');
replace into games (name, console_name) values ( 'Turok: Rage Wars', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tweenies - Doodles Bones', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tweetys High-Flying Adventure', 'Game Boy Color');
replace into games (name, console_name) values ( 'Tyco R/C - Racin Ratz', 'Game Boy Color');
replace into games (name, console_name) values ( 'Ultimate Fighting Championship', 'Game Boy Color');
replace into games (name, console_name) values ( 'Ultimate Paintball', 'Game Boy Color');
replace into games (name, console_name) values ( 'Ultimate Surfing', 'Game Boy Color');
replace into games (name, console_name) values ( 'UNO', 'Game Boy Color');
replace into games (name, console_name) values ( 'Vegas Games', 'Game Boy Color');
replace into games (name, console_name) values ( 'Vigilante 8', 'Game Boy Color');
replace into games (name, console_name) values ( 'VIP', 'Game Boy Color');
replace into games (name, console_name) values ( 'Les Visiteurs', 'Game Boy Color');
replace into games (name, console_name) values ( 'V-Rally', 'Game Boy Color');
replace into games (name, console_name) values ( 'Wacky Races', 'Game Boy Color');
replace into games (name, console_name) values ( 'Walt Disney World Quest: Magical Racing Tour', 'Game Boy Color');
replace into games (name, console_name) values ( 'Wario Land II', 'Game Boy Color');
replace into games (name, console_name) values ( 'Wario Land 3', 'Game Boy Color');
replace into games (name, console_name) values ( 'Warlocked', 'Game Boy Color');
replace into games (name, console_name) values ( 'Warriors of Might and Magic', 'Game Boy Color');
replace into games (name, console_name) values ( 'WCW Mayhem', 'Game Boy Color');
replace into games (name, console_name) values ( 'Wendy: Every Witch Way', 'Game Boy Color');
replace into games (name, console_name) values ( 'Wetrix GB', 'Game Boy Color');
replace into games (name, console_name) values ( 'Who Wants To Be A Millionaire: 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Wild Thornberrys Rambler', 'Game Boy Color');
replace into games (name, console_name) values ( 'Wings of Fury', 'Game Boy Color');
replace into games (name, console_name) values ( 'Winnie the Pooh: Adventures in the 100 Acre Wood', 'Game Boy Color');
replace into games (name, console_name) values ( 'Woody Woodpecker', 'Game Boy Color');
replace into games (name, console_name) values ( 'Woody Woodpecker Racing', 'Game Boy Color');
replace into games (name, console_name) values ( 'World Destruction League: Thunder Tanks', 'Game Boy Color');
replace into games (name, console_name) values ( 'The World Is Not Enough', 'Game Boy Color');
replace into games (name, console_name) values ( 'Worms: Armageddon', 'Game Boy Color');
replace into games (name, console_name) values ( 'WWF Attitude', 'Game Boy Color');
replace into games (name, console_name) values ( 'WWF Betrayal', 'Game Boy Color');
replace into games (name, console_name) values ( 'WWF WrestleMania 2000', 'Game Boy Color');
replace into games (name, console_name) values ( 'X-Men: Mutant Academy', 'Game Boy Color');
replace into games (name, console_name) values ( 'X-Men: Mutant Wars', 'Game Boy Color');
replace into games (name, console_name) values ( 'X-Men: Wolverines Rage', 'Game Boy Color');
replace into games (name, console_name) values ( 'Xtreme Sports', 'Game Boy Color');
replace into games (name, console_name) values ( 'Xtreme Wheels', 'Game Boy Color');
replace into games (name, console_name) values ( 'Xena: Warrior Princess', 'Game Boy Color');
replace into games (name, console_name) values ( 'Yars Revenge', 'Game Boy Color');
replace into games (name, console_name) values ( 'Yogi Bear: Great Balloon Blast', 'Game Boy Color');
replace into games (name, console_name) values ( 'Yu-Gi-Oh! Duel Monsters II: Dark Duel Stories', 'Game Boy Color');
replace into games (name, console_name) values ( 'Yu-Gi-Oh! Duel Monsters III: Tri-Holy God Advent', 'Game Boy Color');
replace into games (name, console_name) values ( 'Yu-Gi-Oh! Duel Monsters III: Tri-Holygod Advent', 'Game Boy Color');
replace into games (name, console_name) values ( 'Yu-Gi-Oh! Duel Monsters 4: Battle of the Powerful Duelists', 'Game Boy Color');
replace into games (name, console_name) values ( 'Yu-Gi-Oh! Monster Capsule GB', 'Game Boy Color');
replace into games (name, console_name) values ( 'Zebco Fishing!', 'Game Boy Color');
replace into games (name, console_name) values ( 'Zidane Football Generation', 'Game Boy Color');
replace into games (name, console_name) values ( 'Zoboomafoo: Playtime in Zobooland', 'Game Boy Color');
replace into games (name, console_name) values ( 'Zoids: Jashin Fukkatsu! Genobreaker Hen', 'Game Boy Color');
replace into games (name, console_name) values ( 'Zoids: Shirogane no Jukishin Liger Zero', 'Game Boy Color');
replace into games (name, console_name) values ( 'ATV Racing', 'Game Boy Color');
replace into games (name, console_name) values ( 'Digimon 02 4', 'Game Boy Color');
replace into games (name, console_name) values ( 'Digimon 02 5', 'Game Boy Color');
replace into games (name, console_name) values ( 'Digimon 02 Crystal II ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Digimon 02 Emerald / Jade ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Digimon 2 ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Digimon 3 Crystal ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Digimon 3 Crystal ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Digimon Crystal Version II', 'Game Boy Color');
replace into games (name, console_name) values ( 'Digimon Diamond ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Digimon D-3: Ultra Evolution', 'Game Boy Color');
replace into games (name, console_name) values ( 'Digimon Pocket (Vast Fame)', 'Game Boy Color');
replace into games (name, console_name) values ( 'Digimon Pocket (Yong Yong)', 'Game Boy Color');
replace into games (name, console_name) values ( 'Donkey Kong 5: The Journey of Over Time and Space ', 'Game Boy Color');
replace into games (name, console_name) values ( 'EFighter HOT ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Harry Potter', 'Game Boy Color');
replace into games (name, console_name) values ( 'Harry Potter 3', 'Game Boy Color');
replace into games (name, console_name) values ( 'Ice Age ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Ice Age 2 ', 'Game Boy Color');
replace into games (name, console_name) values ( 'The Incredibles ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Jurassic Boy 2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Karate Joe', 'Game Boy Color');
replace into games (name, console_name) values ( 'King of Fighters R-2', 'Game Boy Color');
replace into games (name, console_name) values ( 'Lord of the Rings: The Fellowship of the Ring ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Metal Slug 2001 ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Painter ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pocket Smash Out / Race Time', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pokémon Adventure ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pokémon Diamond ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pokémon Diamond: Special Pikachu Version', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pokémon Green ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pokémon Hong Kong Gold', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pokémon Jade', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pokémon Jade: Special Pikachu Version ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pokémon: Mewtwo Strikes Back', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pokémon Pearl ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pokémon Ruby ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pokémon Sapphire', 'Game Boy Color');
replace into games (name, console_name) values ( 'Pokémon Vietnamese Crystal ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Queen of Fighting 2000', 'Game Boy Color');
replace into games (name, console_name) values ( 'Rockman X4', 'Game Boy Color');
replace into games (name, console_name) values ( 'Sonic Adventure 7 ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Sonic Adventure 8 ', 'Game Boy Color');
replace into games (name, console_name) values ( 'Space Invasion', 'Game Boy Color');
replace into games (name, console_name) values ( 'Super Mario Special 3 ', 'Game Boy Color');
