replace into games (name, console_name) values ('4-in-1 Fun Pak', 'Game Boy');
replace into games (name, console_name) values ('4-in-1 Funpak: Volume II', 'Game Boy');
replace into games (name, console_name) values ('Absolute Entertainment NA', 'Game Boy');
replace into games (name, console_name) values ('Acclaim NA/EU', 'Game Boy');
replace into games (name, console_name) values ('Acclaim NA', 'Game Boy');
replace into games (name, console_name) values ('Accolade NA', 'Game Boy');
replace into games (name, console_name) values ('Activision NA/EU', 'Game Boy');
replace into games (name, console_name) values ('Activision NA', 'Game Boy');
replace into games (name, console_name) values ('ActivisionEU', 'Game Boy');
replace into games (name, console_name) values ('Addams Family, The', 'Game Boy');
replace into games (name, console_name) values ('Addams Family: Pugsleys Scavenger Hunt, The', 'Game Boy');
replace into games (name, console_name) values ('Adventure Island II EU', 'Game Boy');
replace into games (name, console_name) values ('Adventure Island II: Aliens in Paradise', 'Game Boy');
replace into games (name, console_name) values ('Adventure Island', 'Game Boy');
replace into games (name, console_name) values ('Adventures of Rocky and Bullwinkle and Friends, The', 'Game Boy');
replace into games (name, console_name) values ('Adventures of Star Saver, The', 'Game Boy');
replace into games (name, console_name) values ('Aerostar', 'Game Boy');
replace into games (name, console_name) values ('AgroSoar AU', 'Game Boy');
replace into games (name, console_name) values ('Alfred Chicken', 'Game Boy');
replace into games (name, console_name) values ('Alien vs Predator: The Last of His Clan', 'Game Boy');
replace into games (name, console_name) values ('Alien³	Bits Studios', 'Game Boy');
replace into games (name, console_name) values ('All-Star Baseball 99', 'Game Boy');
replace into games (name, console_name) values ('Alleyway', 'Game Boy');
replace into games (name, console_name) values ('Altered Space: A 3-D Alien Adventure', 'Game Boy');
replace into games (name, console_name) values ('Amazing Penguin', 'Game Boy');
replace into games (name, console_name) values ('Amazing Spider-Man 2, The', 'Game Boy');
replace into games (name, console_name) values ('Amazing Spider-Man, The', 'Game Boy');
replace into games (name, console_name) values ('Amazing Tater', 'Game Boy');
replace into games (name, console_name) values ('American Sammy NA', 'Game Boy');
replace into games (name, console_name) values ('American Sammy', 'Game Boy');
replace into games (name, console_name) values ('Animaniacs', 'Game Boy');
replace into games (name, console_name) values ('Arcade Classic No. 1: Asteroids / Missile Command', 'Game Boy');
replace into games (name, console_name) values ('Arcade Classic No. 2: Centipede / Millipede', 'Game Boy');
replace into games (name, console_name) values ('Arcade Classic No. 3: Galaga / Galaxian', 'Game Boy');
replace into games (name, console_name) values ('Arcade Classic No. 4: Defender / Joust', 'Game Boy');
replace into games (name, console_name) values ('Arcade Classics: Super Breakout / Battlezone', 'Game Boy');
replace into games (name, console_name) values ('Asmik Ace Entertainment NA', 'Game Boy');
replace into games (name, console_name) values ('Asmik Corporation of America NA', 'Game Boy');
replace into games (name, console_name) values ('Asteroids', 'Game Boy');
replace into games (name, console_name) values ('Atari EU', 'Game Boy');
replace into games (name, console_name) values ('Atomic Punk', 'Game Boy');
replace into games (name, console_name) values ('Attack of the Killer Tomatoes', 'Game Boy');
replace into games (name, console_name) values ('Avenging Spirit', 'Game Boy');
replace into games (name, console_name) values ('B.C. Kid 2 EU', 'Game Boy');
replace into games (name, console_name) values ('B.C. Kid EU', 'Game Boy');
replace into games (name, console_name) values ('Baby T-Rex EU', 'Game Boy');
replace into games (name, console_name) values ('Balloon Kid', 'Game Boy');
replace into games (name, console_name) values ('Bamse SE', 'Game Boy');
replace into games (name, console_name) values ('Bandai EU', 'Game Boy');
replace into games (name, console_name) values ('Bandai NA', 'Game Boy');
replace into games (name, console_name) values ('Barbie: Game Girl', 'Game Boy');
replace into games (name, console_name) values ('Bart Simpsons Escape from Camp Deadly', 'Game Boy');
replace into games (name, console_name) values ('Baseball', 'Game Boy');
replace into games (name, console_name) values ('Bases Loaded', 'Game Boy');
replace into games (name, console_name) values ('Batman Forever', 'Game Boy');
replace into games (name, console_name) values ('Batman: Return of the Joker', 'Game Boy');
replace into games (name, console_name) values ('Batman: The Animated Series', 'Game Boy');
replace into games (name, console_name) values ('Batman: The Video Game', 'Game Boy');
replace into games (name, console_name) values ('Battle Arena Toshinden', 'Game Boy');
replace into games (name, console_name) values ('Battle Bull', 'Game Boy');
replace into games (name, console_name) values ('Battle Unit Zeoth', 'Game Boy');
replace into games (name, console_name) values ('Battleship', 'Game Boy');
replace into games (name, console_name) values ('Battletoads & Double Dragon: The Ultimate Team', 'Game Boy');
replace into games (name, console_name) values ('Battletoads in Ragnaroks World', 'Game Boy');
replace into games (name, console_name) values ('Battletoads', 'Game Boy');
replace into games (name, console_name) values ('Beavis and Butt-head', 'Game Boy');
replace into games (name, console_name) values ('Beethoven: The Ultimate Canine Caper', 'Game Boy');
replace into games (name, console_name) values ('Beetlejuice', 'Game Boy');
replace into games (name, console_name) values ('Berlitz French Translator', 'Game Boy');
replace into games (name, console_name) values ('Berlitz Spanish Translator', 'Game Boy');
replace into games (name, console_name) values ('Best of the Best: Championship Karate', 'Game Boy');
replace into games (name, console_name) values ('Bill & Teds Excellent Game Boy Adventure: A Bogus Journey!	Beam Software', 'Game Boy');
replace into games (name, console_name) values ('Bill Elliotts NASCAR Fast Tracks', 'Game Boy');
replace into games (name, console_name) values ('Bionic Battler', 'Game Boy');
replace into games (name, console_name) values ('Bionic Commando', 'Game Boy');
replace into games (name, console_name) values ('Black Bass: Lure Fishing', 'Game Boy');
replace into games (name, console_name) values ('Blades of Steel', 'Game Boy');
replace into games (name, console_name) values ('Blaster Master Boy', 'Game Boy');
replace into games (name, console_name) values ('Blaster Master Jr. EU', 'Game Boy');
replace into games (name, console_name) values ('Blues Brothers, The', 'Game Boy');
replace into games (name, console_name) values ('Blues Brothers: Jukebox Adventure, The', 'Game Boy');
replace into games (name, console_name) values ('Bo Jackson: Two Games In One', 'Game Boy');
replace into games (name, console_name) values ('Boggle Plus', 'Game Boy');
replace into games (name, console_name) values ('Bomberman GB', 'Game Boy');
replace into games (name, console_name) values ('Bonks Adventure', 'Game Boy');
replace into games (name, console_name) values ('Bonks Revenge', 'Game Boy');
replace into games (name, console_name) values ('Boomers Adventure in ASMIK World', 'Game Boy');
replace into games (name, console_name) values ('Boxxle II', 'Game Boy');
replace into games (name, console_name) values ('Boxxle', 'Game Boy');
replace into games (name, console_name) values ('Brain Drain', 'Game Boy');
replace into games (name, console_name) values ('Brainbender', 'Game Boy');
replace into games (name, console_name) values ('Bram Stokers Dracula', 'Game Boy');
replace into games (name, console_name) values ('BreakThru!	Realtime Associates', 'Game Boy');
replace into games (name, console_name) values ('Bubble Bobble Part 2', 'Game Boy');
replace into games (name, console_name) values ('Bubble Bobble', 'Game Boy');
replace into games (name, console_name) values ('Bubble Ghost', 'Game Boy');
replace into games (name, console_name) values ('Bubsy II', 'Game Boy');
replace into games (name, console_name) values ('Bugs Bunny Crazy Castle 2, The', 'Game Boy');
replace into games (name, console_name) values ('Bugs Bunny Crazy Castle, The', 'Game Boy');
replace into games (name, console_name) values ('Burai Fighter Deluxe', 'Game Boy');
replace into games (name, console_name) values ('BurgerTime Deluxe', 'Game Boy');
replace into games (name, console_name) values ('Bust-A-Move 2: Arcade Edition', 'Game Boy');
replace into games (name, console_name) values ('Buster Brothers', 'Game Boy');
replace into games (name, console_name) values ('Caesars Palace', 'Game Boy');
replace into games (name, console_name) values ('Capcom NA/EU', 'Game Boy');
replace into games (name, console_name) values ('Capcom NA', 'Game Boy');
replace into games (name, console_name) values ('Captain America and The Avengers', 'Game Boy');
replace into games (name, console_name) values ('Casino FunPak', 'Game Boy');
replace into games (name, console_name) values ('Casper', 'Game Boy');
replace into games (name, console_name) values ('Castelian', 'Game Boy');
replace into games (name, console_name) values ('Castlevania II: Belmonts Revenge', 'Game Boy');
replace into games (name, console_name) values ('Castlevania Legends', 'Game Boy');
replace into games (name, console_name) values ('Castlevania: The Adventure', 'Game Boy');
replace into games (name, console_name) values ('Catrap', 'Game Boy');
replace into games (name, console_name) values ('Centipede', 'Game Boy');
replace into games (name, console_name) values ('Championship Pool', 'Game Boy');
replace into games (name, console_name) values ('Chase H.Q.', 'Game Boy');
replace into games (name, console_name) values ('Chessmaster, The', 'Game Boy');
replace into games (name, console_name) values ('Choplifter II', 'Game Boy');
replace into games (name, console_name) values ('Chuck Rock', 'Game Boy');
replace into games (name, console_name) values ('Cliffhanger', 'Game Boy');
replace into games (name, console_name) values ('College Slam', 'Game Boy');
replace into games (name, console_name) values ('Contra: The Alien Wars', 'Game Boy');
replace into games (name, console_name) values ('Cool Ball', 'Game Boy');
replace into games (name, console_name) values ('Cool Spot', 'Game Boy');
replace into games (name, console_name) values ('Cool World', 'Game Boy');
replace into games (name, console_name) values ('Cosmo Tank', 'Game Boy');
replace into games (name, console_name) values ('Crystal Quest', 'Game Boy');
replace into games (name, console_name) values ('Cutthroat Island', 'Game Boy');
replace into games (name, console_name) values ('Cyraid', 'Game Boy');
replace into games (name, console_name) values ('DTMC NA', 'Game Boy');
replace into games (name, console_name) values ('Daedalian Opus', 'Game Boy');
replace into games (name, console_name) values ('Daffy Duck: The Marvin Missions', 'Game Boy');
replace into games (name, console_name) values ('Darkman', 'Game Boy');
replace into games (name, console_name) values ('Data East NA/EU', 'Game Boy');
replace into games (name, console_name) values ('David Cranes The Rescue of Princess Blobette', 'Game Boy');
replace into games (name, console_name) values ('Days of Thunder', 'Game Boy');
replace into games (name, console_name) values ('Dead Heat Scramble', 'Game Boy');
replace into games (name, console_name) values ('Dennis EU', 'Game Boy');
replace into games (name, console_name) values ('Dennis the Menace', 'Game Boy');
replace into games (name, console_name) values ('Desert Strike: Return to the Gulf', 'Game Boy');
replace into games (name, console_name) values ('Dexterity', 'Game Boy');
replace into games (name, console_name) values ('Dick Tracy', 'Game Boy');
replace into games (name, console_name) values ('Dig Dug', 'Game Boy');
replace into games (name, console_name) values ('Disneys Aladdin', 'Game Boy');
replace into games (name, console_name) values ('Disneys Darkwing Duck', 'Game Boy');
replace into games (name, console_name) values ('Disneys DuckTales 2', 'Game Boy');
replace into games (name, console_name) values ('Disneys DuckTales', 'Game Boy');
replace into games (name, console_name) values ('Disneys Hercules', 'Game Boy');
replace into games (name, console_name) values ('Disneys Mulan', 'Game Boy');
replace into games (name, console_name) values ('Disneys Pinocchio', 'Game Boy');
replace into games (name, console_name) values ('Disneys Pocahontas', 'Game Boy');
replace into games (name, console_name) values ('Disneys TaleSpin', 'Game Boy');
replace into games (name, console_name) values ('Disneys The Hunchback of Notre Dame', 'Game Boy');
replace into games (name, console_name) values ('Disneys The Jungle Book', 'Game Boy');
replace into games (name, console_name) values ('Disneys The Little Mermaid', 'Game Boy');
replace into games (name, console_name) values ('Disneys Toy Story', 'Game Boy');
replace into games (name, console_name) values ('Donkey Kong Land 2', 'Game Boy');
replace into games (name, console_name) values ('Donkey Kong Land III', 'Game Boy');
replace into games (name, console_name) values ('Donkey Kong Land', 'Game Boy');
replace into games (name, console_name) values ('Donkey Kong', 'Game Boy');
replace into games (name, console_name) values ('Double Dragon 3: The Arcade Game', 'Game Boy');
replace into games (name, console_name) values ('Double Dragon II', 'Game Boy');
replace into games (name, console_name) values ('Double Dragon', 'Game Boy');
replace into games (name, console_name) values ('Double Dribble: 5 on 5', 'Game Boy');
replace into games (name, console_name) values ('Dr. Franken II', 'Game Boy');
replace into games (name, console_name) values ('Dr. Franken', 'Game Boy');
replace into games (name, console_name) values ('Dr. Mario', 'Game Boy');
replace into games (name, console_name) values ('Dragons Lair: The Legend', 'Game Boy');
replace into games (name, console_name) values ('DragonHeart', 'Game Boy');
replace into games (name, console_name) values ('Dynablaster EU', 'Game Boy');
replace into games (name, console_name) values ('Earthworm Jim', 'Game Boy');
replace into games (name, console_name) values ('Electro Brain NA/EU', 'Game Boy');
replace into games (name, console_name) values ('Electro Brain NA', 'Game Boy');
replace into games (name, console_name) values ('Elevator Action', 'Game Boy');
replace into games (name, console_name) values ('Elite Soccer', 'Game Boy');
replace into games (name, console_name) values ('Elite Systems EU', 'Game Boy');
replace into games (name, console_name) values ('Empire Interactive EU', 'Game Boy');
replace into games (name, console_name) values ('Extra Bases', 'Game Boy');
replace into games (name, console_name) values ('F-1 Race', 'Game Boy');
replace into games (name, console_name) values ('F-15 Strike Eagle', 'Game Boy');
replace into games (name, console_name) values ('F1 Pole Position', 'Game Boy');
replace into games (name, console_name) values ('FCI NA/EU', 'Game Boy');
replace into games (name, console_name) values ('FCI NA', 'Game Boy');
replace into games (name, console_name) values ('FCI', 'Game Boy');
replace into games (name, console_name) values ('FIFA 97 EU', 'Game Boy');
replace into games (name, console_name) values ('FIFA International Soccer', 'Game Boy');
replace into games (name, console_name) values ('FIFA Soccer 96', 'Game Boy');
replace into games (name, console_name) values ('FIFA Soccer 97', 'Game Boy');
replace into games (name, console_name) values ('FIFA: Road to World Cup 98', 'Game Boy');
replace into games (name, console_name) values ('Faceball 2000', 'Game Boy');
replace into games (name, console_name) values ('Fastest Lap', 'Game Boy');
replace into games (name, console_name) values ('Felix the Cat', 'Game Boy');
replace into games (name, console_name) values ('Ferrari Grand Prix Challenge', 'Game Boy');
replace into games (name, console_name) values ('Fidgetts, The', 'Game Boy');
replace into games (name, console_name) values ('Fighting Simulator: 2-in-1 Flying Warriors', 'Game Boy');
replace into games (name, console_name) values ('Final Fantasy Adventure', 'Game Boy');
replace into games (name, console_name) values ('Final Fantasy Legend III', 'Game Boy');
replace into games (name, console_name) values ('Final Fantasy Legend II', 'Game Boy');
replace into games (name, console_name) values ('Final Fantasy Legend, The', 'Game Boy');
replace into games (name, console_name) values ('Fish Dude', 'Game Boy');
replace into games (name, console_name) values ('Fist of the North Star: 10 Big Brawls for the King of Universe', 'Game Boy');
replace into games (name, console_name) values ('Flash, The', 'Game Boy');
replace into games (name, console_name) values ('Flintstones, The', 'Game Boy');
replace into games (name, console_name) values ('Flintstones: King Rock Treasure Island, The', 'Game Boy');
replace into games (name, console_name) values ('Flipull: An Exciting Cube Game', 'Game Boy');
replace into games (name, console_name) values ('Foreman for Real', 'Game Boy');
replace into games (name, console_name) values ('Fortified Zone', 'Game Boy');
replace into games (name, console_name) values ('Frank Thomas Big Hurt Baseball', 'Game Boy');
replace into games (name, console_name) values ('Frogger', 'Game Boy');
replace into games (name, console_name) values ('Game & Watch Gallery', 'Game Boy');
replace into games (name, console_name) values ('Game of Harmony, The', 'Game Boy');
replace into games (name, console_name) values ('GameTek EU', 'Game Boy');
replace into games (name, console_name) values ('GameTek NA/EU', 'Game Boy');
replace into games (name, console_name) values ('GameTek NA', 'Game Boy');
replace into games (name, console_name) values ('Garfield Labyrinth EU', 'Game Boy');
replace into games (name, console_name) values ('Gargoyles Quest: Ghosts n Goblins', 'Game Boy');
replace into games (name, console_name) values ('Gauntlet II', 'Game Boy');
replace into games (name, console_name) values ('Gear Works', 'Game Boy');
replace into games (name, console_name) values ('George Foremans KO Boxing', 'Game Boy');
replace into games (name, console_name) values ('Getaway: High Speed II, The', 'Game Boy');
replace into games (name, console_name) values ('Ghostbusters II', 'Game Boy');
replace into games (name, console_name) values ('Glücksrad DE', 'Game Boy');
replace into games (name, console_name) values ('Go! Go! Tank', 'Game Boy');
replace into games (name, console_name) values ('Goal!', 'Game Boy');
replace into games (name, console_name) values ('Godzilla', 'Game Boy');
replace into games (name, console_name) values ('Golf', 'Game Boy');
replace into games (name, console_name) values ('Gradius: The Interstellar Assault', 'Game Boy');
replace into games (name, console_name) values ('Great Greed', 'Game Boy');
replace into games (name, console_name) values ('Gremlin Graphics EU', 'Game Boy');
replace into games (name, console_name) values ('Gremlin GraphicsEU', 'Game Boy');
replace into games (name, console_name) values ('Gremlins 2: The New Batch', 'Game Boy');
replace into games (name, console_name) values ('HAL Laboratory NA', 'Game Boy');
replace into games (name, console_name) values ('HAL Wrestling', 'Game Boy');
replace into games (name, console_name) values ('Harvest Moon GB', 'Game Boy');
replace into games (name, console_name) values ('Hatris', 'Game Boy');
replace into games (name, console_name) values ('Heavyweight Championship Boxing', 'Game Boy');
replace into games (name, console_name) values ('Heiankyo Alien', 'Game Boy');
replace into games (name, console_name) values ('Hi Tech Expressions EU', 'Game Boy');
replace into games (name, console_name) values ('High Stakes Gambling', 'Game Boy');
replace into games (name, console_name) values ('Hit the Ice', 'Game Boy');
replace into games (name, console_name) values ('Home Alone 2: Lost in New York', 'Game Boy');
replace into games (name, console_name) values ('Home Alone', 'Game Boy');
replace into games (name, console_name) values ('Hook', 'Game Boy');
replace into games (name, console_name) values ('Hot B NA', 'Game Boy');
replace into games (name, console_name) values ('Hudson Hawk', 'Game Boy');
replace into games (name, console_name) values ('Hugo EU', 'Game Boy');
replace into games (name, console_name) values ('Humans, The', 'Game Boy');
replace into games (name, console_name) values ('Hunt for Red October, The', 'Game Boy');
replace into games (name, console_name) values ('Hyper Lode Runner: The Labyrinth of Doom', 'Game Boy');
replace into games (name, console_name) values ('HyperDunk EU', 'Game Boy');
replace into games (name, console_name) values ('In Your Face', 'Game Boy');
replace into games (name, console_name) values ('Incredible Crash Dummies, The', 'Game Boy');
replace into games (name, console_name) values ('Indiana Jones and the Last Crusade', 'Game Boy');
replace into games (name, console_name) values ('InfoGenius Productivity Pak: Frommers Travel Guide', 'Game Boy');
replace into games (name, console_name) values ('InfoGenius Productivity Pak: Personal Organizer and Phone Book', 'Game Boy');
replace into games (name, console_name) values ('InfoGenius Productivity Pak: Spell Checker and Calculator', 'Game Boy');
replace into games (name, console_name) values ('International Superstar Soccer', 'Game Boy');
replace into games (name, console_name) values ('Iron Man and X-O Manowar in Heavy Metal', 'Game Boy');
replace into games (name, console_name) values ('Ishido: The Way of Stones', 'Game Boy');
replace into games (name, console_name) values ('JVC Musical Industries NA/EU', 'Game Boy');
replace into games (name, console_name) values ('Jack Nicklaus Golf', 'Game Boy');
replace into games (name, console_name) values ('Jaleco NA', 'Game Boy');
replace into games (name, console_name) values ('James Bond 007', 'Game Boy');
replace into games (name, console_name) values ('Jeep Jamboree: Off Road Adventure', 'Game Boy');
replace into games (name, console_name) values ('Jeopardy!	Data Design Interactive', 'Game Boy');
replace into games (name, console_name) values ('Jeopardy! Platinum Edition', 'Game Boy');
replace into games (name, console_name) values ('Jeopardy! Sports Edition', 'Game Boy');
replace into games (name, console_name) values ('Jeopardy! Teen Tournament', 'Game Boy');
replace into games (name, console_name) values ('Jetsons: Robot Panic, The', 'Game Boy');
replace into games (name, console_name) values ('Jimmy Connors Tennis', 'Game Boy');
replace into games (name, console_name) values ('Joe & Mac: Caveman Ninja EU', 'Game Boy');
replace into games (name, console_name) values ('Joe & Mac', 'Game Boy');
replace into games (name, console_name) values ('Jordan vs. Bird: One on One', 'Game Boy');
replace into games (name, console_name) values ('Judge Dredd', 'Game Boy');
replace into games (name, console_name) values ('Jungle Strike', 'Game Boy');
replace into games (name, console_name) values ('Jurassic Park Part 2: The Chaos Continues', 'Game Boy');
replace into games (name, console_name) values ('Jurassic Park', 'Game Boy');
replace into games (name, console_name) values ('Ken Griffey, Jr. Presents Major League Baseball', 'Game Boy');
replace into games (name, console_name) values ('Kid Dracula', 'Game Boy');
replace into games (name, console_name) values ('Kid Icarus: Of Myths and Monsters', 'Game Boy');
replace into games (name, console_name) values ('Killer Instinct', 'Game Boy');
replace into games (name, console_name) values ('King of Fighters 95, The', 'Game Boy');
replace into games (name, console_name) values ('King of the Zoo EU', 'Game Boy');
replace into games (name, console_name) values ('Kingdom Crusade', 'Game Boy');
replace into games (name, console_name) values ('Kirbys Block Ball', 'Game Boy');
replace into games (name, console_name) values ('Kirbys Dream Land 2', 'Game Boy');
replace into games (name, console_name) values ('Kirbys Dream Land', 'Game Boy');
replace into games (name, console_name) values ('Kirbys Pinball Land', 'Game Boy');
replace into games (name, console_name) values ('Kirbys Star Stacker', 'Game Boy');
replace into games (name, console_name) values ('Klax', 'Game Boy');
replace into games (name, console_name) values ('Knight Quest', 'Game Boy');
replace into games (name, console_name) values ('Konami EU', 'Game Boy');
replace into games (name, console_name) values ('Konami Golf EU', 'Game Boy');
replace into games (name, console_name) values ('Krustys Fun House', 'Game Boy');
replace into games (name, console_name) values ('Kung-Fu Master', 'Game Boy');
replace into games (name, console_name) values ('Kwirk', 'Game Boy');
replace into games (name, console_name) values ('Laguna EU', 'Game Boy');
replace into games (name, console_name) values ('Lamborghini American Challenge', 'Game Boy');
replace into games (name, console_name) values ('Laser Beam Entertainment AU/EU', 'Game Boy');
replace into games (name, console_name) values ('Last Action Hero', 'Game Boy');
replace into games (name, console_name) values ('Lazlos Leap', 'Game Boy');
replace into games (name, console_name) values ('Legend of Zelda: Links Awakening, The', 'Game Boy');
replace into games (name, console_name) values ('Legend of the River King GB', 'Game Boy');
replace into games (name, console_name) values ('Lemmings', 'Game Boy');
replace into games (name, console_name) values ('Lethal Weapon', 'Game Boy');
replace into games (name, console_name) values ('Lion King, The', 'Game Boy');
replace into games (name, console_name) values ('Littis Summer Sports DE', 'Game Boy');
replace into games (name, console_name) values ('Lock n Chase', 'Game Boy');
replace into games (name, console_name) values ('Looney Tunes 2: Tazmanian Devil in Island Chase EU', 'Game Boy');
replace into games (name, console_name) values ('Looney Tunes', 'Game Boy');
replace into games (name, console_name) values ('Loop', 'Game Boy');
replace into games (name, console_name) values ('Loriciels EU', 'Game Boy');
replace into games (name, console_name) values ('Lost World: Jurassic Park, The', 'Game Boy');
replace into games (name, console_name) values ('Madden 95', 'Game Boy');
replace into games (name, console_name) values ('Madden 96', 'Game Boy');
replace into games (name, console_name) values ('Madden 97', 'Game Boy');
replace into games (name, console_name) values ('Malibu Beach Volleyball', 'Game Boy');
replace into games (name, console_name) values ('Marble Madness', 'Game Boy');
replace into games (name, console_name) values ('Mario & Yoshi EU', 'Game Boy');
replace into games (name, console_name) values ('Marios Picross', 'Game Boy');
replace into games (name, console_name) values ('Marus Mission', 'Game Boy');
replace into games (name, console_name) values ('Maui Mallard in Cold Shadow', 'Game Boy');
replace into games (name, console_name) values ('McDonaldland EU', 'Game Boy');
replace into games (name, console_name) values ('Mega Man III', 'Game Boy');
replace into games (name, console_name) values ('Mega Man II', 'Game Boy');
replace into games (name, console_name) values ('Mega Man IV', 'Game Boy');
replace into games (name, console_name) values ('Mega Man V', 'Game Boy');
replace into games (name, console_name) values ('Mega Man: Dr. Wilys Revenge', 'Game Boy');
replace into games (name, console_name) values ('Megalit', 'Game Boy');
replace into games (name, console_name) values ('Mercenary Force', 'Game Boy');
replace into games (name, console_name) values ('Metal Masters', 'Game Boy');
replace into games (name, console_name) values ('Metroid II: Return of Samus', 'Game Boy');
replace into games (name, console_name) values ('Mickey Mouse EU', 'Game Boy');
replace into games (name, console_name) values ('Mickey Mouse: Magic Wands!', 'Game Boy');
replace into games (name, console_name) values ('Mickeys Dangerous Chase', 'Game Boy');
replace into games (name, console_name) values ('Mickeys Ultimate Challenge', 'Game Boy');
replace into games (name, console_name) values ('Micro Machines', 'Game Boy');
replace into games (name, console_name) values ('Mighty Morphin Power Rangers: The Movie', 'Game Boy');
replace into games (name, console_name) values ('Mighty Morphin Power Rangers', 'Game Boy');
replace into games (name, console_name) values ('Milons Secret Castle', 'Game Boy');
replace into games (name, console_name) values ('Mindscape EU', 'Game Boy');
replace into games (name, console_name) values ('Mindscape NA/EU', 'Game Boy');
replace into games (name, console_name) values ('Miner 2049er', 'Game Boy');
replace into games (name, console_name) values ('Missile Command', 'Game Boy');
replace into games (name, console_name) values ('Mole Mania', 'Game Boy');
replace into games (name, console_name) values ('Monopoly', 'Game Boy');
replace into games (name, console_name) values ('Monster Max', 'Game Boy');
replace into games (name, console_name) values ('Monster Truck Wars', 'Game Boy');
replace into games (name, console_name) values ('Mortal Kombat & Mortal Kombat II', 'Game Boy');
replace into games (name, console_name) values ('Mortal Kombat 3', 'Game Boy');
replace into games (name, console_name) values ('Mortal Kombat I & II EU', 'Game Boy');
replace into games (name, console_name) values ('Mortal Kombat II', 'Game Boy');
replace into games (name, console_name) values ('Mortal Kombat', 'Game Boy');
replace into games (name, console_name) values ('Motocross Maniacs', 'Game Boy');
replace into games (name, console_name) values ('Mouse Trap Hotel', 'Game Boy');
replace into games (name, console_name) values ('Mr. Chins Gourmet Paradise', 'Game Boy');
replace into games (name, console_name) values ('Mr. Do!	Ocean', 'Game Boy');
replace into games (name, console_name) values ('Ms. Pac-Man', 'Game Boy');
replace into games (name, console_name) values ('Muhammad Ali Heavyweight Boxing', 'Game Boy');
replace into games (name, console_name) values ('Mysterium', 'Game Boy');
replace into games (name, console_name) values ('Mystic Quest EU', 'Game Boy');
replace into games (name, console_name) values ('Mystical Ninja Starring Goemon', 'Game Boy');
replace into games (name, console_name) values ('NBA All-Star Challenge 2', 'Game Boy');
replace into games (name, console_name) values ('NBA All-Star Challenge', 'Game Boy');
replace into games (name, console_name) values ('NBA Jam: Tournament Edition', 'Game Boy');
replace into games (name, console_name) values ('NBA Jam', 'Game Boy');
replace into games (name, console_name) values ('NBA Live 96', 'Game Boy');
replace into games (name, console_name) values ('NFL Football', 'Game Boy');
replace into games (name, console_name) values ('NFL Quarterback Club 96', 'Game Boy');
replace into games (name, console_name) values ('NFL Quarterback Club II', 'Game Boy');
replace into games (name, console_name) values ('NFL Quarterback Club', 'Game Boy');
replace into games (name, console_name) values ('NHL 96', 'Game Boy');
replace into games (name, console_name) values ('NHL Hockey 95', 'Game Boy');
replace into games (name, console_name) values ('NTVIC NA', 'Game Boy');
replace into games (name, console_name) values ('Nail n Scale', 'Game Boy');
replace into games (name, console_name) values ('Natsume NA', 'Game Boy');
replace into games (name, console_name) values ('Navy SEALs', 'Game Boy');
replace into games (name, console_name) values ('Nemesis II: The Return of the Hero EU', 'Game Boy');
replace into games (name, console_name) values ('Nemesis', 'Game Boy');
replace into games (name, console_name) values ('New Chessmaster, The', 'Game Boy');
replace into games (name, console_name) values ('Nexoft NA', 'Game Boy');
replace into games (name, console_name) values ('Nigel Mansells World Championship Racing', 'Game Boy');
replace into games (name, console_name) values ('Ninja Boy 2', 'Game Boy');
replace into games (name, console_name) values ('Ninja Boy', 'Game Boy');
replace into games (name, console_name) values ('Ninja Gaiden Shadow', 'Game Boy');
replace into games (name, console_name) values ('Ninja Taro', 'Game Boy');
replace into games (name, console_name) values ('Nintendo EU', 'Game Boy');
replace into games (name, console_name) values ('Nintendo NA/EU', 'Game Boy');
replace into games (name, console_name) values ('Nintendo NA', 'Game Boy');
replace into games (name, console_name) values ('Nintendo World Cup', 'Game Boy');
replace into games (name, console_name) values ('Nobunagas Ambition', 'Game Boy');
replace into games (name, console_name) values ('Ocean EU', 'Game Boy');
replace into games (name, console_name) values ('Ocean NA/EU', 'Game Boy');
replace into games (name, console_name) values ('Ocean Software EU', 'Game Boy');
replace into games (name, console_name) values ('Oddworld Adventures', 'Game Boy');
replace into games (name, console_name) values ('Olympic Summer Games: Atlanta 1996', 'Game Boy');
replace into games (name, console_name) values ('Operation C', 'Game Boy');
replace into games (name, console_name) values ('Out of Gas', 'Game Boy');
replace into games (name, console_name) values ('PGA European Tour', 'Game Boy');
replace into games (name, console_name) values ('PGA Tour 96', 'Game Boy');
replace into games (name, console_name) values ('Pac-Attack', 'Game Boy');
replace into games (name, console_name) values ('Pac-In-Time', 'Game Boy');
replace into games (name, console_name) values ('Pac-Man', 'Game Boy');
replace into games (name, console_name) values ('Pagemaster, The', 'Game Boy');
replace into games (name, console_name) values ('Palcom Software EU', 'Game Boy');
replace into games (name, console_name) values ('Panel Action Bingo', 'Game Boy');
replace into games (name, console_name) values ('Pang EU', 'Game Boy');
replace into games (name, console_name) values ('Paperboy 2', 'Game Boy');
replace into games (name, console_name) values ('Paperboy', 'Game Boy');
replace into games (name, console_name) values ('Parker Brothers NA', 'Game Boy');
replace into games (name, console_name) values ('Penguin Wars', 'Game Boy');
replace into games (name, console_name) values ('Phantom Air Mission EU', 'Game Boy');
replace into games (name, console_name) values ('Pinball Dreams', 'Game Boy');
replace into games (name, console_name) values ('Pinball Fantasies', 'Game Boy');
replace into games (name, console_name) values ('Pinball: Revenge of the Gator', 'Game Boy');
replace into games (name, console_name) values ('Pipe Dream', 'Game Boy');
replace into games (name, console_name) values ('Pit-Fighter', 'Game Boy');
replace into games (name, console_name) values ('Play Action Football', 'Game Boy');
replace into games (name, console_name) values ('Pokémon Blue Version', 'Game Boy');
replace into games (name, console_name) values ('Pokémon Red Version', 'Game Boy');
replace into games (name, console_name) values ('Pokémon Yellow Version: Special Pikachu Edition', 'Game Boy');
replace into games (name, console_name) values ('Pop Up EU', 'Game Boy');
replace into games (name, console_name) values ('Popeye 2', 'Game Boy');
replace into games (name, console_name) values ('Power Mission', 'Game Boy');
replace into games (name, console_name) values ('Power Racer', 'Game Boy');
replace into games (name, console_name) values ('Prehistorik Man', 'Game Boy');
replace into games (name, console_name) values ('Primal Rage', 'Game Boy');
replace into games (name, console_name) values ('Prince of Persia', 'Game Boy');
replace into games (name, console_name) values ('Probotector 2 EU', 'Game Boy');
replace into games (name, console_name) values ('Probotector EU', 'Game Boy');
replace into games (name, console_name) values ('Prophecy: The Viking Child', 'Game Boy');
replace into games (name, console_name) values ('Punisher: The Ultimate Payback, The', 'Game Boy');
replace into games (name, console_name) values ('Pyramids of Ra', 'Game Boy');
replace into games (name, console_name) values ('Q*bert for Game Boy', 'Game Boy');
replace into games (name, console_name) values ('QBillion', 'Game Boy');
replace into games (name, console_name) values ('Qix', 'Game Boy');
replace into games (name, console_name) values ('Quarth', 'Game Boy');
replace into games (name, console_name) values ('R-Type', 'Game Boy');
replace into games (name, console_name) values ('Race Days', 'Game Boy');
replace into games (name, console_name) values ('Race Drivin	Argonaut Games', 'Game Boy');
replace into games (name, console_name) values ('Radar Mission', 'Game Boy');
replace into games (name, console_name) values ('Raging Fighter', 'Game Boy');
replace into games (name, console_name) values ('Real Ghostbusters, The', 'Game Boy');
replace into games (name, console_name) values ('Ren & Stimpy Show: Space Cadet Adventure, The', 'Game Boy');
replace into games (name, console_name) values ('Ren & Stimpy Show: Veediots!, The', 'Game Boy');
replace into games (name, console_name) values ('Riddick Bowe Boxing', 'Game Boy');
replace into games (name, console_name) values ('Ring Rage', 'Game Boy');
replace into games (name, console_name) values ('Road Rash', 'Game Boy');
replace into games (name, console_name) values ('Robin Hood: Prince of Thieves', 'Game Boy');
replace into games (name, console_name) values ('RoboCop 2', 'Game Boy');
replace into games (name, console_name) values ('RoboCop Versus The Terminator', 'Game Boy');
replace into games (name, console_name) values ('RoboCop', 'Game Boy');
replace into games (name, console_name) values ('Roger Clemens MVP Baseball', 'Game Boy');
replace into games (name, console_name) values ('Rolans Curse 2', 'Game Boy');
replace into games (name, console_name) values ('Rolans Curse', 'Game Boy');
replace into games (name, console_name) values ('Romstar NA', 'Game Boy');
replace into games (name, console_name) values ('Rugrats Movie, The', 'Game Boy');
replace into games (name, console_name) values ('SOFEL NA', 'Game Boy');
replace into games (name, console_name) values ('Samurai Shodown', 'Game Boy');
replace into games (name, console_name) values ('Serpent', 'Game Boy');
replace into games (name, console_name) values ('Shadow Warriors: Ninja Gaiden EU', 'Game Boy');
replace into games (name, console_name) values ('Shanghai', 'Game Boy');
replace into games (name, console_name) values ('Shaq Fu', 'Game Boy');
replace into games (name, console_name) values ('Side Pocket', 'Game Boy');
replace into games (name, console_name) values ('Simpsons: Bart & the Beanstalk, The', 'Game Boy');
replace into games (name, console_name) values ('Simpsons: Bart vs. The Juggernauts, The', 'Game Boy');
replace into games (name, console_name) values ('Simpsons: Itchy & Scratchy in Miniature Golf Madness, The', 'Game Boy');
replace into games (name, console_name) values ('Skate or Die: Bad n Rad', 'Game Boy');
replace into games (name, console_name) values ('Skate or Die: Tour de Thrash', 'Game Boy');
replace into games (name, console_name) values ('Small Soldiers', 'Game Boy');
replace into games (name, console_name) values ('Sneaky Snakes', 'Game Boy');
replace into games (name, console_name) values ('Snoopys Magic Show', 'Game Boy');
replace into games (name, console_name) values ('Snow Bros. Jr.	Toaplan', 'Game Boy');
replace into games (name, console_name) values ('Soccer EU', 'Game Boy');
replace into games (name, console_name) values ('Soccer Mania', 'Game Boy');
replace into games (name, console_name) values ('SolarStriker', 'Game Boy');
replace into games (name, console_name) values ('Solitaire FunPak', 'Game Boy');
replace into games (name, console_name) values ('Solomons Club', 'Game Boy');
replace into games (name, console_name) values ('Sony Electronics EU', 'Game Boy');
replace into games (name, console_name) values ('Sony Imagesoft EU', 'Game Boy');
replace into games (name, console_name) values ('Sony Imagesoft NA', 'Game Boy');
replace into games (name, console_name) values ('Space Invaders', 'Game Boy');
replace into games (name, console_name) values ('Spankys Quest', 'Game Boy');
replace into games (name, console_name) values ('Speedball 2: Brutal Deluxe', 'Game Boy');
replace into games (name, console_name) values ('Speedy Gonzales', 'Game Boy');
replace into games (name, console_name) values ('Spider-Man 3: Invasion of the Spider-Slayers', 'Game Boy');
replace into games (name, console_name) values ('Spider-Man and the X-Men in Arcades Revenge', 'Game Boy');
replace into games (name, console_name) values ('Sports Illustrated for Kids: The Ultimate Triple Dare!	Halestorm', 'Game Boy');
replace into games (name, console_name) values ('Sports Illustrated: Championship Football & Baseball', 'Game Boy');
replace into games (name, console_name) values ('Sports Illustrated: Golf Classic', 'Game Boy');
replace into games (name, console_name) values ('Spot: The Cool Adventure', 'Game Boy');
replace into games (name, console_name) values ('Spot: The Video Game', 'Game Boy');
replace into games (name, console_name) values ('Spuds Adventure', 'Game Boy');
replace into games (name, console_name) values ('Spy vs. Spy: Operation Boobytrap', 'Game Boy');
replace into games (name, console_name) values ('Square Deal: The Game of Two Dimensional Poker', 'Game Boy');
replace into games (name, console_name) values ('Star Trek Generations: Beyond the Nexus', 'Game Boy');
replace into games (name, console_name) values ('Star Trek: 25th Anniversary', 'Game Boy');
replace into games (name, console_name) values ('Star Trek: The Next Generation', 'Game Boy');
replace into games (name, console_name) values ('Star Wars: The Empire Strikes Back', 'Game Boy');
replace into games (name, console_name) values ('Star Wars', 'Game Boy');
replace into games (name, console_name) values ('StarHawk', 'Game Boy');
replace into games (name, console_name) values ('Stargate', 'Game Boy');
replace into games (name, console_name) values ('Stop That Roach!', 'Game Boy');
replace into games (name, console_name) values ('Street Fighter II', 'Game Boy');
replace into games (name, console_name) values ('Street Racer', 'Game Boy');
replace into games (name, console_name) values ('Sumo Fighter', 'Game Boy');
replace into games (name, console_name) values ('Sunsoft EU', 'Game Boy');
replace into games (name, console_name) values ('Sunsoft Grand Prix', 'Game Boy');
replace into games (name, console_name) values ('Sunsoft NA', 'Game Boy');
replace into games (name, console_name) values ('Super Battletank: War in the Gulf', 'Game Boy');
replace into games (name, console_name) values ('Super Black Bass', 'Game Boy');
replace into games (name, console_name) values ('Super Chase H.Q.	ITL', 'Game Boy');
replace into games (name, console_name) values ('Super Hunchback', 'Game Boy');
replace into games (name, console_name) values ('Super Mario Land 2: 6 Golden Coins', 'Game Boy');
replace into games (name, console_name) values ('Super Mario Land 3: Wario Land', 'Game Boy');
replace into games (name, console_name) values ('Super Mario Land', 'Game Boy');
replace into games (name, console_name) values ('Super Off Road', 'Game Boy');
replace into games (name, console_name) values ('Super R.C. Pro-Am', 'Game Boy');
replace into games (name, console_name) values ('Super Scrabble', 'Game Boy');
replace into games (name, console_name) values ('Super Star Wars: Return of the Jedi', 'Game Boy');
replace into games (name, console_name) values ('Superman', 'Game Boy');
replace into games (name, console_name) values ('Swamp Thing', 'Game Boy');
replace into games (name, console_name) values ('Sword of Hope II, The', 'Game Boy');
replace into games (name, console_name) values ('Sword of Hope, The', 'Game Boy');
replace into games (name, console_name) values ('T2: The Arcade Game', 'Game Boy');
replace into games (name, console_name) values ('THQ NA', 'Game Boy');
replace into games (name, console_name) values ('Tail Gator', 'Game Boy');
replace into games (name, console_name) values ('Taito Chase H.Q.	Bits Studios', 'Game Boy');
replace into games (name, console_name) values ('Taito Corporation NA/EU', 'Game Boy');
replace into games (name, console_name) values ('Takara NA/EU', 'Game Boy');
replace into games (name, console_name) values ('Takara NA', 'Game Boy');
replace into games (name, console_name) values ('Tamagotchi', 'Game Boy');
replace into games (name, console_name) values ('Tarzan: Lord of the Jungle', 'Game Boy');
replace into games (name, console_name) values ('Tasmania Monogatari', 'Game Boy');
replace into games (name, console_name) values ('Tasmania Story', 'Game Boy');
replace into games (name, console_name) values ('Taxan NA/EU', 'Game Boy');
replace into games (name, console_name) values ('Taxan NA', 'Game Boy');
replace into games (name, console_name) values ('Taz-Mania 2', 'Game Boy');
replace into games (name, console_name) values ('Taz-Mania EU', 'Game Boy');
replace into games (name, console_name) values ('Taz-Mania', 'Game Boy');
replace into games (name, console_name) values ('Tecmo Bowl', 'Game Boy');
replace into games (name, console_name) values ('Teenage Mutant Hero Turtles II: Back From the Sewers EU', 'Game Boy');
replace into games (name, console_name) values ('Teenage Mutant Hero Turtles III: Radical Rescue EU', 'Game Boy');
replace into games (name, console_name) values ('Teenage Mutant Hero Turtles: Fall of the Foot Clan EU', 'Game Boy');
replace into games (name, console_name) values ('Teenage Mutant Ninja Turtles II: Back from the Sewers', 'Game Boy');
replace into games (name, console_name) values ('Teenage Mutant Ninja Turtles III: Radical Rescue', 'Game Boy');
replace into games (name, console_name) values ('Teenage Mutant Ninja Turtles: Fall of the Foot Clan', 'Game Boy');
replace into games (name, console_name) values ('Tennis', 'Game Boy');
replace into games (name, console_name) values ('Terminator 2: Judgment Day', 'Game Boy');
replace into games (name, console_name) values ('Tesserae', 'Game Boy');
replace into games (name, console_name) values ('Tetris 2', 'Game Boy');
replace into games (name, console_name) values ('Tetris Attack', 'Game Boy');
replace into games (name, console_name) values ('Tetris Blast', 'Game Boy');
replace into games (name, console_name) values ('Tetris Plus', 'Game Boy');
replace into games (name, console_name) values ('Tetris', 'Game Boy');
replace into games (name, console_name) values ('The Legend of Prince Valiant EU', 'Game Boy');
replace into games (name, console_name) values ('The Sales Curve EU', 'Game Boy');
replace into games (name, console_name) values ('The Spirit of F-1 EU', 'Game Boy');
replace into games (name, console_name) values ('Tiny Toon Adventures 2: Montanas Movie Madness', 'Game Boy');
replace into games (name, console_name) values ('Tiny Toon Adventures: Babs Big Break', 'Game Boy');
replace into games (name, console_name) values ('Tiny Toon Adventures: Wacky Sports', 'Game Boy');
replace into games (name, console_name) values ('Titus Software', 'Game Boy');
replace into games (name, console_name) values ('Titus the Fox', 'Game Boy');
replace into games (name, console_name) values ('Tom & Jerry 2: The Movie EU', 'Game Boy');
replace into games (name, console_name) values ('Tom & Jerry', 'Game Boy');
replace into games (name, console_name) values ('Tom and Jerry: Frantic Antics', 'Game Boy');
replace into games (name, console_name) values ('Top Gun: Guts and Glory', 'Game Boy');
replace into games (name, console_name) values ('Top Rank Tennis', 'Game Boy');
replace into games (name, console_name) values ('Top Ranking Tennis EU', 'Game Boy');
replace into games (name, console_name) values ('Torpedo Range', 'Game Boy');
replace into games (name, console_name) values ('Total Carnage', 'Game Boy');
replace into games (name, console_name) values ('Toxic Crusaders', 'Game Boy');
replace into games (name, console_name) values ('Track & Field', 'Game Boy');
replace into games (name, console_name) values ('Track Meet', 'Game Boy');
replace into games (name, console_name) values ('Tradewest NA', 'Game Boy');
replace into games (name, console_name) values ('Trax', 'Game Boy');
replace into games (name, console_name) values ('True Lies', 'Game Boy');
replace into games (name, console_name) values ('Tumblepop', 'Game Boy');
replace into games (name, console_name) values ('Turn and Burn: The F-14 Dogfight Simulator', 'Game Boy');
replace into games (name, console_name) values ('Turok: Battle of the Bionosaurs', 'Game Boy');
replace into games (name, console_name) values ('Turrican', 'Game Boy');
replace into games (name, console_name) values ('Ubisoft EU', 'Game Boy');
replace into games (name, console_name) values ('Ubisoft NA/EU', 'Game Boy');
replace into games (name, console_name) values ('Ubisoft NA', 'Game Boy');
replace into games (name, console_name) values ('Ultima: Runes of Virtue II', 'Game Boy');
replace into games (name, console_name) values ('Ultima: Runes of Virtue', 'Game Boy');
replace into games (name, console_name) values ('Ultra Games NA', 'Game Boy');
replace into games (name, console_name) values ('Ultra Golf', 'Game Boy');
replace into games (name, console_name) values ('Universal Soldier', 'Game Boy');
replace into games (name, console_name) values ('Urban Strike', 'Game Boy');
replace into games (name, console_name) values ('VAP', 'Game Boy');
replace into games (name, console_name) values ('Vegas Stakes', 'Game Boy');
replace into games (name, console_name) values ('Virgin Interactive EU', 'Game Boy');
replace into games (name, console_name) values ('Virgin Interactive', 'Game Boy');
replace into games (name, console_name) values ('WCW World Championship Wrestling: The Main Event', 'Game Boy');
replace into games (name, console_name) values ('WCW Wrestling: The Main Event EU', 'Game Boy');
replace into games (name, console_name) values ('WWF King of the Ring', 'Game Boy');
replace into games (name, console_name) values ('WWF Raw', 'Game Boy');
replace into games (name, console_name) values ('WWF Superstars 2', 'Game Boy');
replace into games (name, console_name) values ('WWF Superstars', 'Game Boy');
replace into games (name, console_name) values ('WWF War Zone', 'Game Boy');
replace into games (name, console_name) values ('Wario Blast: Featuring Bomberman!', 'Game Boy');
replace into games (name, console_name) values ('Wario Land II', 'Game Boy');
replace into games (name, console_name) values ('Wario Land: Super Mario Land 3', 'Game Boy');
replace into games (name, console_name) values ('Wave Race', 'Game Boy');
replace into games (name, console_name) values ('Waynes World', 'Game Boy');
replace into games (name, console_name) values ('Were Back!: A Dinosaurs Story', 'Game Boy');
replace into games (name, console_name) values ('Wheel of Fortune', 'Game Boy');
replace into games (name, console_name) values ('Who Framed Roger Rabbit', 'Game Boy');
replace into games (name, console_name) values ('WildSnake', 'Game Boy');
replace into games (name, console_name) values ('Winter Gold EU', 'Game Boy');
replace into games (name, console_name) values ('Winter Olympic Games: Lillehammer 94', 'Game Boy');
replace into games (name, console_name) values ('Wizards & Warriors X: The Fortress of Fear', 'Game Boy');
replace into games (name, console_name) values ('WordZap', 'Game Boy');
replace into games (name, console_name) values ('Wordtris', 'Game Boy');
replace into games (name, console_name) values ('World Bowling', 'Game Boy');
replace into games (name, console_name) values ('World Circuit Series', 'Game Boy');
replace into games (name, console_name) values ('World Cup 98', 'Game Boy');
replace into games (name, console_name) values ('World Heroes 2 Jet', 'Game Boy');
replace into games (name, console_name) values ('Xenon 2 Megablast', 'Game Boy');
replace into games (name, console_name) values ('Yannick Noah Tennis EU', 'Game Boy');
replace into games (name, console_name) values ('Yogi Bear in Yogi Bears Goldrush EU', 'Game Boy');
replace into games (name, console_name) values ('Yogi Bears Gold Rush', 'Game Boy');
replace into games (name, console_name) values ('Yoshis Cookie', 'Game Boy');
replace into games (name, console_name) values ('Yoshi', 'Game Boy');
replace into games (name, console_name) values ('Zen: Intergalactic Ninja', 'Game Boy');
replace into games (name, console_name) values ('Zool: Ninja of the "Nth" Dimension', 'Game Boy');
replace into games (name, console_name) values ('Zoop', 'Game Boy');
replace into games (name, console_name) values ('seaQuest DSV', 'Game Boy');
