replace into games (name, console_name) values ( '5 in One Fun Pak', 'Game Gear');
replace into games (name, console_name) values ( 'Acclaim Japan JP', 'Game Gear');
replace into games (name, console_name) values ( 'Adventures of Batman & Robin, The', 'Game Gear');
replace into games (name, console_name) values ( 'Aerial Assault', 'Game Gear');
replace into games (name, console_name) values ( 'Acclaim Japan JP', 'Game Gear');
replace into games (name, console_name) values ( 'Andre Agassi Tennis', 'Game Gear');
replace into games (name, console_name) values ( 'Arcade Classics', 'Game Gear');
replace into games (name, console_name) values ( 'Arch Rivals', 'Game Gear');
replace into games (name, console_name) values ( 'Arena EU', 'Game Gear');
replace into games (name, console_name) values ( 'Ariel the Little Mermaid', 'Game Gear');
replace into games (name, console_name) values ( 'Asterix and the Great Rescue', 'Game Gear');
replace into games (name, console_name) values ( 'Ax Battler: Golden Axe Densetsu JP', 'Game Gear');
replace into games (name, console_name) values ( 'Baku Baku Animal: Sekai Shiiku Gakari Senshuken JP', 'Game Gear');
replace into games (name, console_name) values ( 'Batman Forever', 'Game Gear');
replace into games (name, console_name) values ( 'Batman Returns', 'Game Gear');
replace into games (name, console_name) values ( 'Gear Stadium Heiseiban JP', 'Game Gear');
replace into games (name, console_name) values ( 'Battleship: The Classic Naval Combat Game', 'Game Gear');
replace into games (name, console_name) values ( 'Battletoads', 'Game Gear');
replace into games (name, console_name) values ( 'Beavis and Butt-head', 'Game Gear');
replace into games (name, console_name) values ( 'The Berenstain Bears Camping Adventure', 'Game Gear');
replace into games (name, console_name) values ( 'Bram Stokers Dracula', 'Game Gear');
replace into games (name, console_name) values ( 'Bubble Bobble', 'Game Gear');
replace into games (name, console_name) values ( 'Bugs Bunny in Double Trouble', 'Game Gear');
replace into games (name, console_name) values ( 'Puzzle Bobble JP', 'Game Gear');
replace into games (name, console_name) values ( 'Caesars Palace', 'Game Gear');
replace into games (name, console_name) values ( 'Captain America and The Avengers', 'Game Gear');
replace into games (name, console_name) values ( 'Casino Fun Pack', 'Game Gear');
replace into games (name, console_name) values ( 'Mickey Mouse no Castle Illusion JP', 'Game Gear');
replace into games (name, console_name) values ( 'Chakan: The Forever Man', 'Game Gear');
replace into games (name, console_name) values ( 'Sega JP', 'Game Gear');
replace into games (name, console_name) values ( 'Cheese Cat-Astrophe Starring Speedy Gonzales', 'Game Gear');
replace into games (name, console_name) values ( 'Sega Chess BR', 'Game Gear');
replace into games (name, console_name) values ( 'Chicago Syndicate', 'Game Gear');
replace into games (name, console_name) values ( 'Choplifter III', 'Game Gear');
replace into games (name, console_name) values ( 'Chuck Rock', 'Game Gear');
replace into games (name, console_name) values ( 'Virgin Interactive EU', 'Game Gear');
replace into games (name, console_name) values ( 'CJ Elephant Fugitive', 'Game Gear');
replace into games (name, console_name) values ( 'Cliffhanger', 'Game Gear');
replace into games (name, console_name) values ( 'Clutch Hitter', 'Game Gear');
replace into games (name, console_name) values ( 'Shapes and Columns BR', 'Game Gear');
replace into games (name, console_name) values ( 'Cool Spot', 'Game Gear');
replace into games (name, console_name) values ( 'Cosmic Spacehead', 'Game Gear');
replace into games (name, console_name) values ( 'Arliel - Crystal Densetsu JP', 'Game Gear');
replace into games (name, console_name) values ( 'Cutthroat Island', 'Game Gear');
replace into games (name, console_name) values ( 'Travel Tickle', 'Game Gear');
replace into games (name, console_name) values ( 'Sadam Crusader: Harukanaru Oukoku JP', 'Game Gear');
replace into games (name, console_name) values ( 'Desert Speedtrap starring Road Runner & Wile E. Coyote', 'Game Gear');
replace into games (name, console_name) values ( 'Desert Strike EU', 'Game Gear');
replace into games (name, console_name) values ( 'Devilish', 'Game Gear');
replace into games (name, console_name) values ( 'Genki JP', 'Game Gear');
replace into games (name, console_name) values ( 'Disneys Aladdin', 'Game Gear');
replace into games (name, console_name) values ( 'Disneys Bonkers: Wax Up!', 'Game Gear');
replace into games (name, console_name) values ( 'Disneys The Jungle Book', 'Game Gear');
replace into games (name, console_name) values ( 'Double Dragon: The Revenge of Billy Lee EU', 'Game Gear');
replace into games (name, console_name) values ( 'Dr. Robotniks Mean Bean Machine', 'Game Gear');
replace into games (name, console_name) values ( 'Dragon: The Bruce Lee Story', 'Game Gear');
replace into games (name, console_name) values ( 'Virgin Interactive EU', 'Game Gear');
replace into games (name, console_name) values ( 'Dragon Crystal: Tsurani no Meikyuu JP', 'Game Gear');
replace into games (name, console_name) values ( 'Dynamite Headdy', 'Game Gear');
replace into games (name, console_name) values ( 'Virgin Interactive EU', 'Game Gear');
replace into games (name, console_name) values ( 'Ecco the Dolphin', 'Game Gear');
replace into games (name, console_name) values ( 'Ecco the Dolphin 2 JP', 'Game Gear');
replace into games (name, console_name) values ( 'Evander "Real Deal" Holyfields Boxing', 'Game Gear');
replace into games (name, console_name) values ( 'F-15 Strike Eagle', 'Game Gear');
replace into games (name, console_name) values ( 'Formula One NA', 'Game Gear');
replace into games (name, console_name) values ( 'Fantastic Dizzy', 'Game Gear');
replace into games (name, console_name) values ( ' Sega EU', 'Game Gear');
replace into games (name, console_name) values ( 'Garou Densetsu Special JP', 'Game Gear');
replace into games (name, console_name) values ( 'FIFA International Soccer', 'Game Gear');
replace into games (name, console_name) values ( 'Black Pearl EU', 'Game Gear');
replace into games (name, console_name) values ( 'Foreman For Real', 'Game Gear');
replace into games (name, console_name) values ( 'Frank Thomas Big Hurt Baseball', 'Game Gear');
replace into games (name, console_name) values ( 'Fred Couples Golf', 'Game Gear');
replace into games (name, console_name) values ( 'G-LOC: Air Battle', 'Game Gear');
replace into games (name, console_name) values ( 'Garfield: Caught in the Act', 'Game Gear');
replace into games (name, console_name) values ( 'Gear Works', 'Game Gear');
replace into games (name, console_name) values ( 'George Foremans KO Boxing', 'Game Gear');
replace into games (name, console_name) values ( 'GP Rider', 'Game Gear');
replace into games (name, console_name) values ( 'Interactive Designs', 'Game Gear');
replace into games (name, console_name) values ( 'Space Battle BR', 'Game Gear');
replace into games (name, console_name) values ( 'Home Alone', 'Game Gear');
replace into games (name, console_name) values ( 'Hook', 'Game Gear');
replace into games (name, console_name) values ( 'Incredible Crash Dummies: Slick Bouya no Daichousen, The JP', 'Game Gear');
replace into games (name, console_name) values ( 'Incredible Hulk, The', 'Game Gear');
replace into games (name, console_name) values ( 'Indiana Jones and the Last Crusade', 'Game Gear');
replace into games (name, console_name) values ( 'Iron Man and X-O Manowar in Heavy Metal', 'Game Gear');
replace into games (name, console_name) values ( 'Itchy & Scratchy Game, The', 'Game Gear');
replace into games (name, console_name) values ( 'James Pond 2: Codename: Robocod EU', 'Game Gear');
replace into games (name, console_name) values ( 'Jeopardy!', 'Game Gear');
replace into games (name, console_name) values ( 'Jeopardy! Sports Edition', 'Game Gear');
replace into games (name, console_name) values ( 'Joe Montana Football', 'Game Gear');
replace into games (name, console_name) values ( 'Journey from Darkness: Strider Returns', 'Game Gear');
replace into games (name, console_name) values ( 'Judge Dredd', 'Game Gear');
replace into games (name, console_name) values ( 'Junction', 'Game Gear');
replace into games (name, console_name) values ( 'Jungle Strike', 'Game Gear');
replace into games (name, console_name) values ( 'Jurassic Park', 'Game Gear');
replace into games (name, console_name) values ( 'Kawasaki Superbikes', 'Game Gear');
replace into games (name, console_name) values ( 'Klax', 'Game Gear');
replace into games (name, console_name) values ( 'Krustys Fun House', 'Game Gear');
replace into games (name, console_name) values ( 'Mickey Mouse no Mahou no Crystal JP', 'Game Gear');
replace into games (name, console_name) values ( 'Last Action Hero', 'Game Gear');
replace into games (name, console_name) values ( 'Mickey Mouse: Densetsu no Oukoku JP', 'Game Gear');
replace into games (name, console_name) values ( 'Lemmings', 'Game Gear');
replace into games (name, console_name) values ( 'Lion King, The', 'Game Gear');
replace into games (name, console_name) values ( 'Lost World, The: Jurassic Park', 'Game Gear');
replace into games (name, console_name) values ( 'Donald Duck no Lucky Dime JP', 'Game Gear');
replace into games (name, console_name) values ( 'Madden NFL 95', 'Game Gear');
replace into games (name, console_name) values ( 'Madden 96', 'Game Gear');
replace into games (name, console_name) values ( 'Popils: The Blockbusting Challenge EU', 'Game Gear');
replace into games (name, console_name) values ( 'Majors Pro Baseball, The', 'Game Gear');
replace into games (name, console_name) values ( 'Marble Madness', 'Game Gear');
replace into games (name, console_name) values ( 'Mega Man', 'Game Gear');
replace into games (name, console_name) values ( 'Mickeys Ultimate Challenge', 'Game Gear');
replace into games (name, console_name) values ( 'Micro Machines', 'Game Gear');
replace into games (name, console_name) values ( 'Mighty Morphin Power Rangers', 'Game Gear');
replace into games (name, console_name) values ( 'Mighty Morphin Power Rangers: The Movie', 'Game Gear');
replace into games (name, console_name) values ( 'MLBPA Baseball', 'Game Gear');
replace into games (name, console_name) values ( 'Monster Truck Wars', 'Game Gear');
replace into games (name, console_name) values ( 'Mortal Kombat', 'Game Gear');
replace into games (name, console_name) values ( 'Mortal Kombat II: Kyuukyoku Shinken JP', 'Game Gear');
replace into games (name, console_name) values ( 'Ms. Pac-Man', 'Game Gear');
replace into games (name, console_name) values ( 'NBA Action starring David Robinson', 'Game Gear');
replace into games (name, console_name) values ( 'NBA Jam', 'Game Gear');
replace into games (name, console_name) values ( 'NBA Jam Tournament Edition', 'Game Gear');
replace into games (name, console_name) values ( 'NFL 95', 'Game Gear');
replace into games (name, console_name) values ( 'NFL Quarterback Club 95 JP', 'Game Gear');
replace into games (name, console_name) values ( 'NFL Quarterback Club 96', 'Game Gear');
replace into games (name, console_name) values ( 'NHL All-Star Hockey', 'Game Gear');
replace into games (name, console_name) values ( 'NHL Hockey', 'Game Gear');
replace into games (name, console_name) values ( 'Ninja Gaiden', 'Game Gear');
replace into games (name, console_name) values ( 'Olympic Gold: Barcelona 92', 'Game Gear');
replace into games (name, console_name) values ( 'Out Run Europa', 'Game Gear');
replace into games (name, console_name) values ( 'Pac-Attack', 'Game Gear');
replace into games (name, console_name) values ( 'Pac-Man', 'Game Gear');
replace into games (name, console_name) values ( 'Paperboy', 'Game Gear');
replace into games (name, console_name) values ( 'Paperboy 2', 'Game Gear');
replace into games (name, console_name) values ( 'Pete Sampras Tennis', 'Game Gear');
replace into games (name, console_name) values ( 'PGA Tour Golf', 'Game Gear');
replace into games (name, console_name) values ( 'PGA Tour Golf II', 'Game Gear');
replace into games (name, console_name) values ( 'PGA Tour 96', 'Game Gear');
replace into games (name, console_name) values ( 'Phantom 2040', 'Game Gear');
replace into games (name, console_name) values ( 'Pinball Dreams', 'Game Gear');
replace into games (name, console_name) values ( 'Poker Face Pauls Blackjack', 'Game Gear');
replace into games (name, console_name) values ( 'Poker Face Pauls Gin', 'Game Gear');
replace into games (name, console_name) values ( 'Poker Face Pauls Poker', 'Game Gear');
replace into games (name, console_name) values ( 'Poker Face Pauls Solitaire', 'Game Gear');
replace into games (name, console_name) values ( 'Predator 2', 'Game Gear');
replace into games (name, console_name) values ( 'Primal Rage', 'Game Gear');
replace into games (name, console_name) values ( 'Domark EU', 'Game Gear');
replace into games (name, console_name) values ( 'Psychic World', 'Game Gear');
replace into games (name, console_name) values ( 'Minigolf BR', 'Game Gear');
replace into games (name, console_name) values ( 'Ren Hoek and Stimpy: Quest for the Shaven Yak', 'Game Gear');
replace into games (name, console_name) values ( 'R.B.I. Baseball 94', 'Game Gear');
replace into games (name, console_name) values ( 'R.C. Grand Prix', 'Game Gear');
replace into games (name, console_name) values ( 'Riddick Bowe Boxing', 'Game Gear');
replace into games (name, console_name) values ( 'Rise of the Robots', 'Game Gear');
replace into games (name, console_name) values ( 'Ristar: The Shooting Star JP', 'Game Gear');
replace into games (name, console_name) values ( 'Road Rash', 'Game Gear');
replace into games (name, console_name) values ( 'RoboCop 3', 'Game Gear');
replace into games (name, console_name) values ( 'RoboCop Versus The Terminator', 'Game Gear');
replace into games (name, console_name) values ( 'Samurai Spirits JP', 'Game Gear');
replace into games (name, console_name) values ( 'Scratch Golf', 'Game Gear');
replace into games (name, console_name) values ( 'Shaq Fu', 'Game Gear');
replace into games (name, console_name) values ( 'Shining Force Gaiden II: Jashin no Mesame JP', 'Game Gear');
replace into games (name, console_name) values ( 'The GG Shinobi JP', 'Game Gear');
replace into games (name, console_name) values ( 'The GG Shinobi II: The Silent Fury JP', 'Game Gear');
replace into games (name, console_name) values ( 'Side Pocket', 'Game Gear');
replace into games (name, console_name) values ( 'Simpsons, The: Bartman Meets Radioactive Man', 'Game Gear');
replace into games (name, console_name) values ( 'Simpsons, The: Bart vs. the Space Mutants', 'Game Gear');
replace into games (name, console_name) values ( 'Simpsons, The: Bart vs. the World', 'Game Gear');
replace into games (name, console_name) values ( 'Skweek JP', 'Game Gear');
replace into games (name, console_name) values ( 'Solitaire Funpak', 'Game Gear');
replace into games (name, console_name) values ( 'Ryuu Kyuu JP', 'Game Gear');
replace into games (name, console_name) values ( 'G Sonic JP', 'Game Gear');
replace into games (name, console_name) values ( 'Sonic & Tails JP', 'Game Gear');
replace into games (name, console_name) values ( 'Sonic Drift Racing EU', 'Game Gear');
replace into games (name, console_name) values ( 'Sonic Labyrinth', 'Game Gear');
replace into games (name, console_name) values ( 'Sonic the Hedgehog Spinball', 'Game Gear');
replace into games (name, console_name) values ( 'Sonic The Hedgehog', 'Game Gear');
replace into games (name, console_name) values ( 'Sonic The Hedgehog 2', 'Game Gear');
replace into games (name, console_name) values ( 'Sonic & Tails 2 JP', 'Game Gear');
replace into games (name, console_name) values ( 'Space Harrier', 'Game Gear');
replace into games (name, console_name) values ( 'Spider-Man vs. The Kingpin', 'Game Gear');
replace into games (name, console_name) values ( 'Spider-Man: Return of the Sinister Six', 'Game Gear');
replace into games (name, console_name) values ( 'Spider-Man/X-Men: Arcades Revenge', 'Game Gear');
replace into games (name, console_name) values ( 'Sports Illustrated: Championship Football & Baseball', 'Game Gear');
replace into games (name, console_name) values ( 'Sports Trivia: Championship Edition', 'Game Gear');
replace into games (name, console_name) values ( 'Stargate', 'Game Gear');
replace into games (name, console_name) values ( 'Star Trek: The Next Generation: The Advanced Holodeck Tutorial', 'Game Gear');
replace into games (name, console_name) values ( 'Star Trek Generations: Beyond the Nexus', 'Game Gear');
replace into games (name, console_name) values ( 'Star Wars', 'Game Gear');
replace into games (name, console_name) values ( 'Bare Knuckle: Ikari no Tekken JP', 'Game Gear');
replace into games (name, console_name) values ( 'Bare Knuckle II: Shitou e no Chingonka JP', 'Game Gear');
replace into games (name, console_name) values ( 'Super Battletank', 'Game Gear');
replace into games (name, console_name) values ( 'Super Columns', 'Game Gear');
replace into games (name, console_name) values ( 'Super Golf', 'Game Gear');
replace into games (name, console_name) values ( 'Super Monaco GP', 'Game Gear');
replace into games (name, console_name) values ( 'Ayrton Sennas Super Monaco GP II', 'Game Gear');
replace into games (name, console_name) values ( 'Super Off Road', 'Game Gear');
replace into games (name, console_name) values ( 'Super Smash TV', 'Game Gear');
replace into games (name, console_name) values ( 'Super Space Invaders', 'Game Gear');
replace into games (name, console_name) values ( 'Super Star Wars: Return of the Jedi', 'Game Gear');
replace into games (name, console_name) values ( 'Surf Ninjas', 'Game Gear');
replace into games (name, console_name) values ( 'T2: The Arcade Game', 'Game Gear');
replace into games (name, console_name) values ( 'Tails Adventure', 'Game Gear');
replace into games (name, console_name) values ( 'TaleSpin', 'Game Gear');
replace into games (name, console_name) values ( 'Taz-Mania', 'Game Gear');
replace into games (name, console_name) values ( 'Taz in Escape from Mars', 'Game Gear');
replace into games (name, console_name) values ( 'Tempo Jr.', 'Game Gear');
replace into games (name, console_name) values ( 'Kick & Rush JP', 'Game Gear');
replace into games (name, console_name) values ( 'Terminator, The', 'Game Gear');
replace into games (name, console_name) values ( 'Terminator 2: Judgment Day', 'Game Gear');
replace into games (name, console_name) values ( 'Tesserae', 'Game Gear');
replace into games (name, console_name) values ( 'The Smurfs[1]', 'Game Gear');
replace into games (name, console_name) values ( 'Tom and Jerry: The Movie', 'Game Gear');
replace into games (name, console_name) values ( 'True Lies', 'Game Gear');
replace into games (name, console_name) values ( 'Urban Strike', 'Game Gear');
replace into games (name, console_name) values ( 'In the Wake of Vampire JP', 'Game Gear');
replace into games (name, console_name) values ( 'Virtua Fighter Mini JP', 'Game Gear');
replace into games (name, console_name) values ( 'VR Troopers', 'Game Gear');
replace into games (name, console_name) values ( 'Wheel of Fortune', 'Game Gear');
replace into games (name, console_name) values ( 'Wimbledon', 'Game Gear');
replace into games (name, console_name) values ( 'Winter Olympics: Lillehammer 94', 'Game Gear');
replace into games (name, console_name) values ( 'Revenge of Drancon NA', 'Game Gear');
replace into games (name, console_name) values ( 'Woody Pop', 'Game Gear');
replace into games (name, console_name) values ( 'World Class Leader Board', 'Game Gear');
replace into games (name, console_name) values ( 'World Cup USA 94', 'Game Gear');
replace into games (name, console_name) values ( 'World Series Baseball', 'Game Gear');
replace into games (name, console_name) values ( 'Nomo Hideo no World Series Baseball JP', 'Game Gear');
replace into games (name, console_name) values ( 'WWF Raw', 'Game Gear');
replace into games (name, console_name) values ( 'WWF WrestleMania: Steel Cage Challenge', 'Game Gear');
replace into games (name, console_name) values ( 'X-Men', 'Game Gear');
replace into games (name, console_name) values ( 'X-Men: Gamesmasters Legacy', 'Game Gear');
replace into games (name, console_name) values ( 'X-Men: Mojo World', 'Game Gear');
replace into games (name, console_name) values ( 'Zool no Yume Bouken JP', 'Game Gear');
replace into games (name, console_name) values ( 'Zoop', 'Game Gear');
