replace into games (name,console_name) values ( '10-Yard Fight',  'NES');
replace into games (name,console_name) values ( '1942',  'NES');
replace into games (name,console_name) values ( '1943: The Battle of Midway',  'NES');
replace into games (name,console_name) values ( '3-D Battles of World Runner, The',  'NES');
replace into games (name,console_name) values ( '720 Degrees',  'NES');
replace into games (name,console_name) values ( '8 Eyes',  'NES');
replace into games (name,console_name) values ( 'Abadox: The Deadly Inner War',  'NES');
replace into games (name,console_name) values ( 'Action 52 (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Addams Family, The',  'NES');
replace into games (name,console_name) values ( 'Adventure Island',  'NES');
replace into games (name,console_name) values ( 'Adventure Island 2',  'NES');
replace into games (name,console_name) values ( 'Adventure Island 3',  'NES');
replace into games (name,console_name) values ( 'Adventures of Bayou Billy',  'NES');
replace into games (name,console_name) values ( 'Adventures of Lolo',  'NES');
replace into games (name,console_name) values ( 'Adventures of Lolo 2',  'NES');
replace into games (name,console_name) values ( 'Adventures of Lolo 3',  'NES');
replace into games (name,console_name) values ( 'Adventures of Tom Sawyer',  'NES');
replace into games (name,console_name) values ( 'Adventures of DinoRiki',  'NES');
replace into games (name,console_name) values ( 'After Burner (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Airball (Prototype)',  'NES');
replace into games (name,console_name) values ( 'Air Fortress',  'NES');
replace into games (name,console_name) values ( 'Airwolf',  'NES');
replace into games (name,console_name) values ( 'Alfred Chicken',  'NES');
replace into games (name,console_name) values ( 'Alien3',  'NES');
replace into games (name,console_name) values ( 'Alien Syndrome (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'All Pro Basketball',  'NES');
replace into games (name,console_name) values ( 'Alpha Mission',  'NES');
replace into games (name,console_name) values ( 'Altered Beast',  'NES');
replace into games (name,console_name) values ( 'Al Unser Jr.s Turbo Racing',  'NES');
replace into games (name,console_name) values ( 'Amagon',  'NES');
replace into games (name,console_name) values ( 'American Gladiators',  'NES');
replace into games (name,console_name) values ( 'Anticipation',  'NES');
replace into games (name,console_name) values ( 'Archon',  'NES');
replace into games (name,console_name) values ( 'Arch Rivals',  'NES');
replace into games (name,console_name) values ( 'Arkanoid',  'NES');
replace into games (name,console_name) values ( 'Arkistas Ring',  'NES');
replace into games (name,console_name) values ( 'Astyanax',  'NES');
replace into games (name,console_name) values ( 'Athena',  'NES');
replace into games (name,console_name) values ( 'Athletic World',  'NES');
replace into games (name,console_name) values ( 'Attack of the Killer Tomatoes',  'NES');
replace into games (name,console_name) values ( 'Baby Boomer (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Back to the Future',  'NES');
replace into games (name,console_name) values ( 'Back to the Future II and III',  'NES');
replace into games (name,console_name) values ( 'Bad Dudes',  'NES');
replace into games (name,console_name) values ( 'Bad News Baseball',  'NES');
replace into games (name,console_name) values ( 'Bad Street Brawler',  'NES');
replace into games (name,console_name) values ( 'Balloon Fight',  'NES');
replace into games (name,console_name) values ( 'Bandit Kings of Ancient China',  'NES');
replace into games (name,console_name) values ( 'Barbie',  'NES');
replace into games (name,console_name) values ( 'Bards Tale, The',  'NES');
replace into games (name,console_name) values ( 'Baseball',  'NES');
replace into games (name,console_name) values ( 'Baseball Simulator 1,000',  'NES');
replace into games (name,console_name) values ( 'Baseball Stars',  'NES');
replace into games (name,console_name) values ( 'Baseball Stars II',  'NES');
replace into games (name,console_name) values ( 'Bases Loaded',  'NES');
replace into games (name,console_name) values ( 'Bases Loaded II: Second Season',  'NES');
replace into games (name,console_name) values ( 'Bases Loaded 3',  'NES');
replace into games (name,console_name) values ( 'Bases Loaded 4',  'NES');
replace into games (name,console_name) values ( 'Base Wars: Cyber Stadium Series',  'NES');
replace into games (name,console_name) values ( 'Batman',  'NES');
replace into games (name,console_name) values ( 'Batman: Return of the Joker',  'NES');
replace into games (name,console_name) values ( 'Batman Returns',  'NES');
replace into games (name,console_name) values ( 'Battle Chess',  'NES');
replace into games (name,console_name) values ( 'Battle Kid 2: Mountain of Torment (Homebrew)',  'NES');
replace into games (name,console_name) values ( 'Battle Kid 1: Fortress of Peril (Homebrew)',  'NES');
replace into games (name,console_name) values ( 'Battle of Olympus, The',  'NES');
replace into games (name,console_name) values ( 'Battleship',  'NES');
replace into games (name,console_name) values ( 'Battle Tank',  'NES');
replace into games (name,console_name) values ( 'Battletoads',  'NES');
replace into games (name,console_name) values ( 'Battletoads and Double Dragon',  'NES');
replace into games (name,console_name) values ( 'Bee 52 (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Beetlejuice',  'NES');
replace into games (name,console_name) values ( 'Best of the Best: Championship Karate',  'NES');
replace into games (name,console_name) values ( 'Bible Adventures (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Bible Buffet (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Big Birds Hide and Speak',  'NES');
replace into games (name,console_name) values ( 'Bigfoot',  'NES');
replace into games (name,console_name) values ( 'Big Nose Freaks Out (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Big Nose the Caveman (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Bill and Teds Excellent Video Game Adventure',  'NES');
replace into games (name,console_name) values ( 'Bill Elliotts NASCAR Challenge',  'NES');
replace into games (name,console_name) values ( 'Bio Miracle Bokutte Upa',  'NES');
replace into games (name,console_name) values ( 'Bionic Commando',  'NES');
replace into games (name,console_name) values ( 'Black Bass, The',  'NES');
replace into games (name,console_name) values ( 'Blackjack (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Blades of Steel',  'NES');
replace into games (name,console_name) values ( 'Blaster Master',  'NES');
replace into games (name,console_name) values ( 'Blue Marlin, The',  'NES');
replace into games (name,console_name) values ( 'Blues Brothers, The',  'NES');
replace into games (name,console_name) values ( 'Bo Jackson Baseball',  'NES');
replace into games (name,console_name) values ( 'Bomberman',  'NES');
replace into games (name,console_name) values ( 'Bomberman II',  'NES');
replace into games (name,console_name) values ( 'Bonks Adventure',  'NES');
replace into games (name,console_name) values ( 'Boulder Dash',  'NES');
replace into games (name,console_name) values ( 'Boy and His Blob',  'NES');
replace into games (name,console_name) values ( 'BreakThru',  'NES');
replace into games (name,console_name) values ( 'Break Time: The National Pool Tour',  'NES');
replace into games (name,console_name) values ( 'Bubble Bath Babes (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Bubble Bobble',  'NES');
replace into games (name,console_name) values ( 'Bubble Bobble, Part 2',  'NES');
replace into games (name,console_name) values ( 'Bucky OHare',  'NES');
replace into games (name,console_name) values ( 'Bugs Bunny Birthday Blowout',  'NES');
replace into games (name,console_name) values ( 'Bugs Bunny Crazy Castle',  'NES');
replace into games (name,console_name) values ( 'Bump n Jump',  'NES');
replace into games (name,console_name) values ( 'Burai Fighter',  'NES');
replace into games (name,console_name) values ( 'BurgerTime',  'NES');
replace into games (name,console_name) values ( 'Cabal',  'NES');
replace into games (name,console_name) values ( 'Caesars Palace',  'NES');
replace into games (name,console_name) values ( 'California Games',  'NES');
replace into games (name,console_name) values ( 'Caltron 6-in-1 (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Captain America and the Avengers',  'NES');
replace into games (name,console_name) values ( 'Captain Comic: The Adventure (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Captain Planet and the Planeteers',  'NES');
replace into games (name,console_name) values ( 'Captain Skyhawk',  'NES');
replace into games (name,console_name) values ( 'Casino Kid',  'NES');
replace into games (name,console_name) values ( 'Casino Kid II',  'NES');
replace into games (name,console_name) values ( 'Castelian',  'NES');
replace into games (name,console_name) values ( 'Castle of Deceit (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Castle of Dragon',  'NES');
replace into games (name,console_name) values ( 'Castlequest',  'NES');
replace into games (name,console_name) values ( 'Castlevania',  'NES');
replace into games (name,console_name) values ( 'Castlevania II: Simons Quest',  'NES');
replace into games (name,console_name) values ( 'Castlevania III: Draculas Curse',  'NES');
replace into games (name,console_name) values ( 'Caveman Games',  'NES');
replace into games (name,console_name) values ( 'Challenge of the Dragon (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Challenger',  'NES');
replace into games (name,console_name) values ( 'Championship Bowling',  'NES');
replace into games (name,console_name) values ( 'Championship Pool',  'NES');
replace into games (name,console_name) values ( 'Cheetamen II (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Chessmaster, The',  'NES');
replace into games (name,console_name) values ( 'Chiller (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Chubby Cherub',  'NES');
replace into games (name,console_name) values ( 'Chunkout 2 (Homebrew)',  'NES');
replace into games (name,console_name) values ( 'Circus Caper',  'NES');
replace into games (name,console_name) values ( 'City Connection',  'NES');
replace into games (name,console_name) values ( 'Clash at Demonhead',  'NES');
replace into games (name,console_name) values ( 'Classic Concentration',  'NES');
replace into games (name,console_name) values ( 'Cliffhanger',  'NES');
replace into games (name,console_name) values ( 'Clu Clu Land',  'NES');
replace into games (name,console_name) values ( 'Cobra Command',  'NES');
replace into games (name,console_name) values ( 'Cobra Triangle',  'NES');
replace into games (name,console_name) values ( 'Code Name: Viper',  'NES');
replace into games (name,console_name) values ( 'Color A Dinosaur',  'NES');
replace into games (name,console_name) values ( 'Commando',  'NES');
replace into games (name,console_name) values ( 'Conan: The Mysteries of Time',  'NES');
replace into games (name,console_name) values ( 'Conflict',  'NES');
replace into games (name,console_name) values ( 'Conquest of the Crystal Palace',  'NES');
replace into games (name,console_name) values ( 'Contra',  'NES');
replace into games (name,console_name) values ( 'Contra Force',  'NES');
replace into games (name,console_name) values ( 'Cool World',  'NES');
replace into games (name,console_name) values ( 'Cosmic Wars',  'NES');
replace into games (name,console_name) values ( 'Cowboy Kid',  'NES');
replace into games (name,console_name) values ( 'Crash and the Boys Street Challenge',  'NES');
replace into games (name,console_name) values ( 'Crisis Force',  'NES');
replace into games (name,console_name) values ( 'Cross Fire',  'NES');
replace into games (name,console_name) values ( 'Crystalis',  'NES');
replace into games (name,console_name) values ( 'Crystal Mines (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Cyberball',  'NES');
replace into games (name,console_name) values ( 'Cybernoid: The Fighting Machine',  'NES');
replace into games (name,console_name) values ( 'D-Pad Hero 2 (Homebrew)',  'NES');
replace into games (name,console_name) values ( 'Dance Aerobics',  'NES');
replace into games (name,console_name) values ( 'Darkman',  'NES');
replace into games (name,console_name) values ( 'Darkwing Duck',  'NES');
replace into games (name,console_name) values ( 'Dash Galaxy in the Alien Asylum',  'NES');
replace into games (name,console_name) values ( 'Day Dreamin Davey',  'NES');
replace into games (name,console_name) values ( 'Days of Thunder',  'NES');
replace into games (name,console_name) values ( 'Deadly Towers',  'NES');
replace into games (name,console_name) values ( 'Deathbots (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Death Race (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Defender II',  'NES');
replace into games (name,console_name) values ( 'Defender of the Crown',  'NES');
replace into games (name,console_name) values ( 'Defenders of Dynatron City',  'NES');
replace into games (name,console_name) values ( 'Deja Vu',  'NES');
replace into games (name,console_name) values ( 'Demon Sword',  'NES');
replace into games (name,console_name) values ( 'Desert Commander',  'NES');
replace into games (name,console_name) values ( 'Destination Earthstar',  'NES');
replace into games (name,console_name) values ( 'Destiny of an Emperor',  'NES');
replace into games (name,console_name) values ( 'Destiny of an Emperor II',  'NES');
replace into games (name,console_name) values ( 'Devil World',  'NES');
replace into games (name,console_name) values ( 'Dick Tracy',  'NES');
replace into games (name,console_name) values ( 'Die Hard',  'NES');
replace into games (name,console_name) values ( 'Dig Dug',  'NES');
replace into games (name,console_name) values ( 'Dig Dug II: Trouble in Paradise',  'NES');
replace into games (name,console_name) values ( 'Digger T. Rock: Legend of the Lost City',  'NES');
replace into games (name,console_name) values ( 'Dirty Harry',  'NES');
replace into games (name,console_name) values ( 'Adventures in The Magic Kingdom, Disneys',  'NES');
replace into games (name,console_name) values ( 'Donkey Kong',  'NES');
replace into games (name,console_name) values ( 'Donkey Kong 3',  'NES');
replace into games (name,console_name) values ( 'Donkey Kong Classics',  'NES');
replace into games (name,console_name) values ( 'Donkey Kong Jr.',  'NES');
replace into games (name,console_name) values ( 'Donkey Kong Jr. Math',  'NES');
replace into games (name,console_name) values ( 'Double Dare',  'NES');
replace into games (name,console_name) values ( 'Double Dragon',  'NES');
replace into games (name,console_name) values ( 'Double Dragon II: The Revenge',  'NES');
replace into games (name,console_name) values ( 'Double Dragon III: The Sacred Stones',  'NES');
replace into games (name,console_name) values ( 'Double Dribble',  'NES');
replace into games (name,console_name) values ( 'Double Strike (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Dracula, Bram Stokers',  'NES');
replace into games (name,console_name) values ( 'Dragon Fighter',  'NES');
replace into games (name,console_name) values ( 'Dragon Power',  'NES');
replace into games (name,console_name) values ( 'Dragons Lair',  'NES');
replace into games (name,console_name) values ( 'Dragon Spirit: The New Legend',  'NES');
replace into games (name,console_name) values ( 'Dragon Strike',  'NES');
replace into games (name,console_name) values ( 'Dragon Warrior',  'NES');
replace into games (name,console_name) values ( 'Dragon Warrior II',  'NES');
replace into games (name,console_name) values ( 'Dragon Warrior III',  'NES');
replace into games (name,console_name) values ( 'Dragon Warrior IV',  'NES');
replace into games (name,console_name) values ( 'Dr. Chaos',  'NES');
replace into games (name,console_name) values ( 'Dr. Jekyll and Mr. Hyde',  'NES');
replace into games (name,console_name) values ( 'Dr. Mario',  'NES');
replace into games (name,console_name) values ( 'Duck Hunt',  'NES');
replace into games (name,console_name) values ( 'DuckTales',  'NES');
replace into games (name,console_name) values ( 'DuckTales 2',  'NES');
replace into games (name,console_name) values ( 'Dudes with Attitude (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Dungeon Magic: Sword of the Elements',  'NES');
replace into games (name,console_name) values ( 'Dusty Diamond All-Star Softball',  'NES');
replace into games (name,console_name) values ( 'Dynowarz: The Destruction of Spondylus',  'NES');
replace into games (name,console_name) values ( 'Elevator Action',  'NES');
replace into games (name,console_name) values ( 'Eliminator Boat Duel',  'NES');
replace into games (name,console_name) values ( 'Empire Strikes Back, The',  'NES');
replace into games (name,console_name) values ( 'Excitebike',  'NES');
replace into games (name,console_name) values ( 'Exerion II (Prototype)',  'NES');
replace into games (name,console_name) values ( 'Exodus: Journey to the Promised Land (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'F-117A Stealth Fighter',  'NES');
replace into games (name,console_name) values ( 'F-15 City War (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'F-15 Strike Eagle',  'NES');
replace into games (name,console_name) values ( 'F1 Race',  'NES');
replace into games (name,console_name) values ( 'Famicom Wars',  'NES');
replace into games (name,console_name) values ( 'Family Feud',  'NES');
replace into games (name,console_name) values ( 'Fantastic Adventures of Dizzy (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Fantasy Zone (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Faria, A World of Mystery and Danger!',  'NES');
replace into games (name,console_name) values ( 'Fast Break, Magic Johnsons',  'NES');
replace into games (name,console_name) values ( 'Faxanadu',  'NES');
replace into games (name,console_name) values ( 'Felix the Cat',  'NES');
replace into games (name,console_name) values ( 'Ferrari Grand Prix',  'NES');
replace into games (name,console_name) values ( 'Festers Quest',  'NES');
replace into games (name,console_name) values ( 'Fighting Golf, Lee Trevinos',  'NES');
replace into games (name,console_name) values ( 'Final Fantasy',  'NES');
replace into games (name,console_name) values ( 'Fire N Ice',  'NES');
replace into games (name,console_name) values ( 'Firehawk (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Firehouse Rescue, Fisher-Price',  'NES');
replace into games (name,console_name) values ( 'Fist of the North Star',  'NES');
replace into games (name,console_name) values ( 'Flight of the Intruder',  'NES');
replace into games (name,console_name) values ( 'Flintstones: The Rescue of Dino and Hoppy ',  'NES');
replace into games (name,console_name) values ( 'Flintstones: The Surprise at Dinosaur Peak',  'NES');
replace into games (name,console_name) values ( 'Flying Dragon: The Secret Scroll',  'NES');
replace into games (name,console_name) values ( 'Flying Warriors',  'NES');
replace into games (name,console_name) values ( 'Formula One: Built to Win',  'NES');
replace into games (name,console_name) values ( 'Frankenstein: The Monster Returns',  'NES');
replace into games (name,console_name) values ( 'Freedom Force',  'NES');
replace into games (name,console_name) values ( 'Friday The 13th',  'NES');
replace into games (name,console_name) values ( 'Fun House',  'NES');
replace into games (name,console_name) values ( 'Galactic Crusader (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Galaga: Demons of Death',  'NES');
replace into games (name,console_name) values ( 'Galaxian',  'NES');
replace into games (name,console_name) values ( 'Galaxy 5000: Racing in the 51st Century',  'NES');
replace into games (name,console_name) values ( 'Gargoyles Quest II',  'NES');
replace into games (name,console_name) values ( 'Gauntlet (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Gauntlet II',  'NES');
replace into games (name,console_name) values ( 'Gemfire',  'NES');
replace into games (name,console_name) values ( 'Geminim/Siamond (Homebrew)',  'NES');
replace into games (name,console_name) values ( 'GemVenture (Homebrew)',  'NES');
replace into games (name,console_name) values ( 'Genghis Kahn',  'NES');
replace into games (name,console_name) values ( 'George Foremans K.O. Boxing',  'NES');
replace into games (name,console_name) values ( 'Ghosts n Goblins',  'NES');
replace into games (name,console_name) values ( 'Ghostbusters',  'NES');
replace into games (name,console_name) values ( 'Ghostbusters II',  'NES');
replace into games (name,console_name) values ( 'Ghost Lion, Legend of',  'NES');
replace into games (name,console_name) values ( 'Ghoul School',  'NES');
replace into games (name,console_name) values ( 'G.I. Joe: A Real American Hero',  'NES');
replace into games (name,console_name) values ( 'G.I. Joe: The Atlantis Factor',  'NES');
replace into games (name,console_name) values ( 'Gilligans Island',  'NES');
replace into games (name,console_name) values ( 'Glider (Homebrew)',  'NES');
replace into games (name,console_name) values ( 'Goal!',  'NES');
replace into games (name,console_name) values ( 'Goal! Two',  'NES');
replace into games (name,console_name) values ( 'Godzilla: Monster of Monsters!',  'NES');
replace into games (name,console_name) values ( 'Godzilla 2: War of the Monsters',  'NES');
replace into games (name,console_name) values ( 'Gold Medal Challenge 92',  'NES');
replace into games (name,console_name) values ( 'Golf',  'NES');
replace into games (name,console_name) values ( 'Golf Grand Slam',  'NES');
replace into games (name,console_name) values ( 'Golf Challenge Pebble Beach, Bandai',  'NES');
replace into games (name,console_name) values ( 'Golf Power, Greg Normans',  'NES');
replace into games (name,console_name) values ( 'Golgo 13: Top Secret Episode',  'NES');
replace into games (name,console_name) values ( 'Goonies, The',  'NES');
replace into games (name,console_name) values ( 'Goonies II, The',  'NES');
replace into games (name,console_name) values ( 'Gotcha! The Sport!',  'NES');
replace into games (name,console_name) values ( 'Gradius',  'NES');
replace into games (name,console_name) values ( 'Great Waldo Search, The',  'NES');
replace into games (name,console_name) values ( 'Gremlins 2: The New Batch',  'NES');
replace into games (name,console_name) values ( 'Guardian Legend, The',  'NES');
replace into games (name,console_name) values ( 'Guerrilla War',  'NES');
replace into games (name,console_name) values ( 'Gumshoe',  'NES');
replace into games (name,console_name) values ( 'Gun-Nac',  'NES');
replace into games (name,console_name) values ( 'Gun.Smoke',  'NES');
replace into games (name,console_name) values ( 'Gyromite',  'NES');
replace into games (name,console_name) values ( 'Gyruss',  'NES');
replace into games (name,console_name) values ( 'Happy Camper (Prototype)',  'NES');
replace into games (name,console_name) values ( 'Harlem Globetrotters',  'NES');
replace into games (name,console_name) values ( 'Hatris',  'NES');
replace into games (name,console_name) values ( 'Heavy Barrel',  'NES');
replace into games (name,console_name) values ( 'Heavy Shreddin',  'NES');
replace into games (name,console_name) values ( 'Heroes of the Lance',  'NES');
replace into games (name,console_name) values ( 'High Speed',  'NES');
replace into games (name,console_name) values ( 'Hillsfar',  'NES');
replace into games (name,console_name) values ( 'Hogans Alley',  'NES');
replace into games (name,console_name) values ( 'Hollywood Squares',  'NES');
replace into games (name,console_name) values ( 'Home Alone',  'NES');
replace into games (name,console_name) values ( 'Home Alone 2: Lost in New York',  'NES');
replace into games (name,console_name) values ( 'Hook',  'NES');
replace into games (name,console_name) values ( 'Hoops',  'NES');
replace into games (name,console_name) values ( 'Hot Slots (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Hudson Hawk',  'NES');
replace into games (name,console_name) values ( 'Hunt for Red October, The',  'NES');
replace into games (name,console_name) values ( 'Hydlide',  'NES');
replace into games (name,console_name) values ( 'I Can Remember - Fisher-Price',  'NES');
replace into games (name,console_name) values ( 'Ice Climber',  'NES');
replace into games (name,console_name) values ( 'Ice Hockey',  'NES');
replace into games (name,console_name) values ( 'Ikari Warriors',  'NES');
replace into games (name,console_name) values ( 'Ikari Warriors II: Victory Road',  'NES');
replace into games (name,console_name) values ( 'Ikari III: The Rescue',  'NES');
replace into games (name,console_name) values ( 'Image Fight',  'NES');
replace into games (name,console_name) values ( 'Immortal, The',  'NES');
replace into games (name,console_name) values ( 'Impossible Mission II',  'NES');
replace into games (name,console_name) values ( 'Incredible Crash Dummies, The',  'NES');
replace into games (name,console_name) values ( 'Indiana Jones and the Last Crusade (Taito)',  'NES');
replace into games (name,console_name) values ( 'Indiana Jones and the Last Crusade: The Action Game (UBI Soft)',  'NES');
replace into games (name,console_name) values ( 'Indiana Jones and the Temple of Doom (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Indy Heat, Danny Sullivans',  'NES');
replace into games (name,console_name) values ( 'Infiltrator',  'NES');
replace into games (name,console_name) values ( 'Iron Tank: The Invasion of Normandy',  'NES');
replace into games (name,console_name) values ( 'Isolated Warrior',  'NES');
replace into games (name,console_name) values ( 'Jackal',  'NES');
replace into games (name,console_name) values ( 'Jackie Chans Action Kung Fu',  'NES');
replace into games (name,console_name) values ( 'Jack Nicklaus Major Championship Golf',  'NES');
replace into games (name,console_name) values ( 'James Bond Jr.',  'NES');
replace into games (name,console_name) values ( 'Jaws',  'NES');
replace into games (name,console_name) values ( 'Jeopardy!',  'NES');
replace into games (name,console_name) values ( 'Jeopardy! 25th Anniversary',  'NES');
replace into games (name,console_name) values ( 'Jeopardy! Jr.',  'NES');
replace into games (name,console_name) values ( 'Jeopardy! Super',  'NES');
replace into games (name,console_name) values ( 'Jetsons: Cogswells Caper',  'NES');
replace into games (name,console_name) values ( 'Jimmy Connors Pro Tennis Tour',  'NES');
replace into games (name,console_name) values ( 'Joe and Mac',  'NES');
replace into games (name,console_name) values ( 'Jordan vs. Bird: One on One',  'NES');
replace into games (name,console_name) values ( 'Joshua and The Battle of Jericho (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Journey to Silius',  'NES');
replace into games (name,console_name) values ( 'Joust',  'NES');
replace into games (name,console_name) values ( 'Jungle Book, The',  'NES');
replace into games (name,console_name) values ( 'Jurassic Park',  'NES');
replace into games (name,console_name) values ( 'Kabuki: Quantum Fighter',  'NES');
replace into games (name,console_name) values ( 'Karate Champ',  'NES');
replace into games (name,console_name) values ( 'Karate Kid, The',  'NES');
replace into games (name,console_name) values ( 'Karnov',  'NES');
replace into games (name,console_name) values ( 'Kickle Cubicle',  'NES');
replace into games (name,console_name) values ( 'Kickmaster',  'NES');
replace into games (name,console_name) values ( 'Kid Icarus',  'NES');
replace into games (name,console_name) values ( 'Kid Klown in Night Mayor World',  'NES');
replace into games (name,console_name) values ( 'Kid Kool and the Quest for the Seven Wonder Herbs',  'NES');
replace into games (name,console_name) values ( 'Kid Niki: Radical Ninja',  'NES');
replace into games (name,console_name) values ( 'King Neptunes Adventure (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'King of Kings: The Early Years (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'King of the Ring - WWF',  'NES');
replace into games (name,console_name) values ( 'Kings Knight',  'NES');
replace into games (name,console_name) values ( 'Kings of the Beach',  'NES');
replace into games (name,console_name) values ( 'Kings Quest V',  'NES');
replace into games (name,console_name) values ( 'Kirbys Adventure',  'NES');
replace into games (name,console_name) values ( 'Kiwi Kraze',  'NES');
replace into games (name,console_name) values ( 'KlashBall',  'NES');
replace into games (name,console_name) values ( 'Klax (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Knight Rider',  'NES');
replace into games (name,console_name) values ( 'Krazy Kreatures (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Krion Conquest, The',  'NES');
replace into games (name,console_name) values ( 'Krustys Fun House',  'NES');
replace into games (name,console_name) values ( 'Kung Fu',  'NES');
replace into games (name,console_name) values ( 'Kung Fu Heroes',  'NES');
replace into games (name,console_name) values ( 'Laser Invasion',  'NES');
replace into games (name,console_name) values ( 'Last Action Hero',  'NES');
replace into games (name,console_name) values ( 'Last Ninja, The',  'NES');
replace into games (name,console_name) values ( 'Last Starfighter, The',  'NES');
replace into games (name,console_name) values ( 'Legacy of the Wizard',  'NES');
replace into games (name,console_name) values ( 'Legendary Wings',  'NES');
replace into games (name,console_name) values ( 'Legend of Kage, The',  'NES');
replace into games (name,console_name) values ( 'Legend of Zelda, The',  'NES');
replace into games (name,console_name) values ( 'Legends of the Diamond',  'NES');
replace into games (name,console_name) values ( 'Lemmings',  'NES');
replace into games (name,console_name) values ( 'LEmpereur',  'NES');
replace into games (name,console_name) values ( 'Lethal Weapon',  'NES');
replace into games (name,console_name) values ( 'Life Force',  'NES');
replace into games (name,console_name) values ( 'Linus Spaceheads Cosmic Crusade (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Little League Baseball: Championship Series',  'NES');
replace into games (name,console_name) values ( 'Little Mermaid, The',  'NES');
replace into games (name,console_name) values ( 'Little Nemo: The Dream Master',  'NES');
replace into games (name,console_name) values ( 'Little Ninja Brothers',  'NES');
replace into games (name,console_name) values ( 'Little Samson',  'NES');
replace into games (name,console_name) values ( 'Lode Runner',  'NES');
replace into games (name,console_name) values ( 'Lone Ranger, The',  'NES');
replace into games (name,console_name) values ( 'Loop',  'NES');
replace into games (name,console_name) values ( 'Low G Man: The Low Gravity Man',  'NES');
replace into games (name,console_name) values ( 'Lunar Pool',  'NES');
replace into games (name,console_name) values ( 'Mach Rider',  'NES');
replace into games (name,console_name) values ( 'Mad Max',  'NES');
replace into games (name,console_name) values ( 'Mafat Conspiracy, The',  'NES');
replace into games (name,console_name) values ( 'Magic Darts',  'NES');
replace into games (name,console_name) values ( 'Magician',  'NES');
replace into games (name,console_name) values ( 'Magic of Scheherazade, The',  'NES');
replace into games (name,console_name) values ( 'Magmax',  'NES');
replace into games (name,console_name) values ( 'Major League Baseball',  'NES');
replace into games (name,console_name) values ( 'Maniac Mansion',  'NES');
replace into games (name,console_name) values ( 'Mappy-Land',  'NES');
replace into games (name,console_name) values ( 'Marble Madness',  'NES');
replace into games (name,console_name) values ( 'Mario Bros.',  'NES');
replace into games (name,console_name) values ( 'Mario Is Missing!',  'NES');
replace into games (name,console_name) values ( 'Marios Time Machine',  'NES');
replace into games (name,console_name) values ( 'Master Chu and the Drunkard Hu (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Maxi 15 (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'M.C. Kids',  'NES');
replace into games (name,console_name) values ( 'Mechanized Attack',  'NES');
replace into games (name,console_name) values ( 'Mega Man',  'NES');
replace into games (name,console_name) values ( 'Mega Man 2',  'NES');
replace into games (name,console_name) values ( 'Mega Man 3',  'NES');
replace into games (name,console_name) values ( 'Mega Man 4',  'NES');
replace into games (name,console_name) values ( 'Mega Man 5',  'NES');
replace into games (name,console_name) values ( 'Mega Man 6',  'NES');
replace into games (name,console_name) values ( 'Menace Beach (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Mendel Palace',  'NES');
replace into games (name,console_name) values ( 'Mermaids of Atlantis (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Metal Fighter (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Metal Gear',  'NES');
replace into games (name,console_name) values ( 'Metal Mech: Man and Machine',  'NES');
replace into games (name,console_name) values ( 'Metal Storm',  'NES');
replace into games (name,console_name) values ( 'Metroid',  'NES');
replace into games (name,console_name) values ( 'Michael Andrettis World GP',  'NES');
replace into games (name,console_name) values ( 'Mickey Mousecapade',  'NES');
replace into games (name,console_name) values ( 'Mickeys Adventure in Numberland',  'NES');
replace into games (name,console_name) values ( 'Mickeys Safari in Letterland',  'NES');
replace into games (name,console_name) values ( 'Micro Machines (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Mig 29 Soviet Fighter (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Might and Magic: Secret of the Inner Sanctum',  'NES');
replace into games (name,console_name) values ( 'Mighty Bomb Jack',  'NES');
replace into games (name,console_name) values ( 'Mighty Final Fight',  'NES');
replace into games (name,console_name) values ( 'Mike Ditkas Big Play Football (Prototype)',  'NES');
replace into games (name,console_name) values ( 'Mike Tysons Intergalactic Power Punch (Prototype)',  'NES');
replace into games (name,console_name) values ( 'Mike Tysons Punch-Out!!',  'NES');
replace into games (name,console_name) values ( 'Millipede',  'NES');
replace into games (name,console_name) values ( 'Milons Secret Castle',  'NES');
replace into games (name,console_name) values ( 'Miracle Piano Teaching System',  'NES');
replace into games (name,console_name) values ( 'Mission Cobra (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Mission: Impossible',  'NES');
replace into games (name,console_name) values ( 'Monopoly',  'NES');
replace into games (name,console_name) values ( 'Monster in my Pocket',  'NES');
replace into games (name,console_name) values ( 'Monster Party',  'NES');
replace into games (name,console_name) values ( 'Monster Truck Rally',  'NES');
replace into games (name,console_name) values ( 'Moon Ranger (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Motor City Patrol',  'NES');
replace into games (name,console_name) values ( 'Mr. Gimmick!',  'NES');
replace into games (name,console_name) values ( 'Ms. Pac-Man (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'M.U.L.E.',  'NES');
replace into games (name,console_name) values ( 'Muppet Adventure: Chaos at the Carnival',  'NES');
replace into games (name,console_name) values ( 'M.U.S.C.L.E.',  'NES');
replace into games (name,console_name) values ( 'Mutant Virus: Crisis in a Computer World',  'NES');
replace into games (name,console_name) values ( 'Myriad 6-in-1 (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Mystery Quest',  'NES');
replace into games (name,console_name) values ( 'Mystic Pillars (Homebrew)',  'NES');
replace into games (name,console_name) values ( 'NARC',  'NES');
replace into games (name,console_name) values ( 'Nekketsu Kakuto Densetsu',  'NES');
replace into games (name,console_name) values ( 'NES Open Tournament Golf',  'NES');
replace into games (name,console_name) values ( 'New Ghostbusters 2',  'NES');
replace into games (name,console_name) values ( 'NFL Football',  'NES');
replace into games (name,console_name) values ( 'Nigel Mansells World Championship Racing',  'NES');
replace into games (name,console_name) values ( 'Nightmare on Elm Street',  'NES');
replace into games (name,console_name) values ( 'Nightshade',  'NES');
replace into games (name,console_name) values ( 'Ninja Crusaders',  'NES');
replace into games (name,console_name) values ( 'Ninja Gaiden',  'NES');
replace into games (name,console_name) values ( 'Ninja Gaiden II: The Dark Sword of Chaos',  'NES');
replace into games (name,console_name) values ( 'Ninja Gaiden III: The Ancient Ship of Doom',  'NES');
replace into games (name,console_name) values ( 'Ninja JaJaMaru-kun',  'NES');
replace into games (name,console_name) values ( 'Ninja Kid',  'NES');
replace into games (name,console_name) values ( 'Nobunagas Ambition',  'NES');
replace into games (name,console_name) values ( 'Nobunagas Ambition II',  'NES');
replace into games (name,console_name) values ( 'North and South',  'NES');
replace into games (name,console_name) values ( 'Nuts and Milk',  'NES');
replace into games (name,console_name) values ( 'Operation Secret Storm (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Operation Wolf',  'NES');
replace into games (name,console_name) values ( 'ORB-3D',  'NES');
replace into games (name,console_name) values ( 'Othello',  'NES');
replace into games (name,console_name) values ( 'Over Horizon',  'NES');
replace into games (name,console_name) values ( 'Overlord',  'NES');
replace into games (name,console_name) values ( 'Pac-Man (Tengen) (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Pac-Mania (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Palamedes',  'NES');
replace into games (name,console_name) values ( 'Panic Restaurant',  'NES');
replace into games (name,console_name) values ( 'Paperboy',  'NES');
replace into games (name,console_name) values ( 'Paperboy 2',  'NES');
replace into games (name,console_name) values ( 'Parodius Da!',  'NES');
replace into games (name,console_name) values ( 'Peek-A-Boo Poker (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Perfect Fit - Fisher-Price',  'NES');
replace into games (name,console_name) values ( 'Pesterminator: The Western Exterminator (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Peter Pan and The Pirates',  'NES');
replace into games (name,console_name) values ( 'Phantom Fighter',  'NES');
replace into games (name,console_name) values ( 'Pictionary',  'NES');
replace into games (name,console_name) values ( 'Pinball',  'NES');
replace into games (name,console_name) values ( 'Pinball Quest',  'NES');
replace into games (name,console_name) values ( 'Pin*Bot',  'NES');
replace into games (name,console_name) values ( 'Pipe Dream',  'NES');
replace into games (name,console_name) values ( 'Pirates!',  'NES');
replace into games (name,console_name) values ( 'Platoon',  'NES');
replace into games (name,console_name) values ( 'Play Action Football',  'NES');
replace into games (name,console_name) values ( 'Pool of Radiance',  'NES');
replace into games (name,console_name) values ( 'Popeye',  'NES');
replace into games (name,console_name) values ( 'P.O.W.: Prisoners of War',  'NES');
replace into games (name,console_name) values ( 'Power Blade',  'NES');
replace into games (name,console_name) values ( 'Power Blade 2',  'NES');
replace into games (name,console_name) values ( 'Power Punch II',  'NES');
replace into games (name,console_name) values ( 'Pradikus Conflict (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Predator: Soon the Hunt Will Begin',  'NES');
replace into games (name,console_name) values ( 'Prince of Persia',  'NES');
replace into games (name,console_name) values ( 'Princess Tomato in the Salad Kingdom',  'NES');
replace into games (name,console_name) values ( 'Pro Sport Hockey',  'NES');
replace into games (name,console_name) values ( 'Pro Wrestling',  'NES');
replace into games (name,console_name) values ( 'Pugsleys Scavenger Hunt',  'NES');
replace into games (name,console_name) values ( 'Punch-Out!!',  'NES');
replace into games (name,console_name) values ( 'Punisher, The',  'NES');
replace into games (name,console_name) values ( 'Puss N Boots: Peros Great Adventure',  'NES');
replace into games (name,console_name) values ( 'Puzzle (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Puzznic',  'NES');
replace into games (name,console_name) values ( 'Pyramid (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Q*Bert',  'NES');
replace into games (name,console_name) values ( 'Qix',  'NES');
replace into games (name,console_name) values ( 'Quarterback, John Elways',  'NES');
replace into games (name,console_name) values ( 'Quattro Adventure (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Quattro Arcade (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Quattro Sports (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Race America, Alex DeMeos',  'NES');
replace into games (name,console_name) values ( 'Racket Attack',  'NES');
replace into games (name,console_name) values ( 'Rad Gravity, The Adventures of',  'NES');
replace into games (name,console_name) values ( 'Rad Racer',  'NES');
replace into games (name,console_name) values ( 'Rad Racer II',  'NES');
replace into games (name,console_name) values ( 'Rad Racket: Deluxe Tennis II (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Raid 2020 (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Raid on Bungeling Bay',  'NES');
replace into games (name,console_name) values ( 'Rainbow Islands',  'NES');
replace into games (name,console_name) values ( 'Rally Bike',  'NES');
replace into games (name,console_name) values ( 'Rambo',  'NES');
replace into games (name,console_name) values ( 'Rampage',  'NES');
replace into games (name,console_name) values ( 'Rampart',  'NES');
replace into games (name,console_name) values ( 'R.B.I. Baseball (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'R.B.I. Baseball 2 (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'R.B.I. Baseball 3 (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'R.C. Pro-Am',  'NES');
replace into games (name,console_name) values ( 'R.C. Pro Am II',  'NES');
replace into games (name,console_name) values ( 'Remote Control',  'NES');
replace into games (name,console_name) values ( 'The Ren and Stimpy Show: Buckeroos',  'NES');
replace into games (name,console_name) values ( 'Renegade',  'NES');
replace into games (name,console_name) values ( 'Rescue: The Embassy Mission',  'NES');
replace into games (name,console_name) values ( 'Rescue Rangers, Chip n Dale',  'NES');
replace into games (name,console_name) values ( 'Rescue Rangers 2, Chip n Dale',  'NES');
replace into games (name,console_name) values ( 'Ring King',  'NES');
replace into games (name,console_name) values ( 'River City Ransom',  'NES');
replace into games (name,console_name) values ( 'RoadBlasters',  'NES');
replace into games (name,console_name) values ( 'Road Runner (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Robin Hood: Prince of Thieves',  'NES');
replace into games (name,console_name) values ( 'RoboCop',  'NES');
replace into games (name,console_name) values ( 'RoboCop 2',  'NES');
replace into games (name,console_name) values ( 'RoboCop 3',  'NES');
replace into games (name,console_name) values ( 'RoboDemons (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'RoboWarrior',  'NES');
replace into games (name,console_name) values ( 'Rocketeer, The',  'NES');
replace into games (name,console_name) values ( 'Rocket Ranger',  'NES');
replace into games (name,console_name) values ( 'Rockin Kats',  'NES');
replace into games (name,console_name) values ( 'Rock n Ball',  'NES');
replace into games (name,console_name) values ( 'Rocky and Bullwinkle and Friends',  'NES');
replace into games (name,console_name) values ( 'Rod Land',  'NES');
replace into games (name,console_name) values ( 'Roger Clemens MVP Baseball',  'NES');
replace into games (name,console_name) values ( 'Rollerball',  'NES');
replace into games (name,console_name) values ( 'Rollerblade Racer',  'NES');
replace into games (name,console_name) values ( 'Rollergames',  'NES');
replace into games (name,console_name) values ( 'Rolling Thunder (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Romance of the Three Kingdoms',  'NES');
replace into games (name,console_name) values ( 'Romance of the Three Kingdoms II',  'NES');
replace into games (name,console_name) values ( 'Roundball: 2-on-2 Challenge',  'NES');
replace into games (name,console_name) values ( 'Rushn Attack',  'NES');
replace into games (name,console_name) values ( 'Rygar',  'NES');
replace into games (name,console_name) values ( 'Sara Parkers Pool Challenge (Prototype)',  'NES');
replace into games (name,console_name) values ( 'S.C.A.T.: Special Cybernetic Attack Team',  'NES');
replace into games (name,console_name) values ( 'Secret Scout in the Temple of Demise (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Section Z',  'NES');
replace into games (name,console_name) values ( 'Seicross',  'NES');
replace into games (name,console_name) values ( 'Sesame Street 123',  'NES');
replace into games (name,console_name) values ( 'Sesame Street ABC',  'NES');
replace into games (name,console_name) values ( 'Sesame Street Countdown',  'NES');
replace into games (name,console_name) values ( 'Shadowgate',  'NES');
replace into games (name,console_name) values ( 'Shadow of the Ninja',  'NES');
replace into games (name,console_name) values ( 'Shatterhand',  'NES');
replace into games (name,console_name) values ( 'Shingen the Ruler',  'NES');
replace into games (name,console_name) values ( 'Shinobi (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Shockwave (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Shooting Range',  'NES');
replace into games (name,console_name) values ( 'Short Order / Eggsplode!',  'NES');
replace into games (name,console_name) values ( 'Side Pocket',  'NES');
replace into games (name,console_name) values ( 'Silent Assault (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Silent Service',  'NES');
replace into games (name,console_name) values ( 'Silk Worm',  'NES');
replace into games (name,console_name) values ( 'Silver Surfer',  'NES');
replace into games (name,console_name) values ( 'Simpsons, The: Bartman Meets Radioactive Man',  'NES');
replace into games (name,console_name) values ( 'Simpsons, The: Bart vs. the Space Mutants',  'NES');
replace into games (name,console_name) values ( 'Simpsons, The: Bart vs. the World',  'NES');
replace into games (name,console_name) values ( 'Skate or Die',  'NES');
replace into games (name,console_name) values ( 'Skate Or Die 2: The Search for Double Trouble',  'NES');
replace into games (name,console_name) values ( 'Ski or Die',  'NES');
replace into games (name,console_name) values ( 'Skull and Crossbones (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Sky Kid',  'NES');
replace into games (name,console_name) values ( 'Sky Shark',  'NES');
replace into games (name,console_name) values ( 'Slalom',  'NES');
replace into games (name,console_name) values ( 'Smash T.V.',  'NES');
replace into games (name,console_name) values ( 'Snake Rattle and Roll',  'NES');
replace into games (name,console_name) values ( 'Snakes Revenge',  'NES');
replace into games (name,console_name) values ( 'Snoopys Silly Sports Spectacular',  'NES');
replace into games (name,console_name) values ( 'Snow Brothers',  'NES');
replace into games (name,console_name) values ( 'Soccer',  'NES');
replace into games (name,console_name) values ( 'Solar Jetman: Hunt for the Golden Warpship',  'NES');
replace into games (name,console_name) values ( 'Solitaire (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Solomons Key',  'NES');
replace into games (name,console_name) values ( 'Solstice: Quest for the Staff of Demnos',  'NES');
replace into games (name,console_name) values ( 'Space Shuttle Project',  'NES');
replace into games (name,console_name) values ( 'Spelunker',  'NES');
replace into games (name,console_name) values ( 'Spider-Man: Return of the Sinister Six',  'NES');
replace into games (name,console_name) values ( 'Spiritual Warfare (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Splatterhouse: Wanpaku Graffiti',  'NES');
replace into games (name,console_name) values ( 'Spot',  'NES');
replace into games (name,console_name) values ( 'Spy Hunter',  'NES');
replace into games (name,console_name) values ( 'Spy vs. Spy',  'NES');
replace into games (name,console_name) values ( 'Sqoon',  'NES');
replace into games (name,console_name) values ( 'Stack Up',  'NES');
replace into games (name,console_name) values ( 'Stadium Events',  'NES');
replace into games (name,console_name) values ( 'Stanley: The Search for Dr. Livingston',  'NES');
replace into games (name,console_name) values ( 'Star Force',  'NES');
replace into games (name,console_name) values ( 'Starship Hector',  'NES');
replace into games (name,console_name) values ( 'Star Soldier',  'NES');
replace into games (name,console_name) values ( 'Star Trek: 25th Anniversary',  'NES');
replace into games (name,console_name) values ( 'Star Trek: The Next Generation',  'NES');
replace into games (name,console_name) values ( 'StarTropics',  'NES');
replace into games (name,console_name) values ( 'StarTropics II: Zodas Revenge',  'NES');
replace into games (name,console_name) values ( 'Star Voyager',  'NES');
replace into games (name,console_name) values ( 'Star Wars',  'NES');
replace into games (name,console_name) values ( 'Stealth ATF',  'NES');
replace into games (name,console_name) values ( 'Stinger',  'NES');
replace into games (name,console_name) values ( 'Street Cop',  'NES');
replace into games (name,console_name) values ( 'Street Fighter 2010: The Final Fight',  'NES');
replace into games (name,console_name) values ( 'Strider',  'NES');
replace into games (name,console_name) values ( 'Stunt Kids (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Sudoku 2007 (Homebrew)',  'NES');
replace into games (name,console_name) values ( 'Sunday Funday: The Ride (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Super C',  'NES');
replace into games (name,console_name) values ( 'Super Cars',  'NES');
replace into games (name,console_name) values ( 'Super Dodge Ball',  'NES');
replace into games (name,console_name) values ( 'Super Glove Ball',  'NES');
replace into games (name,console_name) values ( 'Superman',  'NES');
replace into games (name,console_name) values ( 'Super Mario Bros.',  'NES');
replace into games (name,console_name) values ( 'Super Mario Bros. 2',  'NES');
replace into games (name,console_name) values ( 'Super Mario Bros. 2 - The Lost Levels',  'NES');
replace into games (name,console_name) values ( 'Super Mario Bros. 3',  'NES');
replace into games (name,console_name) values ( 'Super NeSnake 2 (Homebrew)',  'NES');
replace into games (name,console_name) values ( 'Super Off Road',  'NES');
replace into games (name,console_name) values ( 'Super Pitfall',  'NES');
replace into games (name,console_name) values ( 'Super Spike V-Ball',  'NES');
replace into games (name,console_name) values ( 'Super Sprint (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Super Spy Hunter',  'NES');
replace into games (name,console_name) values ( 'Super Team Games',  'NES');
replace into games (name,console_name) values ( 'Swamp Thing',  'NES');
replace into games (name,console_name) values ( 'Sword Master',  'NES');
replace into games (name,console_name) values ( 'Swords and Serpents',  'NES');
replace into games (name,console_name) values ( 'Taboo: The Sixth Sense',  'NES');
replace into games (name,console_name) values ( 'Tagin Dragon (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Tag Team Wrestling',  'NES');
replace into games (name,console_name) values ( 'TaleSpin',  'NES');
replace into games (name,console_name) values ( 'T and C Surf Designs: Wood and Water Rage',  'NES');
replace into games (name,console_name) values ( 'Target: Renegade',  'NES');
replace into games (name,console_name) values ( 'Tecmo Baseball',  'NES');
replace into games (name,console_name) values ( 'Tecmo NBA Basketball',  'NES');
replace into games (name,console_name) values ( 'Tecmo Bowl',  'NES');
replace into games (name,console_name) values ( 'Tecmo Cup Soccer Game',  'NES');
replace into games (name,console_name) values ( 'Tecmo Super Bowl',  'NES');
replace into games (name,console_name) values ( 'Tecmo World Wrestling',  'NES');
replace into games (name,console_name) values ( 'Teenage Mutant Ninja Turtles',  'NES');
replace into games (name,console_name) values ( 'TMNT II: The Arcade Game',  'NES');
replace into games (name,console_name) values ( 'TMNT III: The Manhattan Project',  'NES');
replace into games (name,console_name) values ( 'TMNT: Tournament Fighters',  'NES');
replace into games (name,console_name) values ( 'Tengen Tetris (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Tennis',  'NES');
replace into games (name,console_name) values ( 'Terminator, The',  'NES');
replace into games (name,console_name) values ( 'Terminator 2: Judgement Day',  'NES');
replace into games (name,console_name) values ( 'Terra Cresta',  'NES');
replace into games (name,console_name) values ( 'Tetra Star: The Fighter',  'NES');
replace into games (name,console_name) values ( 'Tetris',  'NES');
replace into games (name,console_name) values ( 'Tetris 2',  'NES');
replace into games (name,console_name) values ( 'Three Stooges, The',  'NES');
replace into games (name,console_name) values ( 'Thrillas Surfari - T and C II',  'NES');
replace into games (name,console_name) values ( 'Thunder and Lightning',  'NES');
replace into games (name,console_name) values ( 'Thunderbirds',  'NES');
replace into games (name,console_name) values ( 'Thundercade',  'NES');
replace into games (name,console_name) values ( 'Tic-Tac XO (Homebrew)',  'NES');
replace into games (name,console_name) values ( 'Tiger-Heli',  'NES');
replace into games (name,console_name) values ( 'Tiles of Fate (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Time Lord',  'NES');
replace into games (name,console_name) values ( 'Times of Lore',  'NES');
replace into games (name,console_name) values ( 'Tiny Toon Adventures',  'NES');
replace into games (name,console_name) values ( 'Tiny Toon Adventures 2: Trouble in Wackyland',  'NES');
replace into games (name,console_name) values ( 'Tiny Toon Adventures: Cartoon Workshop',  'NES');
replace into games (name,console_name) values ( 'Toki',  'NES');
replace into games (name,console_name) values ( 'Tom and Jerry',  'NES');
replace into games (name,console_name) values ( 'Tombs and Treasure',  'NES');
replace into games (name,console_name) values ( 'Toobin (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Top Gun',  'NES');
replace into games (name,console_name) values ( 'Top Gun: The Second Mission',  'NES');
replace into games (name,console_name) values ( 'Top Players Tennis - Chris Evert and Ivan Lendl',  'NES');
replace into games (name,console_name) values ( 'Totally Rad',  'NES');
replace into games (name,console_name) values ( 'Total Recall',  'NES');
replace into games (name,console_name) values ( 'To The Earth',  'NES');
replace into games (name,console_name) values ( 'Touchdown Fever',  'NES');
replace into games (name,console_name) values ( 'Toxic Crusaders',  'NES');
replace into games (name,console_name) values ( 'Track and Field',  'NES');
replace into games (name,console_name) values ( 'Track and Field II',  'NES');
replace into games (name,console_name) values ( 'Treasure Master',  'NES');
replace into games (name,console_name) values ( 'Trick Shooting, Barker Bills',  'NES');
replace into games (name,console_name) values ( 'Trog!',  'NES');
replace into games (name,console_name) values ( 'Trojan',  'NES');
replace into games (name,console_name) values ( 'Trolls on Treasure Island (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Twin Cobra',  'NES');
replace into games (name,console_name) values ( 'Twin Eagle',  'NES');
replace into games (name,console_name) values ( 'Ufouria: The Saga',  'NES');
replace into games (name,console_name) values ( 'Ultima III: Exodus',  'NES');
replace into games (name,console_name) values ( 'Ultima IV: Quest of The Avatar',  'NES');
replace into games (name,console_name) values ( 'Ultima V: Warriors of Destiny',  'NES');
replace into games (name,console_name) values ( 'Ultimate Air Combat',  'NES');
replace into games (name,console_name) values ( 'Ultimate Basketball',  'NES');
replace into games (name,console_name) values ( 'Ultimate Frogger Champion (Homebrew)',  'NES');
replace into games (name,console_name) values ( 'Ultimate League Soccer (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Ultimate Stuntman, The (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Uncharted Waters',  'NES');
replace into games (name,console_name) values ( 'Uninvited',  'NES');
replace into games (name,console_name) values ( 'Untouchables, The',  'NES');
replace into games (name,console_name) values ( 'Urban Champion',  'NES');
replace into games (name,console_name) values ( 'Vegas Dream',  'NES');
replace into games (name,console_name) values ( 'Venice Beach Volleyball (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Vice: Project Doom',  'NES');
replace into games (name,console_name) values ( 'Videomation',  'NES');
replace into games (name,console_name) values ( 'Vindicators (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Volleyball',  'NES');
replace into games (name,console_name) values ( 'Wacky Races',  'NES');
replace into games (name,console_name) values ( 'Wall Street Kid',  'NES');
replace into games (name,console_name) values ( 'Wally Bear and the NO! Gang (Unlicensed)',  'NES');
replace into games (name,console_name) values ( 'Warios Woods',  'NES');
replace into games (name,console_name) values ( 'Wayne Gretzky Hockey',  'NES');
replace into games (name,console_name) values ( 'Waynes World',  'NES');
replace into games (name,console_name) values ( 'Werewolf: The Last Warrior',  'NES');
replace into games (name,console_name) values ( 'Wheel of Fortune',  'NES');
replace into games (name,console_name) values ( 'Wheel of Fortune: Family Edition',  'NES');
replace into games (name,console_name) values ( 'Wheel of Fortune: Junior Edition',  'NES');
replace into games (name,console_name) values ( 'Wheel of Fortune: Featuring Vanna White',  'NES');
replace into games (name,console_name) values ( 'Where in Time is Carmen San Diego?',  'NES');
replace into games (name,console_name) values ( 'Wheres Waldo?',  'NES');
replace into games (name,console_name) values ( 'Who Framed Roger Rabbit?',  'NES');
replace into games (name,console_name) values ( 'Whomp Em',  'NES');
replace into games (name,console_name) values ( 'Widget',  'NES');
replace into games (name,console_name) values ( 'Wild Gunman',  'NES');
replace into games (name,console_name) values ( 'Willow',  'NES');
replace into games (name,console_name) values ( 'Win, Lose or Draw',  'NES');
replace into games (name,console_name) values ( 'Winter Games',  'NES');
replace into games (name,console_name) values ( 'Wizardry: Proving Grounds of the Mad Overlord',  'NES');
replace into games (name,console_name) values ( 'Wizardry: Knight of Diamonds',  'NES');
replace into games (name,console_name) values ( 'Wizards and Warriors',  'NES');
replace into games (name,console_name) values ( 'Wizards and Warriors II: Ironsword',  'NES');
replace into games (name,console_name) values ( 'Wizards and Warriors III: Kuros, Visions of Power',  'NES');
replace into games (name,console_name) values ( 'Wolverine',  'NES');
replace into games (name,console_name) values ( 'World Champ',  'NES');
replace into games (name,console_name) values ( 'WCW World Championship Wrestling',  'NES');
replace into games (name,console_name) values ( 'World Class Track Meet',  'NES');
replace into games (name,console_name) values ( 'World Cup',  'NES');
replace into games (name,console_name) values ( 'World Games',  'NES');
replace into games (name,console_name) values ( 'Wrath of the Black Manta',  'NES');
replace into games (name,console_name) values ( 'Wrecking Crew',  'NES');
replace into games (name,console_name) values ( 'WWF Wrestlemania',  'NES');
replace into games (name,console_name) values ( 'WWF Wrestlemania Challenge',  'NES');
replace into games (name,console_name) values ( 'WWF Wrestlemania Steel Cage Challenge',  'NES');
replace into games (name,console_name) values ( 'Wurm: Journey to the Center of the Earth',  'NES');
replace into games (name,console_name) values ( 'Xenophobe',  'NES');
replace into games (name,console_name) values ( 'Xevious',  'NES');
replace into games (name,console_name) values ( 'XEXYZ',  'NES');
replace into games (name,console_name) values ( 'X-Men, The Uncanny',  'NES');
replace into games (name,console_name) values ( 'Yie Ar Kung-Fu',  'NES');
replace into games (name,console_name) values ( 'Yo! Noid',  'NES');
replace into games (name,console_name) values ( 'Yoshi',  'NES');
replace into games (name,console_name) values ( 'Yoshis Cookie',  'NES');
replace into games (name,console_name) values ( 'Young Indiana Jones Chronicles, The',  'NES');
replace into games (name,console_name) values ( 'Zanac',  'NES');
replace into games (name,console_name) values ( 'Zelda II: The Adventure of Link',  'NES');
replace into games (name,console_name) values ( 'Zen: Intergalactic Ninja',  'NES');
replace into games (name,console_name) values ( 'Zombie Nation',  'NES');
