replace into games (name, publisher, year, console_name) values ("32 in 1","Atari","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Ace of Aces","Accolade","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Alien Brigade","Atari","1990","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Armor Attack II (aftermarket)","Robert DeCrescenzo","2013","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Asteroids","Atari","1987","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Asteroids Deluxe (aftermarket)","Atari","2007","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Astro Blaster (aftermarket)","Robert DeCrescenzo","2014","Atari 7800");
replace into games (name, publisher, year, console_name) values ("B*nQ (aftermarket)","Ken Siders","2007","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Ballblazer","Lucasfilm Ltd.","1987","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Barnyard Blaster","Atari","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Basketbrawl","Atari","1990","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Beef Drop (aftermarket)","Ken Siders","2006","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Centipede","Atari","1987","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Choplifter!","Brøderbund","1987","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Combat 1990 (aftermarket)","Harry Dodgson","2005","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Commando","Data East","1989","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Crack'ed","Robert Neve","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Crazy Brix (aftermarket)","Robert DeCrescenzo","2011","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Crazy Otto (video game) (aftermarket)","Robert DeCrescenzo","2013","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Crossbow","Exidy","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Dark Chambers","John Palevich","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Desert Falcon","Atari","1987","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Dig Dug","Namco","1987","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Donkey Kong","Nintendo","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Donkey Kong Junior","Nintendo","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Double Dragon","Technōs Japan","1989","Atari 7800");
replace into games (name, publisher, year, console_name) values ("F-18 Hornet (video game)","John Van Ryzin","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("FailSafe (aftermarket)","Robert DeCrescenzo","2010","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Fatal Run","Atari","1990","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Fight Night","Accolade","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Food Fight","Atari","1987","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Frenzy (aftermarket)","Robert DeCrescenzo","2013","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Galaga","Namco","1987","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Hangly-Man (aftermarket)","Nittoh","2005","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Hat Trick","Bally Sente","1987","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Ikari Warriors","Atari","1990","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Impossible Mission","Epyx","1987","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Jinks (video game)","Softgold","1989","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Joust","Williams Electronics","1987","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Jr. Pac-Man (aftermarket)","PacManPlus","2009","Atari 7800");
replace into games (name, publisher, year, console_name) values ("K.C. Munchkin (aftermarket)","Robert DeCrescenzo","2014","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Karateka","Brøderbund","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Klax (aftermarket)","David Dentt",2002,"Atari 7800");
replace into games (name, publisher, year, console_name) values ("Kung-Fu Master","Data East","Absolute","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Mario Bros.","Nintendo","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Mat Mania Challenge","Atari","1990","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Mean 18 Ultimate Golf","Accolade","1989","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Meltdown","Atari","1990","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Meteor Shower (aftermarket)","Robert DeCrescenzo","2011","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Midnight Mutants","Atari","1990","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Moon Cresta (aftermarket)","Robert DeCrescenzo","2011","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Motor Psycho","Atari","1990","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Ms. Pac-Attack (aftermarket)","Two-Bit Score","2005","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Ms. Pac-Man","Namco","1987","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Ninja Golf","Atari","1990","Atari 7800");
replace into games (name, publisher, year, console_name) values ("One-On-One Basketball","Electronic Arts","1987","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Pac-Man (aftermarket)","PacManPlus","2005","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Pac-Man Collection (aftermarket)","PacManPlus","2006","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Pac-Man Plus (aftermarket)","PacManPlus","2005","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Pac-Pollux (aftermarket)","Atari","Gambler172","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Pete Rose Baseball","Alex DeMeo","1989","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Planet Smashers (video game)","Atari","1989","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Pole Position II","Namco","1986","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Rampage","Bally Midway","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Realsports Baseball (video game)","Atari","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Rip-Off (aftermarket)","Robert DeCrescenzo","2012","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Robotron: 2084","Williams Electronics","1987","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Santa Simon (aftermarket)","Matthias Luedtke","2006","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Scramble (aftermarket)","Robert DeCrescenzo","2012","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Scrapyard Dog","Atari","1990","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Sentinel","Atari","1991","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Space Duel (aftermarket)","Atari","AtariAge","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Space Invaders (aftermarket)","Taito","AtariAge","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Summer Games","Epyx","1987","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Super Huey","Cosmi Corporation","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Super Pac-Man (aftermarket)","Namco","2008","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Super Skateboardin'","Absolute","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Tank Command","Froggo","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Title Match Pro Wrestling","Absolute","1989","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Tomcat: The F-14 Fighter Simulator","Dan Kitchen","1989","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Touchdown Football","Electronic Arts","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Tower Toppler","U.S. Gold","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Wasp! (aftermarket)","Mark Ball","2009","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Water Ski (video game)","Froggo","1988","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Winter Games","Epyx","1987","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Worm! (aftermarket)","Mark Ball","2010","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Xenophobe","Bally Midway","1989","Atari 7800");
replace into games (name, publisher, year, console_name) values ("Xevious","Namco","1988","Atari 7800");
