replace into games (name, publisher, year, console_name) values ("AirCars 94","","", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("AirCars","Midnight Entertainment Group","", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Alice's Mom's Rescue","Orion","2015", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Alien vs. Predator","Rebellion","1994", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Arena Football '95 (Beta)","V-Real Interactive, B&C ComputerVisions","2006", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Atari Karts","Miracle Designs Ltd.","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Attack of the Mutant Penguins","Sunrise Games","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("American Hero","Atari","", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Another World","Delphine Software/Sébastien Briais","2013", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Barkley Shut Up and Jam (Beta)","Ringler Studio","unreleased", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("BattleSphere","4 Play/ScatoLOGIC inc.","2000", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("BattleSphere Gold","4 Play/ScatoLOGIC inc.","2002", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Beebris","Reboot","2009", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Black Out!","Stormworks Interactive","2012", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Breakout 2000","MP Games","1996", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Brett Hull Hockey (Beta)","","", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Brutal Sports Football","Millenium Interactive,Teque","1994", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Bubsy in Fractured Furry Tales","Imagitec Design","1994", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Cannon Fodder","Sensible Software","1994", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Checkered Flag","Rebellion","1994", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Club Drive","Atari","1994", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Cybermorph","Attention To Detail","1993", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Defender 2000","Llamasoft","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Degz","Reboot","2012", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Doom","Id Software","1994", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Double Dragon V: The Shadow Falls","Williams Entertainment","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Downfall","Reboot","2011", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Dragon: The Bruce Lee Story","Midway","1994", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Elansar","Orion","2013", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Evolution: Dino Dudes","Imagitec Design","1993", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Fever Pitch Soccer","U.S. Gold","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Fight For Life","Atari","1996", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Flashback","Tiertex","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Flip Out!","Gorilla Systems","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Full Circle: Rocketeer","Reboot","2013", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("GORF Classic","Arcade game","2005", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("HMS RaptoR","Reboot","2011", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Highlander: The Last of the MacLeods","Lore Design Limited","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Hover Strike","Atari","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Hyper Force","Visual Impact","2000", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Impulse X","MD Games, Duranik",2012, "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("International Sensible Soccer","Sensible Software","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Iron Soldier","Eclipse Software","1994", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Iron Solder Beta","","", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Iron Soldier 2","Eclipse Software","1997", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("I-War","Imagitec Design","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Kasumi Ninja","Hand Made Software","1994", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Kobayashi Maru","Reboot","2011", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Kobayashi Maru: Final","Reboot","2012", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Mad Bodies","Force Design","2008", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Missile Command 3D","Atari, Virtuality","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("NBA Jam: Tournament Edition","High Voltage Software","1996", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Phase Zero","Hyper Image","1995 (Unreleased)", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Pinball Fantasies","Spidersoft","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Pitfall: The Mayan Adventure","Imagitec Design","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Power Drive Rally","Atari Games, Time Warner Interactive","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Primal Rage","Probe","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Project One (level 1 demo)","Reboot","2009", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Protector","Bethesda Softworks","1999", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Protector SE","Songbird Productions","2002", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Raiden","Imagitec Design","1994", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Rayman","Ubisoft","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("River Riders","Argonaut Games","1994", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Skycopter","Carousel Entertainment","1996", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Skyhammer","Rebellion Developments","2000", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Soccer Kid","Krisalis","2000", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("SpaceWar 2000","","2001", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Super Burnout","Shen","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("SuperFly DX","Reboot","2010", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("SuperCross 3D","Tiertex","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Syndicate","Bullfrog Productions","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Speedster II","Carousel Entertainment","1996", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Tempest 2000","Atari","1994", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Theme Park","Bullfrog Productions","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Tiny Toon Adventures (DEMO)","Atari","1994", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Total Carnage","Midway Games","2005", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Towers II: Plight of the Stargazer","JV Games","1996", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Trevor McFur in the Crescent Galaxy","Atari","1993", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Troy Aikman NFL Football","Telegames","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Ultra Vortek","Beyond Games","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Val D'isére Skiing and Snowboarding","Virtual Studio","1994", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("White Men Can't Jump","High Voltage Software","1995", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Wolfenstein 3D","Id Software","1994", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("World Tour Racing","","", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Worms","Team17","1998", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Zero 5","Caspian Software","1997", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Zool 2","Gremlin Graphics","1994", "Atari jaguar");
replace into games (name, publisher, year, console_name) values ("Zoop","Hookstone Productions","1995", "Atari jaguar");
