replace into games (name,console_name) values ( '32 in 1',  'Atari 2600');
replace into games (name,console_name) values ( '3-D Tic-Tac-Toe',  'Atari 2600');
replace into games (name,console_name) values ( 'Action Pak',  'Atari 2600');
replace into games (name,console_name) values ( 'Adventure',  'Atari 2600');
replace into games (name,console_name) values ( 'Air',  'Atari 2600');
replace into games (name,console_name) values ( 'Alpha Beam with Ernie',  'Atari 2600');
replace into games (name,console_name) values ( 'Asterix',  'Atari 2600');
replace into games (name,console_name) values ( 'Asteroids',  'Atari 2600');
replace into games (name,console_name) values ( 'Atari Video Cube',  'Atari 2600');
replace into games (name,console_name) values ( 'Backgammon',  'Atari 2600');
replace into games (name,console_name) values ( 'Back To School Pak',  'Atari 2600');
replace into games (name,console_name) values ( 'Basic Math AKA Fun With Numbers',  'Atari 2600');
replace into games (name,console_name) values ( 'Basic Programming',  'Atari 2600');
replace into games (name,console_name) values ( 'Basketball',  'Atari 2600');
replace into games (name,console_name) values ( 'Battlezone',  'Atari 2600');
replace into games (name,console_name) values ( 'Berzerk',  'Atari 2600');
replace into games (name,console_name) values ( 'Big Birds Egg Catch',  'Atari 2600');
replace into games (name,console_name) values ( 'Blackjack',  'Atari 2600');
replace into games (name,console_name) values ( 'Bowling',  'Atari 2600');
replace into games (name,console_name) values ( 'Brain Games',  'Atari 2600');
replace into games (name,console_name) values ( 'Breakout',  'Atari 2600');
replace into games (name,console_name) values ( 'Canyon Bomber',  'Atari 2600');
replace into games (name,console_name) values ( 'Casino',  'Atari 2600');
replace into games (name,console_name) values ( 'Centipede',  'Atari 2600');
replace into games (name,console_name) values ( 'Circus Atari',  'Atari 2600');
replace into games (name,console_name) values ( 'Codebreaker',  'Atari 2600');
replace into games (name,console_name) values ( 'Combat',  'Atari 2600');
replace into games (name,console_name) values ( 'Concentration aka A Game of Concentration',  'Atari 2600');
replace into games (name,console_name) values ( 'Cookie Monster Munch',  'Atari 2600');
replace into games (name,console_name) values ( 'Crazy Climber',  'Atari 2600');
replace into games (name,console_name) values ( 'Crossbow',  'Atari 2600');
replace into games (name,console_name) values ( 'Crystal Castles',  'Atari 2600');
replace into games (name,console_name) values ( 'Dark Chambers',  'Atari 2600');
replace into games (name,console_name) values ( 'Defender',  'Atari 2600');
replace into games (name,console_name) values ( 'Defender II',  'Atari 2600');
replace into games (name,console_name) values ( 'Demons to Diamonds',  'Atari 2600');
replace into games (name,console_name) values ( 'Desert Falcon',  'Atari 2600');
replace into games (name,console_name) values ( 'Diagnostic Cartridge',  'Atari 2600');
replace into games (name,console_name) values ( 'Dig Dug',  'Atari 2600');
replace into games (name,console_name) values ( 'Dodge Em',  'Atari 2600');
replace into games (name,console_name) values ( 'Double Dunk',  'Atari 2600');
replace into games (name,console_name) values ( 'E.T. the Extra-Terrestrial',  'Atari 2600');
replace into games (name,console_name) values ( 'Fatal Run',  'Atari 2600');
replace into games (name,console_name) values ( 'Flag Capture',  'Atari 2600');
replace into games (name,console_name) values ( 'Football',  'Atari 2600');
replace into games (name,console_name) values ( 'Frog Pond',  'Atari 2600');
replace into games (name,console_name) values ( 'Galaxian',  'Atari 2600');
replace into games (name,console_name) values ( 'Golf',  'Atari 2600');
replace into games (name,console_name) values ( 'Gravitar',  'Atari 2600');
replace into games (name,console_name) values ( 'Gremlins',  'Atari 2600');
replace into games (name,console_name) values ( 'Hangman',  'Atari 2600');
replace into games (name,console_name) values ( 'Haunted House',  'Atari 2600');
replace into games (name,console_name) values ( 'Home Run',  'Atari 2600');
replace into games (name,console_name) values ( 'Human Cannonball',  'Atari 2600');
replace into games (name,console_name) values ( 'Hunt & Score (see Concentration)',  'Atari 2600');
replace into games (name,console_name) values ( 'Ikari Warriors',  'Atari 2600');
replace into games (name,console_name) values ( 'Indy 500',  'Atari 2600');
replace into games (name,console_name) values ( 'Joust',  'Atari 2600');
replace into games (name,console_name) values ( 'Jr. Pac-Man',  'Atari 2600');
replace into games (name,console_name) values ( 'Jungle Hunt',  'Atari 2600');
replace into games (name,console_name) values ( 'Kangaroo',  'Atari 2600');
replace into games (name,console_name) values ( 'Klax',  'Atari 2600');
replace into games (name,console_name) values ( 'Krull',  'Atari 2600');
replace into games (name,console_name) values ( 'Mario Bros.',  'Atari 2600');
replace into games (name,console_name) values ( 'Math Gran Prix',  'Atari 2600');
replace into games (name,console_name) values ( 'Maze Craze: A Game of Cops and Robbers',  'Atari 2600');
replace into games (name,console_name) values ( 'Midnight Magic',  'Atari 2600');
replace into games (name,console_name) values ( 'Millipede',  'Atari 2600');
replace into games (name,console_name) values ( 'Miniature Golf',  'Atari 2600');
replace into games (name,console_name) values ( 'Missile Command',  'Atari 2600');
replace into games (name,console_name) values ( 'Moon Patrol',  'Atari 2600');
replace into games (name,console_name) values ( 'MotoRodeo',  'Atari 2600');
replace into games (name,console_name) values ( 'Ms. Pac-Man',  'Atari 2600');
replace into games (name,console_name) values ( 'Night Driver',  'Atari 2600');
replace into games (name,console_name) values ( 'Obelix',  'Atari 2600');
replace into games (name,console_name) values ( 'Off the Wall',  'Atari 2600');
replace into games (name,console_name) values ( 'Oscars Trash Race',  'Atari 2600');
replace into games (name,console_name) values ( 'Othello',  'Atari 2600');
replace into games (name,console_name) values ( 'Outlaw',  'Atari 2600');
replace into games (name,console_name) values ( 'Pac-Man',  'Atari 2600');
replace into games (name,console_name) values ( 'Pelés Soccer',  'Atari 2600');
replace into games (name,console_name) values ( 'Pengo',  'Atari 2600');
replace into games (name,console_name) values ( 'Pepsi Invaders',  'Atari 2600');
replace into games (name,console_name) values ( 'Phoenix',  'Atari 2600');
replace into games (name,console_name) values ( 'Pigs in Space',  'Atari 2600');
replace into games (name,console_name) values ( 'Polo',  'Atari 2600');
replace into games (name,console_name) values ( 'Pole Position',  'Atari 2600');
replace into games (name,console_name) values ( 'Quadrun',  'Atari 2600');
replace into games (name,console_name) values ( 'Racing Pak',  'Atari 2600');
replace into games (name,console_name) values ( 'Radar Lock',  'Atari 2600');
replace into games (name,console_name) values ( 'Raiders of the Lost Ark',  'Atari 2600');
replace into games (name,console_name) values ( 'RealSports Baseball',  'Atari 2600');
replace into games (name,console_name) values ( 'RealSports Boxing',  'Atari 2600');
replace into games (name,console_name) values ( 'RealSports Football',  'Atari 2600');
replace into games (name,console_name) values ( 'RealSports Soccer',  'Atari 2600');
replace into games (name,console_name) values ( 'RealSports Tennis',  'Atari 2600');
replace into games (name,console_name) values ( 'RealSports Volleyball',  'Atari 2600');
replace into games (name,console_name) values ( 'Road Runner',  'Atari 2600');
replace into games (name,console_name) values ( 'Rubiks Cube',  'Atari 2600');
replace into games (name,console_name) values ( 'Secret Quest',  'Atari 2600');
replace into games (name,console_name) values ( 'Sentinel',  'Atari 2600');
replace into games (name,console_name) values ( 'Signal Tracing Cartridge',  'Atari 2600');
replace into games (name,console_name) values ( 'Sky Diver',  'Atari 2600');
replace into games (name,console_name) values ( 'Slot Machine',  'Atari 2600');
replace into games (name,console_name) values ( 'Slot Racers',  'Atari 2600');
replace into games (name,console_name) values ( 'Snoopy and the Red Baron',  'Atari 2600');
replace into games (name,console_name) values ( 'Solaris',  'Atari 2600');
replace into games (name,console_name) values ( 'Sorcerers Apprentice',  'Atari 2600');
replace into games (name,console_name) values ( 'Space Invaders',  'Atari 2600');
replace into games (name,console_name) values ( 'Space War',  'Atari 2600');
replace into games (name,console_name) values ( 'Sprintmaster',  'Atari 2600');
replace into games (name,console_name) values ( 'Stargate',  'Atari 2600');
replace into games (name,console_name) values ( 'Star Raiders',  'Atari 2600');
replace into games (name,console_name) values ( 'Star Ship',  'Atari 2600');
replace into games (name,console_name) values ( 'Steeplechase',  'Atari 2600');
replace into games (name,console_name) values ( 'Stellar Track',  'Atari 2600');
replace into games (name,console_name) values ( 'Street Racer',  'Atari 2600');
replace into games (name,console_name) values ( 'Submarine Commander',  'Atari 2600');
replace into games (name,console_name) values ( 'Super Baseball',  'Atari 2600');
replace into games (name,console_name) values ( 'Super Breakout',  'Atari 2600');
replace into games (name,console_name) values ( 'Super Football',  'Atari 2600');
replace into games (name,console_name) values ( 'Superman',  'Atari 2600');
replace into games (name,console_name) values ( 'Surround',  'Atari 2600');
replace into games (name,console_name) values ( 'Swordquest: Earthworld',  'Atari 2600');
replace into games (name,console_name) values ( 'Swordquest: Fireworld',  'Atari 2600');
replace into games (name,console_name) values ( 'Swordquest: Waterworld',  'Atari 2600');
replace into games (name,console_name) values ( 'Ta',  'Atari 2600');
replace into games (name,console_name) values ( 'Track & Field',  'Atari 2600');
replace into games (name,console_name) values ( 'Vanguard',  'Atari 2600');
replace into games (name,console_name) values ( 'Video Checkers',  'Atari 2600');
replace into games (name,console_name) values ( 'Video Chess',  'Atari 2600');
replace into games (name,console_name) values ( 'Video Olympics',  'Atari 2600');
replace into games (name,console_name) values ( 'Video Pinball',  'Atari 2600');
replace into games (name,console_name) values ( 'Warlords',  'Atari 2600');
replace into games (name,console_name) values ( 'Xenophobe',  'Atari 2600');
replace into games (name,console_name) values ( 'Yars Revenge',  'Atari 2600');
replace into games (name,console_name) values ( 'Acid Drop',  'Atari 2600');
replace into games (name,console_name) values ( 'Actionauts',  'Atari 2600');
replace into games (name,console_name) values ( 'The Activision Decathlon',  'Atari 2600');
replace into games (name,console_name) values ( 'Adventures of Tron',  'Atari 2600');
replace into games (name,console_name) values ( 'Airlock',  'Atari 2600');
replace into games (name,console_name) values ( 'Air Raid',  'Atari 2600');
replace into games (name,console_name) values ( 'Air Raiders',  'Atari 2600');
replace into games (name,console_name) values ( 'Alien',  'Atari 2600');
replace into games (name,console_name) values ( 'Aliens Return',  'Atari 2600');
replace into games (name,console_name) values ( 'Amidar',  'Atari 2600');
replace into games (name,console_name) values ( 'Aquatak',  'Atari 2600');
replace into games (name,console_name) values ( 'Armor Ambush',  'Atari 2600');
replace into games (name,console_name) values ( 'Artillery Duel/Chuck Norris Superkicks',  'Atari 2600');
replace into games (name,console_name) values ( 'Artillery Duel/Ghost Manor',  'Atari 2600');
replace into games (name,console_name) values ( 'Artillery Duel/Spikes Peak',  'Atari 2600');
replace into games (name,console_name) values ( 'Artillery Duel',  'Atari 2600');
replace into games (name,console_name) values ( 'Assault',  'Atari 2600');
replace into games (name,console_name) values ( 'Astroblast',  'Atari 2600');
replace into games (name,console_name) values ( 'Atlantis',  'Atari 2600');
replace into games (name,console_name) values ( 'Atlantis II',  'Atari 2600');
replace into games (name,console_name) values ( 'Bachelor Party',  'Atari 2600');
replace into games (name,console_name) values ( 'Bachelorette Party',  'Atari 2600');
replace into games (name,console_name) values ( 'Bank Heist',  'Atari 2600');
replace into games (name,console_name) values ( 'Barnstorming',  'Atari 2600');
replace into games (name,console_name) values ( 'Beamrider',  'Atari 2600');
replace into games (name,console_name) values ( 'Beany Bopper',  'Atari 2600');
replace into games (name,console_name) values ( 'Beat Em and Eat Em',  'Atari 2600');
replace into games (name,console_name) values ( 'Berenstain Bears',  'Atari 2600');
replace into games (name,console_name) values ( 'Bermuda Triangle',  'Atari 2600');
replace into games (name,console_name) values ( 'Birthday Mania',  'Atari 2600');
replace into games (name,console_name) values ( 'Blue Print',  'Atari 2600');
replace into games (name,console_name) values ( 'BMX Airmaster',  'Atari 2600');
replace into games (name,console_name) values ( 'Bobby Is Going Home',  'Atari 2600');
replace into games (name,console_name) values ( 'Boing!',  'Atari 2600');
replace into games (name,console_name) values ( 'Boxing',  'Atari 2600');
replace into games (name,console_name) values ( 'Bridge',  'Atari 2600');
replace into games (name,console_name) values ( 'Buck Rogers: Planet of Zoom',  'Atari 2600');
replace into games (name,console_name) values ( 'Bugs',  'Atari 2600');
replace into games (name,console_name) values ( 'Bumper Bash',  'Atari 2600');
replace into games (name,console_name) values ( 'Bump n Jump',  'Atari 2600');
replace into games (name,console_name) values ( 'BurgerTime',  'Atari 2600');
replace into games (name,console_name) values ( 'Burning Desire',  'Atari 2600');
replace into games (name,console_name) values ( 'Busy Police',  'Atari 2600');
replace into games (name,console_name) values ( 'Cakewalk',  'Atari 2600');
replace into games (name,console_name) values ( 'California Games',  'Atari 2600');
replace into games (name,console_name) values ( 'Carnival',  'Atari 2600');
replace into games (name,console_name) values ( 'Cathouse Blues',  'Atari 2600');
replace into games (name,console_name) values ( 'Challenge',  'Atari 2600');
replace into games (name,console_name) values ( 'Challenge of Nexar',  'Atari 2600');
replace into games (name,console_name) values ( 'Chase the Chuck Wagon',  'Atari 2600');
replace into games (name,console_name) values ( 'Checkers',  'Atari 2600');
replace into games (name,console_name) values ( 'China Syndrome',  'Atari 2600');
replace into games (name,console_name) values ( 'Chopper Command',  'Atari 2600');
replace into games (name,console_name) values ( 'Chuck Norris Superkicks/Ghost Manor',  'Atari 2600');
replace into games (name,console_name) values ( 'Chuck Norris Superkicks/Spikes Peak',  'Atari 2600');
replace into games (name,console_name) values ( 'Chuck Norris Superkicks',  'Atari 2600');
replace into games (name,console_name) values ( 'Coconuts',  'Atari 2600');
replace into games (name,console_name) values ( 'Commando',  'Atari 2600');
replace into games (name,console_name) values ( 'Commando Raid',  'Atari 2600');
replace into games (name,console_name) values ( 'Communist Mutants from Space (Cassette)',  'Atari 2600');
replace into games (name,console_name) values ( 'Condor Attack',  'Atari 2600');
replace into games (name,console_name) values ( 'Confrontation',  'Atari 2600');
replace into games (name,console_name) values ( 'Congo Bongo',  'Atari 2600');
replace into games (name,console_name) values ( 'Cosmic Ark',  'Atari 2600');
replace into games (name,console_name) values ( 'Cosmic Commuter',  'Atari 2600');
replace into games (name,console_name) values ( 'Cosmic Corridor',  'Atari 2600');
replace into games (name,console_name) values ( 'Cosmic Creeps',  'Atari 2600');
replace into games (name,console_name) values ( 'Cosmic Free Fire',  'Atari 2600');
replace into games (name,console_name) values ( 'Cosmic Swarm',  'Atari 2600');
replace into games (name,console_name) values ( 'Crab Control',  'Atari 2600');
replace into games (name,console_name) values ( 'Crackpots',  'Atari 2600');
replace into games (name,console_name) values ( 'Crash Dive',  'Atari 2600');
replace into games (name,console_name) values ( 'Cross Force',  'Atari 2600');
replace into games (name,console_name) values ( 'Cruise Missile',  'Atari 2600');
replace into games (name,console_name) values ( 'Crypts of Chaos',  'Atari 2600');
replace into games (name,console_name) values ( 'Cubicolor',  'Atari 2600');
replace into games (name,console_name) values ( 'Custers Revenge',  'Atari 2600');
replace into games (name,console_name) values ( 'Dancing Plate',  'Atari 2600');
replace into games (name,console_name) values ( 'Dark Cavern',  'Atari 2600');
replace into games (name,console_name) values ( 'Deadly Discs',  'Atari 2600');
replace into games (name,console_name) values ( 'Deadly Duck',  'Atari 2600');
replace into games (name,console_name) values ( 'Death Trap',  'Atari 2600');
replace into games (name,console_name) values ( 'Demolition Herby',  'Atari 2600');
replace into games (name,console_name) values ( 'Demon Attack',  'Atari 2600');
replace into games (name,console_name) values ( 'Dice Puzzle',  'Atari 2600');
replace into games (name,console_name) values ( 'Dishaster',  'Atari 2600');
replace into games (name,console_name) values ( 'Dolphin',  'Atari 2600');
replace into games (name,console_name) values ( 'Donkey Kong',  'Atari 2600');
replace into games (name,console_name) values ( 'Donkey Kong Junior',  'Atari 2600');
replace into games (name,console_name) values ( 'Double Dragon',  'Atari 2600');
replace into games (name,console_name) values ( 'Dragon Treasure',  'Atari 2600');
replace into games (name,console_name) values ( 'Dragonfire',  'Atari 2600');
replace into games (name,console_name) values ( 'Dragonstomper (cassette)',  'Atari 2600');
replace into games (name,console_name) values ( 'Dumbos Flying Circus',  'Atari 2600');
replace into games (name,console_name) values ( 'Dragster',  'Atari 2600');
replace into games (name,console_name) values ( 'Earth Dies Screaming',  'Atari 2600');
replace into games (name,console_name) values ( 'Earth Attack',  'Atari 2600');
replace into games (name,console_name) values ( 'Eddy Langfinger, der Museumsdieb',  'Atari 2600');
replace into games (name,console_name) values ( 'Eggomania',  'Atari 2600');
replace into games (name,console_name) values ( 'Elis Ladder',  'Atari 2600');
replace into games (name,console_name) values ( 'Encounter at L-5',  'Atari 2600');
replace into games (name,console_name) values ( 'Enduro',  'Atari 2600');
replace into games (name,console_name) values ( 'Entombed',  'Atari 2600');
replace into games (name,console_name) values ( 'Escape From The Mindmaster (Cassette)',  'Atari 2600');
replace into games (name,console_name) values ( 'Espial',  'Atari 2600');
replace into games (name,console_name) values ( 'Exocet',  'Atari 2600');
replace into games (name,console_name) values ( 'Exocet Missile',  'Atari 2600');
replace into games (name,console_name) values ( 'Extra Terrestrials',  'Atari 2600');
replace into games (name,console_name) values ( 'Fantastic Voyage',  'Atari 2600');
replace into games (name,console_name) values ( 'Farmer Dan',  'Atari 2600');
replace into games (name,console_name) values ( 'Fast Eddie',  'Atari 2600');
replace into games (name,console_name) values ( 'Fast Food',  'Atari 2600');
replace into games (name,console_name) values ( 'Fathom',  'Atari 2600');
replace into games (name,console_name) values ( 'Fighter Pilot',  'Atari 2600');
replace into games (name,console_name) values ( 'Final Approach',  'Atari 2600');
replace into games (name,console_name) values ( 'Fireball (cassette)',  'Atari 2600');
replace into games (name,console_name) values ( 'Fire Fighter',  'Atari 2600');
replace into games (name,console_name) values ( 'Fire Fly',  'Atari 2600');
replace into games (name,console_name) values ( 'Fisher Price',  'Atari 2600');
replace into games (name,console_name) values ( 'Fishing Derby',  'Atari 2600');
replace into games (name,console_name) values ( 'Flash Gordon',  'Atari 2600');
replace into games (name,console_name) values ( 'Frankensteins Monster',  'Atari 2600');
replace into games (name,console_name) values ( 'Freeway',  'Atari 2600');
replace into games (name,console_name) values ( 'Frogger',  'Atari 2600');
replace into games (name,console_name) values ( 'Frogs and Flies',  'Atari 2600');
replace into games (name,console_name) values ( 'The Official Frogger (cassette)',  'Atari 2600');
replace into games (name,console_name) values ( 'Frogger II: Threeedeep!',  'Atari 2600');
replace into games (name,console_name) values ( 'Front Line',  'Atari 2600');
replace into games (name,console_name) values ( 'Frostbite',  'Atari 2600');
replace into games (name,console_name) values ( 'Gamma-Attack',  'Atari 2600');
replace into games (name,console_name) values ( 'Gangster Alley',  'Atari 2600');
replace into games (name,console_name) values ( 'Gas Hog',  'Atari 2600');
replace into games (name,console_name) values ( 'Gauntlet',  'Atari 2600');
replace into games (name,console_name) values ( 'Ghostbusters',  'Atari 2600');
replace into games (name,console_name) values ( 'Ghostbusters II',  'Atari 2600');
replace into games (name,console_name) values ( 'Ghost Manor/Spikes Peak',  'Atari 2600');
replace into games (name,console_name) values ( 'Ghost Manor',  'Atari 2600');
replace into games (name,console_name) values ( 'G.I. Joe: Cobra Strike',  'Atari 2600');
replace into games (name,console_name) values ( 'Gigolo',  'Atari 2600');
replace into games (name,console_name) values ( 'Glacier Patrol',  'Atari 2600');
replace into games (name,console_name) values ( 'Glib',  'Atari 2600');
replace into games (name,console_name) values ( 'Gopher',  'Atari 2600');
replace into games (name,console_name) values ( 'Gorf',  'Atari 2600');
replace into games (name,console_name) values ( 'Grand Prix',  'Atari 2600');
replace into games (name,console_name) values ( 'Great Escape',  'Atari 2600');
replace into games (name,console_name) values ( 'Guardian',  'Atari 2600');
replace into games (name,console_name) values ( 'Gyruss',  'Atari 2600');
replace into games (name,console_name) values ( 'Halloween',  'Atari 2600');
replace into games (name,console_name) values ( 'Harbor Escape',  'Atari 2600');
replace into games (name,console_name) values ( 'H.E.R.O.',  'Atari 2600');
replace into games (name,console_name) values ( 'I Want My Mommy',  'Atari 2600');
replace into games (name,console_name) values ( 'Ice Hockey',  'Atari 2600');
replace into games (name,console_name) values ( 'Inca Gold',  'Atari 2600');
replace into games (name,console_name) values ( 'Infiltrate',  'Atari 2600');
replace into games (name,console_name) values ( 'International Soccer',  'Atari 2600');
replace into games (name,console_name) values ( 'James Bond 007',  'Atari 2600');
replace into games (name,console_name) values ( 'Jawbreaker',  'Atari 2600');
replace into games (name,console_name) values ( 'Journey Escape',  'Atari 2600');
replace into games (name,console_name) values ( 'Jungle Fever',  'Atari 2600');
replace into games (name,console_name) values ( 'Kaboom!',  'Atari 2600');
replace into games (name,console_name) values ( 'Karate',  'Atari 2600');
replace into games (name,console_name) values ( 'Keystone Kapers',  'Atari 2600');
replace into games (name,console_name) values ( 'Killer Satellites (Cassette)',  'Atari 2600');
replace into games (name,console_name) values ( 'King Kong',  'Atari 2600');
replace into games (name,console_name) values ( 'Knight on the Town',  'Atari 2600');
replace into games (name,console_name) values ( 'Kool-Aid Man',  'Atari 2600');
replace into games (name,console_name) values ( 'Kung-Fu Master',  'Atari 2600');
replace into games (name,console_name) values ( 'Lady in Wading',  'Atari 2600');
replace into games (name,console_name) values ( 'Laser Blast',  'Atari 2600');
replace into games (name,console_name) values ( 'Laser Gates',  'Atari 2600');
replace into games (name,console_name) values ( 'Laser Volley',  'Atari 2600');
replace into games (name,console_name) values ( 'Lochjaw',  'Atari 2600');
replace into games (name,console_name) values ( 'Lock n Chase',  'Atari 2600');
replace into games (name,console_name) values ( 'London Blit',  'Atari 2600');
replace into games (name,console_name) values ( 'Lost Luggage',  'Atari 2600');
replace into games (name,console_name) values ( 'M.A.D.',  'Atari 2600');
replace into games (name,console_name) values ( 'MagiCard',  'Atari 2600');
replace into games (name,console_name) values ( 'Malagai',  'Atari 2600');
replace into games (name,console_name) values ( 'Mangia',  'Atari 2600');
replace into games (name,console_name) values ( 'Marauder',  'Atari 2600');
replace into games (name,console_name) values ( 'Marine Wars',  'Atari 2600');
replace into games (name,console_name) values ( 'M*A*S*H',  'Atari 2600');
replace into games (name,console_name) values ( 'Master Builder',  'Atari 2600');
replace into games (name,console_name) values ( 'Masters of the Universe: The Power of He-Man',  'Atari 2600');
replace into games (name,console_name) values ( 'MegaBoy',  'Atari 2600');
replace into games (name,console_name) values ( 'Mega Force',  'Atari 2600');
replace into games (name,console_name) values ( 'Megamania',  'Atari 2600');
replace into games (name,console_name) values ( 'Miner 2049er',  'Atari 2600');
replace into games (name,console_name) values ( 'Miner 2049er II',  'Atari 2600');
replace into games (name,console_name) values ( 'Mines of Minos',  'Atari 2600');
replace into games (name,console_name) values ( 'Missile Control',  'Atari 2600');
replace into games (name,console_name) values ( 'Mission 3000 A.D.',  'Atari 2600');
replace into games (name,console_name) values ( 'Mission Survive',  'Atari 2600');
replace into games (name,console_name) values ( 'Mogul Maniac',  'Atari 2600');
replace into games (name,console_name) values ( 'Montezumas Revenge: Starring Panama Joe',  'Atari 2600');
replace into games (name,console_name) values ( 'Moonsweeper',  'Atari 2600');
replace into games (name,console_name) values ( 'Motocross',  'Atari 2600');
replace into games (name,console_name) values ( 'Motocross Racer',  'Atari 2600');
replace into games (name,console_name) values ( 'Mountain King',  'Atari 2600');
replace into games (name,console_name) values ( 'Mouse Trap',  'Atari 2600');
replace into games (name,console_name) values ( 'Mr. Do!',  'Atari 2600');
replace into games (name,console_name) values ( 'Mr. Dos Castle',  'Atari 2600');
replace into games (name,console_name) values ( 'Mr. Postman',  'Atari 2600');
replace into games (name,console_name) values ( 'The Music Machine',  'Atari 2600');
replace into games (name,console_name) values ( 'My Golf',  'Atari 2600');
replace into games (name,console_name) values ( 'Name This Game',  'Atari 2600');
replace into games (name,console_name) values ( 'Nightmare',  'Atari 2600');
replace into games (name,console_name) values ( 'Night Stalker',  'Atari 2600');
replace into games (name,console_name) values ( 'No Escape!',  'Atari 2600');
replace into games (name,console_name) values ( 'Nuts',  'Atari 2600');
replace into games (name,console_name) values ( 'Ocean City Defender',  'Atari 2600');
replace into games (name,console_name) values ( 'Off Your Rocker',  'Atari 2600');
replace into games (name,console_name) values ( 'Oink!',  'Atari 2600');
replace into games (name,console_name) values ( 'Omega Race',  'Atari 2600');
replace into games (name,console_name) values ( 'Open Sesame',  'Atari 2600');
replace into games (name,console_name) values ( 'Out of Control',  'Atari 2600');
replace into games (name,console_name) values ( 'Pac-Kong',  'Atari 2600');
replace into games (name,console_name) values ( 'Panda Chase',  'Atari 2600');
replace into games (name,console_name) values ( 'Parachute',  'Atari 2600');
replace into games (name,console_name) values ( 'Party Mix (cassette)',  'Atari 2600');
replace into games (name,console_name) values ( 'Pete Rose Baseball',  'Atari 2600');
replace into games (name,console_name) values ( 'Phantom Tank',  'Atari 2600');
replace into games (name,console_name) values ( 'Phantom-Panzer',  'Atari 2600');
replace into games (name,console_name) values ( 'Phaser Patrol (cassette)',  'Atari 2600');
replace into games (name,console_name) values ( 'Philly Flasher',  'Atari 2600');
replace into games (name,console_name) values ( 'Pick n Pile',  'Atari 2600');
replace into games (name,console_name) values ( 'Picnic',  'Atari 2600');
replace into games (name,console_name) values ( 'Piece o Cake',  'Atari 2600');
replace into games (name,console_name) values ( 'Pinball',  'Atari 2600');
replace into games (name,console_name) values ( 'Piraten-Schiff',  'Atari 2600');
replace into games (name,console_name) values ( 'Pitfall!',  'Atari 2600');
replace into games (name,console_name) values ( 'Pitfall II: Lost Caverns',  'Atari 2600');
replace into games (name,console_name) values ( 'Planet Patrol',  'Atari 2600');
replace into games (name,console_name) values ( 'Planeten Patrouile',  'Atari 2600');
replace into games (name,console_name) values ( 'Plaque Attack',  'Atari 2600');
replace into games (name,console_name) values ( 'Polaris',  'Atari 2600');
replace into games (name,console_name) values ( 'Pooyan',  'Atari 2600');
replace into games (name,console_name) values ( 'Popeye',  'Atari 2600');
replace into games (name,console_name) values ( 'Porkys',  'Atari 2600');
replace into games (name,console_name) values ( 'Pressure Cooker',  'Atari 2600');
replace into games (name,console_name) values ( 'Private Eye',  'Atari 2600');
replace into games (name,console_name) values ( 'Pyramid War',  'Atari 2600');
replace into games (name,console_name) values ( 'Q*bert',  'Atari 2600');
replace into games (name,console_name) values ( 'Q*berts Qubes',  'Atari 2600');
replace into games (name,console_name) values ( 'Quest for Quintana Roo',  'Atari 2600');
replace into games (name,console_name) values ( 'Quick Step',  'Atari 2600');
replace into games (name,console_name) values ( 'Rabbit Transit (cassette)',  'Atari 2600');
replace into games (name,console_name) values ( 'Racquetball',  'Atari 2600');
replace into games (name,console_name) values ( 'Radar',  'Atari 2600');
replace into games (name,console_name) values ( 'Raft Rider',  'Atari 2600');
replace into games (name,console_name) values ( 'Ram It',  'Atari 2600');
replace into games (name,console_name) values ( 'Rampage',  'Atari 2600');
replace into games (name,console_name) values ( 'Reactor',  'Atari 2600');
replace into games (name,console_name) values ( 'Red Sea Crossing',  'Atari 2600');
replace into games (name,console_name) values ( 'Rescue Terra 1',  'Atari 2600');
replace into games (name,console_name) values ( 'Revenge of the Beefsteak Tomatoes',  'Atari 2600');
replace into games (name,console_name) values ( 'Riddle of the Sphinx',  'Atari 2600');
replace into games (name,console_name) values ( 'River Patrol',  'Atari 2600');
replace into games (name,console_name) values ( 'River Raid',  'Atari 2600');
replace into games (name,console_name) values ( 'River Raid II',  'Atari 2600');
replace into games (name,console_name) values ( 'Robin Hood/Sir Lancelot - The Joust',  'Atari 2600');
replace into games (name,console_name) values ( 'Robin Hood',  'Atari 2600');
replace into games (name,console_name) values ( 'Robot Commando Raid',  'Atari 2600');
replace into games (name,console_name) values ( 'Robot Tank',  'Atari 2600');
replace into games (name,console_name) values ( 'Roc N Rope',  'Atari 2600');
replace into games (name,console_name) values ( 'Room of Doom',  'Atari 2600');
replace into games (name,console_name) values ( 'Save Our Ship',  'Atari 2600');
replace into games (name,console_name) values ( 'Save the Whales',  'Atari 2600');
replace into games (name,console_name) values ( 'Scraper Caper',  'Atari 2600');
replace into games (name,console_name) values ( 'Scuba Diver',  'Atari 2600');
replace into games (name,console_name) values ( 'Sea Hawk',  'Atari 2600');
replace into games (name,console_name) values ( 'Seamonster',  'Atari 2600');
replace into games (name,console_name) values ( 'Seaquest',  'Atari 2600');
replace into games (name,console_name) values ( 'Shark Attack',  'Atari 2600');
replace into games (name,console_name) values ( 'Shootin Gallery',  'Atari 2600');
replace into games (name,console_name) values ( 'Shuttle Orbiter',  'Atari 2600');
replace into games (name,console_name) values ( 'Sir Lancelot',  'Atari 2600');
replace into games (name,console_name) values ( 'Skate Boardin: A Radical Adventure',  'Atari 2600');
replace into games (name,console_name) values ( 'Skeet Shoot',  'Atari 2600');
replace into games (name,console_name) values ( 'Skiing',  'Atari 2600');
replace into games (name,console_name) values ( 'Sky Jinks',  'Atari 2600');
replace into games (name,console_name) values ( 'Sky Skipper',  'Atari 2600');
replace into games (name,console_name) values ( 'Smurf: Rescue in Gargamels Castle',  'Atari 2600');
replace into games (name,console_name) values ( 'Snail Against Squirrel',  'Atari 2600');
replace into games (name,console_name) values ( 'Sneak N Peek',  'Atari 2600');
replace into games (name,console_name) values ( 'Solar Fox',  'Atari 2600');
replace into games (name,console_name) values ( 'Solar Storm',  'Atari 2600');
replace into games (name,console_name) values ( 'Sorcerer',  'Atari 2600');
replace into games (name,console_name) values ( 'Space Adventure',  'Atari 2600');
replace into games (name,console_name) values ( 'Space Attack',  'Atari 2600');
replace into games (name,console_name) values ( 'Space Canyon',  'Atari 2600');
replace into games (name,console_name) values ( 'Space Cavern',  'Atari 2600');
replace into games (name,console_name) values ( 'Spacechase',  'Atari 2600');
replace into games (name,console_name) values ( 'Space Grid',  'Atari 2600');
replace into games (name,console_name) values ( 'Space Jockey',  'Atari 2600');
replace into games (name,console_name) values ( 'Spacemaster X-7',  'Atari 2600');
replace into games (name,console_name) values ( 'Space Shuttle: A Journey Into Space',  'Atari 2600');
replace into games (name,console_name) values ( 'Spiderdroid',  'Atari 2600');
replace into games (name,console_name) values ( 'Spider Fighter',  'Atari 2600');
replace into games (name,console_name) values ( 'Spider-Man',  'Atari 2600');
replace into games (name,console_name) values ( 'Spider Maze',  'Atari 2600');
replace into games (name,console_name) values ( 'Spikes Peak',  'Atari 2600');
replace into games (name,console_name) values ( 'Spitfire Attack',  'Atari 2600');
replace into games (name,console_name) values ( 'Springer',  'Atari 2600');
replace into games (name,console_name) values ( 'Spy Hunter',  'Atari 2600');
replace into games (name,console_name) values ( 'Squeeze Box',  'Atari 2600');
replace into games (name,console_name) values ( 'Sssnake',  'Atari 2600');
replace into games (name,console_name) values ( 'Stampede',  'Atari 2600');
replace into games (name,console_name) values ( 'Star Fox',  'Atari 2600');
replace into games (name,console_name) values ( 'Stargunner',  'Atari 2600');
replace into games (name,console_name) values ( 'Starmaster',  'Atari 2600');
replace into games (name,console_name) values ( 'Star Strike',  'Atari 2600');
replace into games (name,console_name) values ( 'Star Trek: Strategic Operations Simulator',  'Atari 2600');
replace into games (name,console_name) values ( 'Star Voyager',  'Atari 2600');
replace into games (name,console_name) values ( 'Star Wars: The Arcade Game',  'Atari 2600');
replace into games (name,console_name) values ( 'Star Wars: Jedi Arena',  'Atari 2600');
replace into games (name,console_name) values ( 'Star Wars Return of the Jedi: Death Star Battle',  'Atari 2600');
replace into games (name,console_name) values ( 'Star Wars: The Empire Strikes Back',  'Atari 2600');
replace into games (name,console_name) values ( 'Strategy X',  'Atari 2600');
replace into games (name,console_name) values ( 'Strawberry Shortcake: Musical Match-ups',  'Atari 2600');
replace into games (name,console_name) values ( 'Stronghold',  'Atari 2600');
replace into games (name,console_name) values ( 'Stunt Man',  'Atari 2600');
replace into games (name,console_name) values ( 'Sub-Scan',  'Atari 2600');
replace into games (name,console_name) values ( 'Subterranea',  'Atari 2600');
replace into games (name,console_name) values ( 'Suicide Mission (cassette)',  'Atari 2600');
replace into games (name,console_name) values ( 'Summer Games',  'Atari 2600');
replace into games (name,console_name) values ( 'Super Baumeister',  'Atari 2600');
replace into games (name,console_name) values ( 'Super Challenge Baseball',  'Atari 2600');
replace into games (name,console_name) values ( 'Super Challenge Football',  'Atari 2600');
replace into games (name,console_name) values ( 'Super Cobra',  'Atari 2600');
replace into games (name,console_name) values ( 'Surfers Paradise: But Danger Below!',  'Atari 2600');
replace into games (name,console_name) values ( 'Survival Island (cassette)',  'Atari 2600');
replace into games (name,console_name) values ( 'Survival Run',  'Atari 2600');
replace into games (name,console_name) values ( 'Swedish Erotica: Bachelor Party',  'Atari 2600');
replace into games (name,console_name) values ( 'Swedish Erotica: Beat Em & Eat Em',  'Atari 2600');
replace into games (name,console_name) values ( 'Swedish Erotica: Custers Revenge',  'Atari 2600');
replace into games (name,console_name) values ( 'Sword of Saros (cassette)',  'Atari 2600');
replace into games (name,console_name) values ( 'Tac-Scan',  'Atari 2600');
replace into games (name,console_name) values ( 'Tank Brigade',  'Atari 2600');
replace into games (name,console_name) values ( 'Tank City',  'Atari 2600');
replace into games (name,console_name) values ( 'Tanks But No Tanks',  'Atari 2600');
replace into games (name,console_name) values ( 'Tapeworm',  'Atari 2600');
replace into games (name,console_name) values ( 'Tapper',  'Atari 2600');
replace into games (name,console_name) values ( 'Task Force',  'Atari 2600');
replace into games (name,console_name) values ( 'Tax Avoiders',  'Atari 2600');
replace into games (name,console_name) values ( 'Tennis',  'Atari 2600');
replace into games (name,console_name) values ( 'The Texas Chainsaw Massacre',  'Atari 2600');
replace into games (name,console_name) values ( 'The Smurfs Save the Day[10]',  'Atari 2600');
replace into games (name,console_name) values ( 'Threshold',  'Atari 2600');
replace into games (name,console_name) values ( 'Thunderground',  'Atari 2600');
replace into games (name,console_name) values ( 'Time Pilot',  'Atari 2600');
replace into games (name,console_name) values ( 'Time Warp',  'Atari 2600');
replace into games (name,console_name) values ( 'Title Match Pro Wrestling',  'Atari 2600');
replace into games (name,console_name) values ( 'Tomarc The Barbarian',  'Atari 2600');
replace into games (name,console_name) values ( 'Tomcat: The F-14 Fighter Simulator',  'Atari 2600');
replace into games (name,console_name) values ( 'Tooth Protectors',  'Atari 2600');
replace into games (name,console_name) values ( 'Towering Inferno',  'Atari 2600');
replace into games (name,console_name) values ( 'Treasure Below',  'Atari 2600');
replace into games (name,console_name) values ( 'Trick Shot',  'Atari 2600');
replace into games (name,console_name) values ( 'Tron: Deadly Discs',  'Atari 2600');
replace into games (name,console_name) values ( 'Tunnel Runner',  'Atari 2600');
replace into games (name,console_name) values ( 'Turmoil',  'Atari 2600');
replace into games (name,console_name) values ( 'Tutankham',  'Atari 2600');
replace into games (name,console_name) values ( 'Universal Chaos',  'Atari 2600');
replace into games (name,console_name) values ( 'Upn Down',  'Atari 2600');
replace into games (name,console_name) values ( 'Venture',  'Atari 2600');
replace into games (name,console_name) values ( 'Video Jogger',  'Atari 2600');
replace into games (name,console_name) values ( 'Video Life',  'Atari 2600');
replace into games (name,console_name) values ( 'Video Reflex',  'Atari 2600');
replace into games (name,console_name) values ( 'Vulture Attack',  'Atari 2600');
replace into games (name,console_name) values ( 'Wabbit',  'Atari 2600');
replace into games (name,console_name) values ( 'Wall Ball',  'Atari 2600');
replace into games (name,console_name) values ( 'Wall Defender',  'Atari 2600');
replace into games (name,console_name) values ( 'War Zone',  'Atari 2600');
replace into games (name,console_name) values ( 'Warplock',  'Atari 2600');
replace into games (name,console_name) values ( 'Wing War',  'Atari 2600');
replace into games (name,console_name) values ( 'Winter Games',  'Atari 2600');
replace into games (name,console_name) values ( 'Wizard of Wor',  'Atari 2600');
replace into games (name,console_name) values ( 'Word Zapper',  'Atari 2600');
replace into games (name,console_name) values ( 'Worm War I',  'Atari 2600');
replace into games (name,console_name) values ( 'X-man',  'Atari 2600');
replace into games (name,console_name) values ( 'Z-Tack',  'Atari 2600');
replace into games (name,console_name) values ( 'Zaxxon',  'Atari 2600');
replace into games (name,console_name) values ( 'Zoo Fun',  'Atari 2600');
