replace into games(name,console_name) values( "3 Ninjas Kick Back",'Super Nintendo');
replace into games(name,console_name) values( "The 7th Saga",'Super Nintendo');
replace into games(name,console_name) values( "A.S.P. Air Strike Patrol Desert FighterEU",'Super Nintendo');
replace into games(name,console_name) values( "AAAHH!!! Real Monsters",'Super Nintendo');
replace into games(name,console_name) values( "ABC Monday Night Football",'Super Nintendo');
replace into games(name,console_name) values( "Acme Animation Factory",'Super Nintendo');
replace into games(name,console_name) values( "ActRaiser",'Super Nintendo');
replace into games(name,console_name) values( "ActRaiser 2",'Super Nintendo');
replace into games(name,console_name) values( "The Addams Family",'Super Nintendo');
replace into games(name,console_name) values( "The Addams Family: Pugsley's Scavenger Hunt",'Super Nintendo');
replace into games(name,console_name) values( "Addams Family Values",'Super Nintendo');
replace into games(name,console_name) values( "The Adventures of Batman & Robin",'Super Nintendo');
replace into games(name,console_name) values( "The Adventures of Dr. Franken",'Super Nintendo');
replace into games(name,console_name) values( "The Adventures of Mighty Max",'Super Nintendo');
replace into games(name,console_name) values( "The Adventures of Rocky and Bullwinkle and Friends",'Super Nintendo');
replace into games(name,console_name) values( "Aero Fighters",'Super Nintendo');
replace into games(name,console_name) values( "Aero the Acro-Bat",'Super Nintendo');
replace into games(name,console_name) values( "Aero the Acro-Bat 2",'Super Nintendo');
replace into games(name,console_name) values( "Aerobiz",'Super Nintendo');
replace into games(name,console_name) values( "Aerobiz Supersonic",'Super Nintendo');
replace into games(name,console_name) values( "Air Cavalry",'Super Nintendo');
replace into games(name,console_name) values( "Al Unser Jr.'s Road to the Top",'Super Nintendo');
replace into games(name,console_name) values( "Alfred Chicken",'Super Nintendo');
replace into games(name,console_name) values( "Alien³",'Super Nintendo');
replace into games(name,console_name) values( "Alien vs. Predator",'Super Nintendo');
replace into games(name,console_name) values( "American Gladiators",'Super Nintendo');
replace into games(name,console_name) values( "An American Tail: Fievel Goes West",'Super Nintendo');
replace into games(name,console_name) values( "Andre Agassi Tennis",'Super Nintendo');
replace into games(name,console_name) values( "Animaniacs",'Super Nintendo');
replace into games(name,console_name) values( "Arcade's Greatest Hits: The Atari Collection 1",'Super Nintendo');
replace into games(name,console_name) values( "Arcana",'Super Nintendo');
replace into games(name,console_name) values( "Ardy Lightfoot",'Super Nintendo');
replace into games(name,console_name) values( "Arkanoid: Doh It Again",'Super Nintendo');
replace into games(name,console_name) values( "Art of Fighting",'Super Nintendo');
replace into games(name,console_name) values( "Axelay",'Super Nintendo');
replace into games(name,console_name) values( "B.O.B.",'Super Nintendo');
replace into games(name,console_name) values( "Ballz 3D",'Super Nintendo');
replace into games(name,console_name) values( "Barbie Super Model",'Super Nintendo');
replace into games(name,console_name) values( "Barkley Shut Up and Jam!",'Super Nintendo');
replace into games(name,console_name) values( "Bass Masters Classic",'Super Nintendo');
replace into games(name,console_name) values( "Bass Masters Classic: Pro Edition",'Super Nintendo');
replace into games(name,console_name) values( "Bassin's Black Bass with Hank Parker",'Super Nintendo');
replace into games(name,console_name) values( "Batman Forever",'Super Nintendo');
replace into games(name,console_name) values( "Batman Returns",'Super Nintendo');
replace into games(name,console_name) values( "Battle Blaze",'Super Nintendo');
replace into games(name,console_name) values( "Battle Cars",'Super Nintendo');
replace into games(name,console_name) values( "Battle Clash",'Super Nintendo');
replace into games(name,console_name) values( "Battle Grand Prix",'Super Nintendo');
replace into games(name,console_name) values( "Battletoads & Double Dragon",'Super Nintendo');
replace into games(name,console_name) values( "Battletoads in Battlemaniacs",'Super Nintendo');
replace into games(name,console_name) values( "Beavis and Butt-head",'Super Nintendo');
replace into games(name,console_name) values( "Bébé's Kids",'Super Nintendo');
replace into games(name,console_name) values( "Best of the Best: Championship Karate",'Super Nintendo');
replace into games(name,console_name) values( "Big Sky Trooper",'Super Nintendo');
replace into games(name,console_name) values( "Biker Mice from Mars",'Super Nintendo');
replace into games(name,console_name) values( "Bill Laimbeer's Combat Basketball",'Super Nintendo');
replace into games(name,console_name) values( "Bill Walsh College Football",'Super Nintendo');
replace into games(name,console_name) values( "BioMetal",'Super Nintendo');
replace into games(name,console_name) values( "BlaZeon: The Bio-Cyborg Challenge",'Super Nintendo');
replace into games(name,console_name) values( "The Blues Brothers",'Super Nintendo');
replace into games(name,console_name) values( "Boogerman: A Pick and Flick Adventure",'Super Nintendo');
replace into games(name,console_name) values( "Brain Lord",'Super Nintendo');
replace into games(name,console_name) values( "The Brainies",'Super Nintendo');
replace into games(name,console_name) values( "Bram Stoker's Dracula",'Super Nintendo');
replace into games(name,console_name) values( "Brandish",'Super Nintendo');
replace into games(name,console_name) values( "BreakThru!",'Super Nintendo');
replace into games(name,console_name) values( "Breath of Fire",'Super Nintendo');
replace into games(name,console_name) values( "Breath of Fire II",'Super Nintendo');
replace into games(name,console_name) values( "Brett Hull Hockey",'Super Nintendo');
replace into games(name,console_name) values( "Brett Hull Hockey '95",'Super Nintendo');
replace into games(name,console_name) values( "Bronkie the Bronchiasaurus",'Super Nintendo');
replace into games(name,console_name) values( "Brunswick World: Tournament of Champions",'Super Nintendo');
replace into games(name,console_name) values( "Brutal: Paws of Fury",'Super Nintendo');
replace into games(name,console_name) values( "Bubsy in Claws Encounters of the Furred Kind",'Super Nintendo');
replace into games(name,console_name) values( "Bubsy 2",'Super Nintendo');
replace into games(name,console_name) values( "Bugs Bunny Rabbit Rampage",'Super Nintendo');
replace into games(name,console_name) values( "Bulls versus Blazers and the NBA Playoffs",'Super Nintendo');
replace into games(name,console_name) values( "Cacoma Knight in Bizyland",'Super Nintendo');
replace into games(name,console_name) values( "Cal Ripken Jr. Baseball",'Super Nintendo');
replace into games(name,console_name) values( "California Games 2",'Super Nintendo');
replace into games(name,console_name) values( "Capcom's MVP Football",'Super Nintendo');
replace into games(name,console_name) values( "Capcom's Soccer Shootout",'Super Nintendo');
replace into games(name,console_name) values( "Captain America and The Avengers",'Super Nintendo');
replace into games(name,console_name) values( "Captain Commando",'Super Nintendo');
replace into games(name,console_name) values( "Captain Novolin",'Super Nintendo');
replace into games(name,console_name) values( "Carrier Aces",'Super Nintendo');
replace into games(name,console_name) values( "Casper",'Super Nintendo');
replace into games(name,console_name) values( "Champions World Class Soccer",'Super Nintendo');
replace into games(name,console_name) values( "Championship Pool",'Super Nintendo');
replace into games(name,console_name) values( "The Chessmaster",'Super Nintendo');
replace into games(name,console_name) values( "Chester Cheetah: Too Cool to Fool",'Super Nintendo');
replace into games(name,console_name) values( "Chester Cheetah: Wild Wild Quest",'Super Nintendo');
replace into games(name,console_name) values( "Choplifter III",'Super Nintendo');
replace into games(name,console_name) values( "Chrono Trigger",'Super Nintendo');
replace into games(name,console_name) values( "Chuck Rock",'Super Nintendo');
replace into games(name,console_name) values( "Civilization",'Super Nintendo');
replace into games(name,console_name) values( "ClayFighter",'Super Nintendo');
replace into games(name,console_name) values( "ClayFighter: Tournament Edition",'Super Nintendo');
replace into games(name,console_name) values( "ClayFighter 2: Judgment Clay",'Super Nintendo');
replace into games(name,console_name) values( "Claymates",'Super Nintendo');
replace into games(name,console_name) values( "Cliffhanger",'Super Nintendo');
replace into games(name,console_name) values( "Clue",'Super Nintendo');
replace into games(name,console_name) values( "College Football USA '97: The Road to New Orleans",'Super Nintendo');
replace into games(name,console_name) values( "College Slam",'Super Nintendo');
replace into games(name,console_name) values( "The Combatribes",'Super Nintendo');
replace into games(name,console_name) values( "Congo's Caper",'Super Nintendo');
replace into games(name,console_name) values( "Cool Spot",'Super Nintendo');
replace into games(name,console_name) values( "Cool World",'Super Nintendo');
replace into games(name,console_name) values( "Cutthroat Island",'Super Nintendo');
replace into games(name,console_name) values( "Cyber Spin",'Super Nintendo');
replace into games(name,console_name) values( "Cybernator",'Super Nintendo');
replace into games(name,console_name) values( "Daffy Duck: The Marvin Missions",'Super Nintendo');
replace into games(name,console_name) values( "Darius Twin",'Super Nintendo');
replace into games(name,console_name) values( "David Crane's Amazing Tennis",'Super Nintendo');
replace into games(name,console_name) values( "The Death and Return of Superman",'Super Nintendo');
replace into games(name,console_name) values( "Demolition Man",'Super Nintendo');
replace into games(name,console_name) values( "Demon's Crest",'Super Nintendo');
replace into games(name,console_name) values( "Desert Strike: Return to the Gulf",'Super Nintendo');
replace into games(name,console_name) values( "D-Force",'Super Nintendo');
replace into games(name,console_name) values( "Dig & Spike Volleyball",'Super Nintendo');
replace into games(name,console_name) values( "DinoCity",'Super Nintendo');
replace into games(name,console_name) values( "Dirt Trax FX",'Super Nintendo');
replace into games(name,console_name) values( "Disney's Aladdin",'Super Nintendo');
replace into games(name,console_name) values( "Disney's Beauty and the Beast",'Super Nintendo');
replace into games(name,console_name) values( "Disney's Bonkers",'Super Nintendo');
replace into games(name,console_name) values( "Disney's Pinocchio",'Super Nintendo');
replace into games(name,console_name) values( "Donkey Kong Country",'Super Nintendo');
replace into games(name,console_name) values( "Donkey Kong Country 2: Diddy's Kong Quest",'Super Nintendo');
replace into games(name,console_name) values( "Donkey Kong Country 3: Dixie Kong's Double Trouble!",'Super Nintendo');
replace into games(name,console_name) values( "Doom",'Super Nintendo');
replace into games(name,console_name) values( "Doom Troopers",'Super Nintendo');
replace into games(name,console_name) values( "Doomsday Warrior",'Super Nintendo');
replace into games(name,console_name) values( "Double Dragon V: The Shadow Falls",'Super Nintendo');
replace into games(name,console_name) values( "Dragon: The Bruce Lee Story",'Super Nintendo');
replace into games(name,console_name) values( "Dragon View",'Super Nintendo');
replace into games(name,console_name) values( "Dragon's Lair",'Super Nintendo');
replace into games(name,console_name) values( "Drakkhen",'Super Nintendo');
replace into games(name,console_name) values( "Dream TV",'Super Nintendo');
replace into games(name,console_name) values( "The Duel: Test Drive II",'Super Nintendo');
replace into games(name,console_name) values( "Dungeon Master",'Super Nintendo');
replace into games(name,console_name) values( "E.V.O.: Search for Eden",'Super Nintendo');
replace into games(name,console_name) values( "Earth Defense Force",'Super Nintendo');
replace into games(name,console_name) values( "EarthBound",'Super Nintendo');
replace into games(name,console_name) values( "Earthworm Jim",'Super Nintendo');
replace into games(name,console_name) values( "Earthworm Jim 2",'Super Nintendo');
replace into games(name,console_name) values( "Eek! The Cat",'Super Nintendo');
replace into games(name,console_name) values( "Emmitt Smith Football",'Super Nintendo');
replace into games(name,console_name) values( "Equinox",'Super Nintendo');
replace into games(name,console_name) values( "ESPN Baseball Tonight",'Super Nintendo');
replace into games(name,console_name) values( "ESPN National Hockey Night",'Super Nintendo');
replace into games(name,console_name) values( "ESPN Speed World",'Super Nintendo');
replace into games(name,console_name) values( "ESPN Sunday Night NFL",'Super Nintendo');
replace into games(name,console_name) values( "Extra Innings",'Super Nintendo');
replace into games(name,console_name) values( "Eye of the Beholder",'Super Nintendo');
replace into games(name,console_name) values( "F-Zero",'Super Nintendo');
replace into games(name,console_name) values( "F1 Pole Position",'Super Nintendo');
replace into games(name,console_name) values( "F1 ROC II: Race of Champions",'Super Nintendo');
replace into games(name,console_name) values( "Faceball 2000",'Super Nintendo');
replace into games(name,console_name) values( "Family Dog",'Super Nintendo');
replace into games(name,console_name) values( "Family Feud",'Super Nintendo');
replace into games(name,console_name) values( "Fatal Fury: King of Fighters",'Super Nintendo');
replace into games(name,console_name) values( "Fatal Fury 2",'Super Nintendo');
replace into games(name,console_name) values( "Fatal Fury Special",'Super Nintendo');
replace into games(name,console_name) values( "FIFA International Soccer",'Super Nintendo');
replace into games(name,console_name) values( "FIFA Soccer 96",'Super Nintendo');
replace into games(name,console_name) values( "FIFA 97: Gold Edition",'Super Nintendo');
replace into games(name,console_name) values( "Fighter's History",'Super Nintendo');
replace into games(name,console_name) values( "Final Fantasy II",'Super Nintendo');
replace into games(name,console_name) values( "Final Fantasy III",'Super Nintendo');
replace into games(name,console_name) values( "Final Fight",'Super Nintendo');
replace into games(name,console_name) values( "Final Fight 2",'Super Nintendo');
replace into games(name,console_name) values( "Final Fight 3",'Super Nintendo');
replace into games(name,console_name) values( "Final Fight Guy",'Super Nintendo');
replace into games(name,console_name) values( "Firestriker",'Super Nintendo');
replace into games(name,console_name) values( "First Samurai",'Super Nintendo');
replace into games(name,console_name) values( "The Flintstones",'Super Nintendo');
replace into games(name,console_name) values( "The Flintstones: The Treasure of Sierra Madrock",'Super Nintendo');
replace into games(name,console_name) values( "Football Fury",'Super Nintendo');
replace into games(name,console_name) values( "Foreman For Real",'Super Nintendo');
replace into games(name,console_name) values( "Frank Thomas' Big Hurt Baseball",'Super Nintendo');
replace into games(name,console_name) values( "Frantic Flea",'Super Nintendo');
replace into games(name,console_name) values( "Frogger",'Super Nintendo');
replace into games(name,console_name) values( "Full Throttle: All-American Racing",'Super Nintendo');
replace into games(name,console_name) values( "Fun 'n Games",'Super Nintendo');
replace into games(name,console_name) values( "Gemfire",'Super Nintendo');
replace into games(name,console_name) values( "Genghis Khan II: Clan of the Gray Wolf",'Super Nintendo');
replace into games(name,console_name) values( "George Foreman's KO Boxing",'Super Nintendo');
replace into games(name,console_name) values( "Ghoul Patrol",'Super Nintendo');
replace into games(name,console_name) values( "Gods",'Super Nintendo');
replace into games(name,console_name) values( "Goof Troop",'Super Nintendo');
replace into games(name,console_name) values( "GP-1",'Super Nintendo');
replace into games(name,console_name) values( "GP-1: Part II",'Super Nintendo');
replace into games(name,console_name) values( "Gradius III",'Super Nintendo');
replace into games(name,console_name) values( "The Great Circus Mystery Starring Mickey & Minnie",'Super Nintendo');
replace into games(name,console_name) values( "The Great Waldo Search",'Super Nintendo');
replace into games(name,console_name) values( "GunForce",'Super Nintendo');
replace into games(name,console_name) values( "Hagane: The Final Conflict",'Super Nintendo');
replace into games(name,console_name) values( "Hal's Hole in One Golf",'Super Nintendo');
replace into games(name,console_name) values( "HammerLock Wrestling",'Super Nintendo');
replace into games(name,console_name) values( "Hardball III",'Super Nintendo');
replace into games(name,console_name) values( "Harley's Humongous Adventure",'Super Nintendo');
replace into games(name,console_name) values( "Harvest Moon",'Super Nintendo');
replace into games(name,console_name) values( "Hit the Ice",'Super Nintendo');
replace into games(name,console_name) values( "Home Alone",'Super Nintendo');
replace into games(name,console_name) values( "Home Alone 2: Lost in New York",'Super Nintendo');
replace into games(name,console_name) values( "Home Improvement: Power Tool Pursuit!",'Super Nintendo');
replace into games(name,console_name) values( "Hook",'Super Nintendo');
replace into games(name,console_name) values( "The Hunt for Red October",'Super Nintendo');
replace into games(name,console_name) values( "Hurricanes",'Super Nintendo');
replace into games(name,console_name) values( "Hyper V-Ball",'Super Nintendo');
replace into games(name,console_name) values( "Hyper Zone",'Super Nintendo');
replace into games(name,console_name) values( "The Ignition Factor",'Super Nintendo');
replace into games(name,console_name) values( "Imperium",'Super Nintendo');
replace into games(name,console_name) values( "Incantation",'Super Nintendo');
replace into games(name,console_name) values( "The Incredible Crash Dummies",'Super Nintendo');
replace into games(name,console_name) values( "The Incredible Hulk",'Super Nintendo');
replace into games(name,console_name) values( "Indiana Jones' Greatest Adventures",'Super Nintendo');
replace into games(name,console_name) values( "Inindo: Way of the Ninja",'Super Nintendo');
replace into games(name,console_name) values( "Inspector Gadget",'Super Nintendo');
replace into games(name,console_name) values( "International Superstar Soccer",'Super Nintendo');
replace into games(name,console_name) values( "International Superstar Soccer Deluxe",'Super Nintendo');
replace into games(name,console_name) values( "International Tennis Tour",'Super Nintendo');
replace into games(name,console_name) values( "The Itchy & Scratchy Game",'Super Nintendo');
replace into games(name,console_name) values( "Izzy's Quest for the Olympic Rings",'Super Nintendo');
replace into games(name,console_name) values( "J.R.R. Tolkien's The Lord of the Rings, Vol. I",'Super Nintendo');
replace into games(name,console_name) values( "Jack Nicklaus Golf",'Super Nintendo');
replace into games(name,console_name) values( "James Bond Jr.",'Super Nintendo');
replace into games(name,console_name) values( "Jammit",'Super Nintendo');
replace into games(name,console_name) values( "Jeopardy!",'Super Nintendo');
replace into games(name,console_name) values( "Jeopardy! Deluxe Edition",'Super Nintendo');
replace into games(name,console_name) values( "Jeopardy! Sports Edition",'Super Nintendo');
replace into games(name,console_name) values( "The Jetsons: Invasion of the Planet Pirates",'Super Nintendo');
replace into games(name,console_name) values( "Jim Lee's WildC.A.T.S: Covert Action Teams",'Super Nintendo');
replace into games(name,console_name) values( "Jim Power: The Lost Dimension in 3-D",'Super Nintendo');
replace into games(name,console_name) values( "Jimmy Connors Pro Tennis Tour",'Super Nintendo');
replace into games(name,console_name) values( "Jimmy Houston's Bass Tournament U.S.A.",'Super Nintendo');
replace into games(name,console_name) values( "John Madden Football",'Super Nintendo');
replace into games(name,console_name) values( "John Madden Football '93",'Super Nintendo');
replace into games(name,console_name) values( "Judge Dredd",'Super Nintendo');
replace into games(name,console_name) values( "The Jungle Book",'Super Nintendo');
replace into games(name,console_name) values( "Jungle Strike",'Super Nintendo');
replace into games(name,console_name) values( "Jurassic Park",'Super Nintendo');
replace into games(name,console_name) values( "Jurassic Park 2: The Chaos Continues",'Super Nintendo');
replace into games(name,console_name) values( "Justice League Task Force",'Super Nintendo');
replace into games(name,console_name) values( "Ka-Blooey",'Super Nintendo');
replace into games(name,console_name) values( "Kawasaki Caribbean Challenge",'Super Nintendo');
replace into games(name,console_name) values( "Kawasaki Superbike Challenge",'Super Nintendo');
replace into games(name,console_name) values( "Ken Griffey Jr. Presents Major League Baseball",'Super Nintendo');
replace into games(name,console_name) values( "Ken Griffey Jr.'s Winning Run",'Super Nintendo');
replace into games(name,console_name) values( "Kendo Rage",'Super Nintendo');
replace into games(name,console_name) values( "Kid Klown in Crazy Chase",'Super Nintendo');
replace into games(name,console_name) values( "Killer Instinct",'Super Nintendo');
replace into games(name,console_name) values( "King Arthur & the Knights of Justice",'Super Nintendo');
replace into games(name,console_name) values( "King Arthur's World",'Super Nintendo');
replace into games(name,console_name) values( "The King of Dragons",'Super Nintendo');
replace into games(name,console_name) values( "King of the Monsters",'Super Nintendo');
replace into games(name,console_name) values( "King of the Monsters 2",'Super Nintendo');
replace into games(name,console_name) values( "Kirby's Dream Course",'Super Nintendo');
replace into games(name,console_name) values( "Kirby's Dream Land 3",'Super Nintendo');
replace into games(name,console_name) values( "Knights of the Round",'Super Nintendo');
replace into games(name,console_name) values( "Krusty's Super Fun House",'Super Nintendo');
replace into games(name,console_name) values( "Kyle Petty's No Fear Racing",'Super Nintendo');
replace into games(name,console_name) values( "Lagoon",'Super Nintendo');
replace into games(name,console_name) values( "Lamborghini American Challenge",'Super Nintendo');
replace into games(name,console_name) values( "Last Action Hero",'Super Nintendo');
replace into games(name,console_name) values( "The Lawnmower Man",'Super Nintendo');
replace into games(name,console_name) values( "Legend",'Super Nintendo');
replace into games(name,console_name) values( "The Legend of the Mystical Ninja",'Super Nintendo');
replace into games(name,console_name) values( "The Legend of Zelda: A Link to the Past",'Super Nintendo');
replace into games(name,console_name) values( "Lemmings",'Super Nintendo');
replace into games(name,console_name) values( "Lemmings 2: The Tribes",'Super Nintendo');
replace into games(name,console_name) values( "Lester the Unlikely",'Super Nintendo');
replace into games(name,console_name) values( "Lethal Enforcers",'Super Nintendo');
replace into games(name,console_name) values( "Lethal Weapon",'Super Nintendo');
replace into games(name,console_name) values( "Liberty or Death",'Super Nintendo');
replace into games(name,console_name) values( "The Lion King",'Super Nintendo');
replace into games(name,console_name) values( "The Lost Vikings",'Super Nintendo');
replace into games(name,console_name) values( "The Lost Vikings 2",'Super Nintendo');
replace into games(name,console_name) values( "Lufia & the Fortress of Doom",'Super Nintendo');
replace into games(name,console_name) values( "M.A.C.S. Basic Rifle Marksmanship",'Super Nintendo');
replace into games(name,console_name) values( "Madden NFL '94",'Super Nintendo');
replace into games(name,console_name) values( "Madden NFL '95",'Super Nintendo');
replace into games(name,console_name) values( "Madden NFL '96",'Super Nintendo');
replace into games(name,console_name) values( "Madden NFL 97",'Super Nintendo');
replace into games(name,console_name) values( "Madden NFL 98",'Super Nintendo');
replace into games(name,console_name) values( "Magic Boy",'Super Nintendo');
replace into games(name,console_name) values( "Magic Sword",'Super Nintendo');
replace into games(name,console_name) values( "The Magical Quest Starring Mickey Mouse",'Super Nintendo');
replace into games(name,console_name) values( "Mario is Missing!",'Super Nintendo');
replace into games(name,console_name) values( "Mario Paint",'Super Nintendo');
replace into games(name,console_name) values( "Mario's Early Years! Fun with Letters",'Super Nintendo');
replace into games(name,console_name) values( "Mario's Early Years! Fun with Numbers",'Super Nintendo');
replace into games(name,console_name) values( "Mario's Early Years! Preschool Fun",'Super Nintendo');
replace into games(name,console_name) values( "Mario's Time Machine",'Super Nintendo');
replace into games(name,console_name) values( "Mark Davis' The Fishing Master",'Super Nintendo');
replace into games(name,console_name) values( "Marvel Super Heroes: War of the Gems",'Super Nintendo');
replace into games(name,console_name) values( "Mary Shelley's Frankenstein",'Super Nintendo');
replace into games(name,console_name) values( "The Mask",'Super Nintendo');
replace into games(name,console_name) values( "Math Blaster: Episode 1",'Super Nintendo');
replace into games(name,console_name) values( "Mecarobot Golf",'Super Nintendo');
replace into games(name,console_name) values( "MechWarrior",'Super Nintendo');
replace into games(name,console_name) values( "MechWarrior 3050",'Super Nintendo');
replace into games(name,console_name) values( "Mega Man 7",'Super Nintendo');
replace into games(name,console_name) values( "Mega Man Soccer",'Super Nintendo');
replace into games(name,console_name) values( "Mega Man X",'Super Nintendo');
replace into games(name,console_name) values( "Mega Man X2",'Super Nintendo');
replace into games(name,console_name) values( "Mega Man X3",'Super Nintendo');
replace into games(name,console_name) values( "Metal Combat: Falcon's Revenge",'Super Nintendo');
replace into games(name,console_name) values( "Metal Marines",'Super Nintendo');
replace into games(name,console_name) values( "Metal Morph",'Super Nintendo');
replace into games(name,console_name) values( "Metal Warriors",'Super Nintendo');
replace into games(name,console_name) values( "Michael Andretti's Indy Car Challenge",'Super Nintendo');
replace into games(name,console_name) values( "Michael Jordan: Chaos in the Windy City",'Super Nintendo');
replace into games(name,console_name) values( "Mickey Mania: The Timeless Adventures of Mickey Mouse",'Super Nintendo');
replace into games(name,console_name) values( "Mickey's Ultimate Challenge",'Super Nintendo');
replace into games(name,console_name) values( "Micro Machines",'Super Nintendo');
replace into games(name,console_name) values( "Might and Magic III: Isles of Terra",'Super Nintendo');
replace into games(name,console_name) values( "Mighty Morphin Power Rangers",'Super Nintendo');
replace into games(name,console_name) values( "Mighty Morphin Power Rangers: The Movie",'Super Nintendo');
replace into games(name,console_name) values( "Mighty Morphin Power Rangers Fighting Edition",'Super Nintendo');
replace into games(name,console_name) values( "Miracle Piano",'Super Nintendo');
replace into games(name,console_name) values( "MLBPA Baseball",'Super Nintendo');
replace into games(name,console_name) values( "Mohawk & Headphone Jack",'Super Nintendo');
replace into games(name,console_name) values( "Monopoly",'Super Nintendo');
replace into games(name,console_name) values( "Mortal Kombat",'Super Nintendo');
replace into games(name,console_name) values( "Mortal Kombat II",'Super Nintendo');
replace into games(name,console_name) values( "Mortal Kombat 3",'Super Nintendo');
replace into games(name,console_name) values( "Mountain Bike Rally",'Super Nintendo');
replace into games(name,console_name) values( "Mr. Do!",'Super Nintendo');
replace into games(name,console_name) values( "Mr. Nutz",'Super Nintendo');
replace into games(name,console_name) values( "Ms. Pac-Man",'Super Nintendo');
replace into games(name,console_name) values( "Musya",'Super Nintendo');
replace into games(name,console_name) values( "Natsume Championship Wrestling",'Super Nintendo');
replace into games(name,console_name) values( "NBA All-Star Challenge",'Super Nintendo');
replace into games(name,console_name) values( "NBA Give 'n Go",'Super Nintendo');
replace into games(name,console_name) values( "NBA Hangtime",'Super Nintendo');
replace into games(name,console_name) values( "NBA Jam",'Super Nintendo');
replace into games(name,console_name) values( "NBA Jam Tournament Edition",'Super Nintendo');
replace into games(name,console_name) values( "NBA Live 95",'Super Nintendo');
replace into games(name,console_name) values( "NBA Live 96",'Super Nintendo');
replace into games(name,console_name) values( "NBA Live 97",'Super Nintendo');
replace into games(name,console_name) values( "NBA Live 98",'Super Nintendo');
replace into games(name,console_name) values( "NBA Showdown",'Super Nintendo');
replace into games(name,console_name) values( "NCAA Final Four Basketball",'Super Nintendo');
replace into games(name,console_name) values( "NCAA Football",'Super Nintendo');
replace into games(name,console_name) values( "Newman/Haas IndyCar featuring Nigel Mansell",'Super Nintendo');
replace into games(name,console_name) values( "NFL Football",'Super Nintendo');
replace into games(name,console_name) values( "NFL Quarterback Club",'Super Nintendo');
replace into games(name,console_name) values( "NFL Quarterback Club 96",'Super Nintendo');
replace into games(name,console_name) values( "NHL 94",'Super Nintendo');
replace into games(name,console_name) values( "NHL 95",'Super Nintendo');
replace into games(name,console_name) values( "NHL 96",'Super Nintendo');
replace into games(name,console_name) values( "NHL 97",'Super Nintendo');
replace into games(name,console_name) values( "NHL 98",'Super Nintendo');
replace into games(name,console_name) values( "NHLPA Hockey '93",'Super Nintendo');
replace into games(name,console_name) values( "Nickelodeon Guts",'Super Nintendo');
replace into games(name,console_name) values( "Nigel Mansell's World Championship Racing",'Super Nintendo');
replace into games(name,console_name) values( "Ninja Gaiden Trilogy",'Super Nintendo');
replace into games(name,console_name) values( "No Escape",'Super Nintendo');
replace into games(name,console_name) values( "Nobunaga's Ambition",'Super Nintendo');
replace into games(name,console_name) values( "Nobunaga's Ambition: Lord of Darkness",'Super Nintendo');
replace into games(name,console_name) values( "Nolan Ryan's Baseball",'Super Nintendo');
replace into games(name,console_name) values( "Nosferatu",'Super Nintendo');
replace into games(name,console_name) values( "Obitus",'Super Nintendo');
replace into games(name,console_name) values( "Ogre Battle: March of the Black Queen",'Super Nintendo');
replace into games(name,console_name) values( "Olympic Summer Games",'Super Nintendo');
replace into games(name,console_name) values( "On the Ball",'Super Nintendo');
replace into games(name,console_name) values( "Operation Europe: Path to Victory",'Super Nintendo');
replace into games(name,console_name) values( "Operation Logic Bomb",'Super Nintendo');
replace into games(name,console_name) values( "Operation Thunderbolt",'Super Nintendo');
replace into games(name,console_name) values( "Oscar",'Super Nintendo');
replace into games(name,console_name) values( "Out to Lunch",'Super Nintendo');
replace into games(name,console_name) values( "Outlander",'Super Nintendo');
replace into games(name,console_name) values( "P.T.O.: Pacific Theater of Operations",'Super Nintendo');
replace into games(name,console_name) values( "P.T.O. II: Pacific Theater of Operations",'Super Nintendo');
replace into games(name,console_name) values( "Pac-Attack",'Super Nintendo');
replace into games(name,console_name) values( "Pac-In-Time",'Super Nintendo');
replace into games(name,console_name) values( "Pac-Man 2: The New Adventures",'Super Nintendo');
replace into games(name,console_name) values( "Packy and Marlon",'Super Nintendo');
replace into games(name,console_name) values( "The Pagemaster",'Super Nintendo');
replace into games(name,console_name) values( "Paladin's Quest",'Super Nintendo');
replace into games(name,console_name) values( "Paperboy 2",'Super Nintendo');
replace into games(name,console_name) values( "The Peace Keepers",'Super Nintendo');
replace into games(name,console_name) values( "PGA European Tour",'Super Nintendo');
replace into games(name,console_name) values( "PGA Tour 96",'Super Nintendo');
replace into games(name,console_name) values( "PGA Tour Golf",'Super Nintendo');
replace into games(name,console_name) values( "Phalanx",'Super Nintendo');
replace into games(name,console_name) values( "Phantom 2040",'Super Nintendo');
replace into games(name,console_name) values( "Pieces",'Super Nintendo');
replace into games(name,console_name) values( "Pilotwings",'Super Nintendo');
replace into games(name,console_name) values( "Pinball Dreams",'Super Nintendo');
replace into games(name,console_name) values( "Pinball Fantasies",'Super Nintendo');
replace into games(name,console_name) values( "Pink Goes to Hollywood",'Super Nintendo');
replace into games(name,console_name) values( "Pirates of Dark Water",'Super Nintendo');
replace into games(name,console_name) values( "Pitfall: The Mayan Adventure",'Super Nintendo');
replace into games(name,console_name) values( "Pit-Fighter",'Super Nintendo');
replace into games(name,console_name) values( "Plok",'Super Nintendo');
replace into games(name,console_name) values( "Pocky & Rocky",'Super Nintendo');
replace into games(name,console_name) values( "Pocky & Rocky 2",'Super Nintendo');
replace into games(name,console_name) values( "Populous",'Super Nintendo');
replace into games(name,console_name) values( "Porky Pig's Haunted Holiday",'Super Nintendo');
replace into games(name,console_name) values( "Power Instinct",'Super Nintendo');
replace into games(name,console_name) values( "Power Moves",'Super Nintendo');
replace into games(name,console_name) values( "Power Piggs of the Dark Age",'Super Nintendo');
replace into games(name,console_name) values( "Power Rangers Zeo: Battle Racers",'Super Nintendo');
replace into games(name,console_name) values( "Prehistorik Man",'Super Nintendo');
replace into games(name,console_name) values( "Primal Rage",'Super Nintendo');
replace into games(name,console_name) values( "Prince of Persia",'Super Nintendo');
replace into games(name,console_name) values( "Prince of Persia 2: The Shadow and the Flame",'Super Nintendo');
replace into games(name,console_name) values( "Pro Quarterback",'Super Nintendo');
replace into games(name,console_name) values( "Pro Sport Hockey",'Super Nintendo');
replace into games(name,console_name) values( "Pushover",'Super Nintendo');
replace into games(name,console_name) values( "Q*bert 3",'Super Nintendo');
replace into games(name,console_name) values( "Race Drivin'",'Super Nintendo');
replace into games(name,console_name) values( "Radical Rex",'Super Nintendo');
replace into games(name,console_name) values( "Raiden Trad",'Super Nintendo');
replace into games(name,console_name) values( "Rampart",'Super Nintendo');
replace into games(name,console_name) values( "Rap Jam: Volume One",'Super Nintendo');
replace into games(name,console_name) values( "Realm",'Super Nintendo');
replace into games(name,console_name) values( "Relief Pitcher",'Super Nintendo');
replace into games(name,console_name) values( "The Ren & Stimpy Show: Buckaroo$!",'Super Nintendo');
replace into games(name,console_name) values( "The Ren & Stimpy Show: Fire Dogs",'Super Nintendo');
replace into games(name,console_name) values( "The Ren & Stimpy Show: Time Warp",'Super Nintendo');
replace into games(name,console_name) values( "The Ren & Stimpy Show: Veediots!",'Super Nintendo');
replace into games(name,console_name) values( "Revolution X",'Super Nintendo');
replace into games(name,console_name) values( "Rex Ronan: Experimental Surgeon",'Super Nintendo');
replace into games(name,console_name) values( "Rise of the Phoenix",'Super Nintendo');
replace into games(name,console_name) values( "Rise of the Robots",'Super Nintendo');
replace into games(name,console_name) values( "Rival Turf!",'Super Nintendo');
replace into games(name,console_name) values( "Road Riot 4WD",'Super Nintendo');
replace into games(name,console_name) values( "RoboCop 3",'Super Nintendo');
replace into games(name,console_name) values( "RoboCop Versus The Terminator",'Super Nintendo');
replace into games(name,console_name) values( "SlapstickJap",'Super Nintendo');
replace into games(name,console_name) values( "Rock n' Roll Racing",'Super Nintendo');
replace into games(name,console_name) values( "The Rocketeer",'Super Nintendo');
replace into games(name,console_name) values( "Rocko's Modern Life: Spunky's Dangerous Day",'Super Nintendo');
replace into games(name,console_name) values( "Rocky Rodent",'Super Nintendo');
replace into games(name,console_name) values( "Roger Clemens' MVP Baseball",'Super Nintendo');
replace into games(name,console_name) values( "Romance of the Three Kingdoms II",'Super Nintendo');
replace into games(name,console_name) values( "Romance of the Three Kingdoms III: Dragon of Destiny",'Super Nintendo');
replace into games(name,console_name) values( "Romance of the Three Kingdoms IV: Wall of Fire",'Super Nintendo');
replace into games(name,console_name) values( "RPM Racing",'Super Nintendo');
replace into games(name,console_name) values( "R-Type III: The Third Lightning",'Super Nintendo');
replace into games(name,console_name) values( "Run Saber",'Super Nintendo');
replace into games(name,console_name) values( "Samurai Shodown Samurai Spirits JPN",'Super Nintendo');
replace into games(name,console_name) values( "Saturday Night Slam Masters Muscle Bomber JPN",'Super Nintendo');
replace into games(name,console_name) values( "Scooby-Doo Mystery",'Super Nintendo');
replace into games(name,console_name) values( "SeaQuest DSV",'Super Nintendo');
replace into games(name,console_name) values( "Secret of Evermore",'Super Nintendo');
replace into games(name,console_name) values( "Secret of Mana",'Super Nintendo');
replace into games(name,console_name) values( "Secret of the Stars",'Super Nintendo');
replace into games(name,console_name) values( "Shadowrun",'Super Nintendo');
replace into games(name,console_name) values( "Shanghai II: Dragon's Eye",'Super Nintendo');
replace into games(name,console_name) values( "Shaq Fu",'Super Nintendo');
replace into games(name,console_name) values( "Shien's Revenge",'Super Nintendo');
replace into games(name,console_name) values( "Side Pocket",'Super Nintendo');
replace into games(name,console_name) values( "SimAnt",'Super Nintendo');
replace into games(name,console_name) values( "SimCity",'Super Nintendo');
replace into games(name,console_name) values( "SimCity 2000",'Super Nintendo');
replace into games(name,console_name) values( "SimEarth",'Super Nintendo');
replace into games(name,console_name) values( "The Simpsons: Bart's Nightmare",'Super Nintendo');
replace into games(name,console_name) values( "Sink or Swim",'Super Nintendo');
replace into games(name,console_name) values( "Sküljagger: Revolt of the Westicans",'Super Nintendo');
replace into games(name,console_name) values( "Skyblazer",'Super Nintendo');
replace into games(name,console_name) values( "Smart Ball",'Super Nintendo');
replace into games(name,console_name) values( "Snow White: Happily Ever After",'Super Nintendo');
replace into games(name,console_name) values( "Sonic Blast Man",'Super Nintendo');
replace into games(name,console_name) values( "Sonic Blast Man II",'Super Nintendo');
replace into games(name,console_name) values( "SOS",'Super Nintendo');
replace into games(name,console_name) values( "Soul Blazer",'Super Nintendo');
replace into games(name,console_name) values( "Space Ace",'Super Nintendo');
replace into games(name,console_name) values( "Space Football: One on One",'Super Nintendo');
replace into games(name,console_name) values( "Space Invaders",'Super Nintendo');
replace into games(name,console_name) values( "Spanky's Quest",'Super Nintendo');
replace into games(name,console_name) values( "Sparkster",'Super Nintendo');
replace into games(name,console_name) values( "Spectre",'Super Nintendo');
replace into games(name,console_name) values( "Speed Racer in My Most Dangerous Adventures",'Super Nintendo');
replace into games(name,console_name) values( "Speedy Gonzales: Los Gatos Bandidos",'Super Nintendo');
replace into games(name,console_name) values( "Spider-Man: The Animated Series",'Super Nintendo');
replace into games(name,console_name) values( "Spider-Man and Venom: Maximum Carnage",'Super Nintendo');
replace into games(name,console_name) values( "Spider-Man and the X-Men in Arcade's Revenge",'Super Nintendo');
replace into games(name,console_name) values( "Spindizzy Worlds",'Super Nintendo');
replace into games(name,console_name) values( "The Sporting News: Power Baseball",'Super Nintendo');
replace into games(name,console_name) values( "Star Trek: Deep Space Nine: The Crossroads of Time",'Super Nintendo');
replace into games(name,console_name) values( "Star Trek: Starfleet Academy Starship Bridge Simulator",'Super Nintendo');
replace into games(name,console_name) values( "Star Trek: The Next Generation: Future's Past",'Super Nintendo');
replace into games(name,console_name) values( "Stargate",'Super Nintendo');
replace into games(name,console_name) values( "Steel Talons",'Super Nintendo');
replace into games(name,console_name) values( "Sterling Sharpe: End 2 End",'Super Nintendo');
replace into games(name,console_name) values( "Stone Protectors",'Super Nintendo');
replace into games(name,console_name) values( "Street Fighter II: The World Warrior",'Super Nintendo');
replace into games(name,console_name) values( "Street Fighter II Turbo: Hyper Fighting",'Super Nintendo');
replace into games(name,console_name) values( "Street Hockey '95",'Super Nintendo');
replace into games(name,console_name) values( "Street Racer",'Super Nintendo');
replace into games(name,console_name) values( "Stunt Race FX",'Super Nintendo');
replace into games(name,console_name) values( "Sunset Riders",'Super Nintendo');
replace into games(name,console_name) values( "Super Adventure Island",'Super Nintendo');
replace into games(name,console_name) values( "Super Adventure Island II",'Super Nintendo');
replace into games(name,console_name) values( "Super Baseball 2020",'Super Nintendo');
replace into games(name,console_name) values( "Super Baseball Simulator 1.000",'Super Nintendo');
replace into games(name,console_name) values( "Super Bases Loaded",'Super Nintendo');
replace into games(name,console_name) values( "Super Bases Loaded 2",'Super Nintendo');
replace into games(name,console_name) values( "Super Bases Loaded 3: License to Steal",'Super Nintendo');
replace into games(name,console_name) values( "Super Batter Up",'Super Nintendo');
replace into games(name,console_name) values( "Super Battleship",'Super Nintendo');
replace into games(name,console_name) values( "Super Battletank 2",'Super Nintendo');
replace into games(name,console_name) values( "Super Black Bass",'Super Nintendo');
replace into games(name,console_name) values( "Super Bomberman",'Super Nintendo');
replace into games(name,console_name) values( "Super Bomberman 2",'Super Nintendo');
replace into games(name,console_name) values( "Super Bowling",'Super Nintendo');
replace into games(name,console_name) values( "Super Caesars Palace",'Super Nintendo');
replace into games(name,console_name) values( "Super Castlevania IV",'Super Nintendo');
replace into games(name,console_name) values( "Super Chase H.Q.",'Super Nintendo');
replace into games(name,console_name) values( "Super Conflict",'Super Nintendo');
replace into games(name,console_name) values( "Super Double Dragon",'Super Nintendo');
replace into games(name,console_name) values( "Super Ghouls'n Ghosts",'Super Nintendo');
replace into games(name,console_name) values( "Super Goal! 2",'Super Nintendo');
replace into games(name,console_name) values( "Super Godzilla",'Super Nintendo');
replace into games(name,console_name) values( "Super High Impact",'Super Nintendo');
replace into games(name,console_name) values( "Super Mario All-Stars",'Super Nintendo');
replace into games(name,console_name) values( "Super Mario All-Stars + Super Mario World",'Super Nintendo');
replace into games(name,console_name) values( "Super Mario Kart",'Super Nintendo');
replace into games(name,console_name) values( "Super Mario RPG: Legend of the Seven Stars",'Super Nintendo');
replace into games(name,console_name) values( "Super Mario World",'Super Nintendo');
replace into games(name,console_name) values( "Super Mario World 2: Yoshi's Island",'Super Nintendo');
replace into games(name,console_name) values( "Super Metroid",'Super Nintendo');
replace into games(name,console_name) values( "Super Ninja Boy",'Super Nintendo');
replace into games(name,console_name) values( "Super Nova",'Super Nintendo');
replace into games(name,console_name) values( "Super Off Road",'Super Nintendo');
replace into games(name,console_name) values( "Super Off Road: The Baja",'Super Nintendo');
replace into games(name,console_name) values( "Super Pinball: Behind the Mask",'Super Nintendo');
replace into games(name,console_name) values( "Super Play Action Football",'Super Nintendo');
replace into games(name,console_name) values( "Super Punch-Out!!",'Super Nintendo');
replace into games(name,console_name) values( "Super Putty",'Super Nintendo');
replace into games(name,console_name) values( "Super R.B.I. Baseball",'Super Nintendo');
replace into games(name,console_name) values( "Super R-Type",'Super Nintendo');
replace into games(name,console_name) values( "Super Slam Dunk",'Super Nintendo');
replace into games(name,console_name) values( "Super Slap Shot",'Super Nintendo');
replace into games(name,console_name) values( "Super Smash TV",'Super Nintendo');
replace into games(name,console_name) values( "Super Soccer",'Super Nintendo');
replace into games(name,console_name) values( "Super Solitaire",'Super Nintendo');
replace into games(name,console_name) values( "Super Star Wars",'Super Nintendo');
replace into games(name,console_name) values( "Super Star Wars: The Empire Strikes Back",'Super Nintendo');
replace into games(name,console_name) values( "Super Star Wars: Return of the Jedi",'Super Nintendo');
replace into games(name,console_name) values( "Super Street Fighter II: The New Challengers",'Super Nintendo');
replace into games(name,console_name) values( "Super Strike Eagle",'Super Nintendo');
replace into games(name,console_name) values( "Super Tennis",'Super Nintendo');
replace into games(name,console_name) values( "Super Troll Islands",'Super Nintendo');
replace into games(name,console_name) values( "Super Turrican",'Super Nintendo');
replace into games(name,console_name) values( "Super Turrican 2",'Super Nintendo');
replace into games(name,console_name) values( "Super Valis IV",'Super Nintendo');
replace into games(name,console_name) values( "Super Widget",'Super Nintendo');
replace into games(name,console_name) values( "Suzuka 8 Hours",'Super Nintendo');
replace into games(name,console_name) values( "SWAT Kats: The Radical Squadron",'Super Nintendo');
replace into games(name,console_name) values( "Syndicate",'Super Nintendo');
replace into games(name,console_name) values( "T2: The Arcade Game",'Super Nintendo');
replace into games(name,console_name) values( "Taz-Mania",'Super Nintendo');
replace into games(name,console_name) values( "Tecmo Super Baseball",'Super Nintendo');
replace into games(name,console_name) values( "Tecmo Super Bowl",'Super Nintendo');
replace into games(name,console_name) values( "Tecmo Super Bowl II: Special Edition",'Super Nintendo');
replace into games(name,console_name) values( "Tecmo Super Bowl III: Final Edition",'Super Nintendo');
replace into games(name,console_name) values( "Tecmo Super NBA Basketball",'Super Nintendo');
replace into games(name,console_name) values( "The Terminator",'Super Nintendo');
replace into games(name,console_name) values( "Terminator 2: Judgment Day",'Super Nintendo');
replace into games(name,console_name) values( "Tetris & Dr. Mario",'Super Nintendo');
replace into games(name,console_name) values( "Tetris 2",'Super Nintendo');
replace into games(name,console_name) values( "Tetris Attack",'Super Nintendo');
replace into games(name,console_name) values( "Thomas the Tank Engine & Friends",'Super Nintendo');
replace into games(name,console_name) values( "Thunder Spirits",'Super Nintendo');
replace into games(name,console_name) values( "The Tick",'Super Nintendo');
replace into games(name,console_name) values( "Time Slip",'Super Nintendo');
replace into games(name,console_name) values( "Time Trax",'Super Nintendo');
replace into games(name,console_name) values( "Timecop",'Super Nintendo');
replace into games(name,console_name) values( "Timon & Pumbaa's Jungle Games",'Super Nintendo');
replace into games(name,console_name) values( "Tin Star",'Super Nintendo');
replace into games(name,console_name) values( "Tiny Toon Adventures: Buster Busts Loose",'Super Nintendo');
replace into games(name,console_name) values( "TKO Super Championship Boxing",'Super Nintendo');
replace into games(name,console_name) values( "TNN Bass Tournament of Champions",'Super Nintendo');
replace into games(name,console_name) values( "Todd McFarlane's Spawn: The Video Game",'Super Nintendo');
replace into games(name,console_name) values( "Tom and Jerry",'Super Nintendo');
replace into games(name,console_name) values( "Top Gear",'Super Nintendo');
replace into games(name,console_name) values( "Top Gear 2",'Super Nintendo');
replace into games(name,console_name) values( "Top Gear 3000",'Super Nintendo');
replace into games(name,console_name) values( "Total Carnage",'Super Nintendo');
replace into games(name,console_name) values( "Toy Story",'Super Nintendo');
replace into games(name,console_name) values( "Toys",'Super Nintendo');
replace into games(name,console_name) values( "Troddlers",'Super Nintendo');
replace into games(name,console_name) values( "Troy Aikman NFL Football",'Super Nintendo');
replace into games(name,console_name) values( "True Golf: Wicked 18",'Super Nintendo');
replace into games(name,console_name) values( "True Golf Classics: Pebble Beach Golf Links",'Super Nintendo');
replace into games(name,console_name) values( "True Golf Classics: Waialae Country Club",'Super Nintendo');
replace into games(name,console_name) values( "True Lies",'Super Nintendo');
replace into games(name,console_name) values( "Tuff E Nuff",'Super Nintendo');
replace into games(name,console_name) values( "Turn and Burn: No-Fly Zone",'Super Nintendo');
replace into games(name,console_name) values( "The Twisted Tales of Spike McFang",'Super Nintendo');
replace into games(name,console_name) values( "U.N. Squadron",'Super Nintendo');
replace into games(name,console_name) values( "Ultima: Runes of Virtue II",'Super Nintendo');
replace into games(name,console_name) values( "Ultima VI: The False Prophet",'Super Nintendo');
replace into games(name,console_name) values( "Ultima VII: The Black Gate",'Super Nintendo');
replace into games(name,console_name) values( "Ultimate Fighter",'Super Nintendo');
replace into games(name,console_name) values( "Ultimate Mortal Kombat 3",'Super Nintendo');
replace into games(name,console_name) values( "Ultraman: Towards the Future",'Super Nintendo');
replace into games(name,console_name) values( "Uncharted Waters",'Super Nintendo');
replace into games(name,console_name) values( "Uncharted Waters: New Horizons",'Super Nintendo');
replace into games(name,console_name) values( "Untouchables",'Super Nintendo');
replace into games(name,console_name) values( "Urban Strike",'Super Nintendo');
replace into games(name,console_name) values( "Utopia: The Creation of a Nation",'Super Nintendo');
replace into games(name,console_name) values( "Vegas Stakes",'Super Nintendo');
replace into games(name,console_name) values( "Venom/Spider-Man: Separation Anxiety",'Super Nintendo');
replace into games(name,console_name) values( "Virtual Bart",'Super Nintendo');
replace into games(name,console_name) values( "Vortex",'Super Nintendo');
replace into games(name,console_name) values( "War 2410",'Super Nintendo');
replace into games(name,console_name) values( "War 3010: The Revolution",'Super Nintendo');
replace into games(name,console_name) values( "Wario's Woods",'Super Nintendo');
replace into games(name,console_name) values( "Warlock",'Super Nintendo');
replace into games(name,console_name) values( "WarpSpeed",'Super Nintendo');
replace into games(name,console_name) values( "Wayne Gretzky and the NHLPA All-Stars",'Super Nintendo');
replace into games(name,console_name) values( "Wayne's World",'Super Nintendo');
replace into games(name,console_name) values( "WCW SuperBrawl Wrestling",'Super Nintendo');
replace into games(name,console_name) values( "Weaponlord",'Super Nintendo');
replace into games(name,console_name) values( "We're Back! A Dinosaur's Story",'Super Nintendo');
replace into games(name,console_name) values( "Wheel of Fortune: Featuring Vanna White",'Super Nintendo');
replace into games(name,console_name) values( "Wheel of Fortune Deluxe!",'Super Nintendo');
replace into games(name,console_name) values( "Where in the World Is Carmen Sandiego?",'Super Nintendo');
replace into games(name,console_name) values( "Where in Time is Carmen Sandiego?",'Super Nintendo');
replace into games(name,console_name) values( "Whizz",'Super Nintendo');
replace into games(name,console_name) values( "Wild Guns",'Super Nintendo');
replace into games(name,console_name) values( "WildSnake",'Super Nintendo');
replace into games(name,console_name) values( "Williams Arcade's Greatest Hits",'Super Nintendo');
replace into games(name,console_name) values( "Wing Commander",'Super Nintendo');
replace into games(name,console_name) values( "Wing Commander: The Secret Missions",'Super Nintendo');
replace into games(name,console_name) values( "Winter Olympic Games: Lillehammer '94",'Super Nintendo');
replace into games(name,console_name) values( "The Wizard of Oz",'Super Nintendo');
replace into games(name,console_name) values( "Wizardry V: Heart of the Maelstrom",'Super Nintendo');
replace into games(name,console_name) values( "Wolfchild",'Super Nintendo');
replace into games(name,console_name) values( "Wolfenstein 3D",'Super Nintendo');
replace into games(name,console_name) values( "Wolverine: Adamantium Rage",'Super Nintendo');
replace into games(name,console_name) values( "Wordtris",'Super Nintendo');
replace into games(name,console_name) values( "World Cup USA '94",'Super Nintendo');
replace into games(name,console_name) values( "World Heroes",'Super Nintendo');
replace into games(name,console_name) values( "World Heroes 2",'Super Nintendo');
replace into games(name,console_name) values( "World League Soccer",'Super Nintendo');
replace into games(name,console_name) values( "WWF RAW",'Super Nintendo');
replace into games(name,console_name) values( "WWF Royal Rumble",'Super Nintendo');
replace into games(name,console_name) values( "WWF Super WrestleMania",'Super Nintendo');
replace into games(name,console_name) values( "WWF WrestleMania: The Arcade Game",'Super Nintendo');
replace into games(name,console_name) values( "Xardion",'Super Nintendo');
replace into games(name,console_name) values( "X-Kaliber 2097",'Super Nintendo');
replace into games(name,console_name) values( "X-Men: Mutant Apocalypse",'Super Nintendo');
replace into games(name,console_name) values( "X-Zone",'Super Nintendo');
replace into games(name,console_name) values( "Yoshi's Cookie",'Super Nintendo');
replace into games(name,console_name) values( "Yoshi's Safari",'Super Nintendo');
replace into games(name,console_name) values( "Young Merlin",'Super Nintendo');
replace into games(name,console_name) values( "Ys III: Wanderers from Ys",'Super Nintendo');
replace into games(name,console_name) values( "Zero the Kamikaze Squirrel",'Super Nintendo');
replace into games(name,console_name) values( "Zool",'Super Nintendo');
replace into games(name,console_name) values( "Zoop",'Super Nintendo');
replace into games(name,console_name) values( "16-Bit Xmas 2011 (Unlicensed)",'Super Nintendo');
replace into games(name,console_name) values( "Apocalypse II (Unlicensed)",'Super Nintendo');
replace into games(name,console_name) values( "AstroHawk (Unlicensed)",'Super Nintendo');
replace into games(name,console_name) values( "Classic Kong (Unlicensed)",'Super Nintendo');
replace into games(name,console_name) values( "Corn Buster (Unlicensed)",'Super Nintendo');
replace into games(name,console_name) values( "Creepy Bird (Unlicensed)",'Super Nintendo');
replace into games(name,console_name) values( "Dorke and Ymp (Unlicensed)",'Super Nintendo');
replace into games(name,console_name) values( "Hind Strike (Unlicensed)",'Super Nintendo');
replace into games(name,console_name) values( "Mazezam Challenge (Unlicensed)",'Super Nintendo');
replace into games(name,console_name) values( "Mr. Bloppy Saves the World (Unlicensed)",'Super Nintendo');
replace into games(name,console_name) values( "Nightmare Busters (Unlicensed)",'Super Nintendo');
replace into games(name,console_name) values( "Rockfall (Unlicensed)",'Super Nintendo');
replace into games(name,console_name) values( "Piko Interactive (reprint) (Unlicensed)",'Super Nintendo');
replace into games(name,console_name) values( "Super 4 in 1 Multicart (Unlicensed)",'Super Nintendo');
replace into games(name,console_name) values( "Super Thor Quest (Unlicensed)",'Super Nintendo');
replace into games(name,console_name) values( "UWOL: Quest for Money (Unlicensed)",'Super Nintendo');
