replace into games (name, year, publisher, console_name) values ("A.P.B.","1991","Quicksilver Software","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Awesome Golf","1991","Hand Made Software","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Baseball Heroes","1992","Atari","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Basketbrawl","1992","Atari","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Batman Returns","1992","Atari","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("BattleWheels","1993","Beyond Games","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Battlezone 2000","1995","Hand Made Software","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Bill & Ted's Excellent Adventure","1991","Atari","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Block Out","1991","California Dreams","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Blue Lightning","1989","Epyx","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("California Games","1989","Epyx","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Checkered Flag","1991","Atari","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Chip's Challenge","1989","Epyx","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Crystal Mines II","1992","Color Dreams","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Desert Strike","1993","Teque London","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Dinolympics","1992","Imagitec Design","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Dirty Larry--Renegade Cop","1992","Knight Technologies","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Double Dragon","1993","Knight Technologies","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Dracula - The Undead","1991","Hand Made Software","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Electrocop","1989","Epyx","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("European Soccer Challenge","1993","Krisalis Software","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Fidelity Ultimate Chess Challenge","1991","Telegames","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Gates of Zendocon","1989","Epyx","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Gauntlet: The Third Encounter","1990","Epyx","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Gordo 106","1993","Tenth Planet","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Hard Drivin","1991","NuFX","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Hockey","1992","Alpine Studios","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Hydra","1992","NuFX","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Ishido: The Way of the Stones","1991","California Dreams","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Jimmy Connors Tennis","1993","Hand Made Software","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Joust","1992","Shadowsoft","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Klax","1990","Atari","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Krazy Ace Miniature Golf","1993","Telegames","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Kung Food","1992","Lore Games","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Lemmings","1993","DMA Design","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Lynx Casino","1992","Atari","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Malibu Bikini Volleyball","1993","Hand Made Software","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Ms. Pac-Man","1990","Namco","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("NFL Football","1992","Atari","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Ninja Gaiden","1991","Tecmo","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Ninja Gaiden III: The Ancient Ship of Doom","1993","Tecmo","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Pac-Land","1991","Namco","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Paperboy","1990","Tengen","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Pinball Jam","1992","Midway","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Pit-Fighter","1992","Tengen","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Power Factor","1992","Hand Made Software","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Qix","1991","Knight Technologies","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Rampage","1990","Midway","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Rampart","1992","Tengen","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("RoadBlasters","1990","Tengen","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Robo-Squash","1990","Atari","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Robotron: 2084","1991","Shadowsoft","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Rygar","1990","Tecmo","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("S.T.U.N. Runner","1991","Tengen","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Scrapyard Dog","1991","Creative Software Designs","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Shadow of the Beast","1992","Digital Developments","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Shanghai","1990","Mediagenic","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Steel Talons","1992","NuFX","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Super Asteroids & Missile Command","1995","Atari","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Super Off Road","1993","Tradewest","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Super Skweek","1991","Loriciel","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Switchblade II","1992","Gremlin Graphics","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Todds Adventures in Slime World","1990","Epyx","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Toki","1992","Fabtek","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Tournament Cyberball 2072","1991","Tengen","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Turbo Sub","1991","Atari","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Viking Child","1991","Imagitec Design","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Warbirds","1991","Atari","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("World Class Fussball/Soccer","1992","Atari","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Xenophobe","1990","Midway","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Xybots","1991","Tengen","Atari Lynx");
replace into games (name, year, publisher, console_name) values ("Zarlor Mercenary","1990","Epyx","Atari Lynx");
