replace into games( name, year, publisher, console_name) values ('The Activision Decathlon','1983','Activision','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Astro Chase','1984','Parker Brothers','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Ballblazer','1986','Atari Corp.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Beamrider','1983','Activision','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Berzerk','1983','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Blueprint','1983','CBS Electronics','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Bounty Bob Strikes Back!','1984','Big Five Software','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Buck Rogers: Planet of Zoom','1983','Sega','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Centipede','1982','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Choplifter!','1984','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Congo Bongo','1983','Sega','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Countermeasure','1982','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Defender','1982','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Dig Dug','1983','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('The Dreadnaught Factor','1983','Activision','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Frogger','1983','Parker Brothers','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Frogger II: ThreeeDeep!','1984','Parker Brothers','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Galaxian','1982','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Gorf','1983','CBS Electronics','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Gremlins','1986','Atari Corp.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Gyruss','1984','Parker Brothers','Atari 5200');
replace into games( name, year, publisher, console_name) values ('H.E.R.O.','1984','Activision','Atari 5200');
replace into games( name, year, publisher, console_name) values ('James Bond 007','1984','Parker Brothers','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Joust','1983','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Jungle Hunt','1983','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('K-Razy Shoot-Out','1983','CBS Electronics','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Kaboom!','1983','Activision','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Kangaroo','1983','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Keystone Kapers','1984','Activision','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Mario Bros.','1983','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Megamania','1983','Activision','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Meteorites','1983','Electra Concepts','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Miner 2049er','1983','Big Five Software','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Missile Command','1982','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ("Montezuma's Revenge",'1984','Parker Brothers','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Moon Patrol','1983','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Mountain King','1983','CBS Electronics','Atari 5200');
replace into games( name, year, publisher, console_name) values ("Mr. Do!'s Castle",'1984','Parker Brothers','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Ms. Pac-Man','1983','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Pac-Man','1982','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Pengo','1983','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Pitfall!','1984','Activision','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Pitfall II: Lost Caverns','1984','Activision','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Pole Position','1983','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Popeye','1983','Parker Brothers','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Q*bert','1983','Parker Brothers','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Qix','1982','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Quest for Quintana Roo','1984','Sunrise Software','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Realsports Baseball','1982','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Realsports Football','1982','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Realsports Soccer','1982','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Realsports Tennis','1982','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Rescue on Fractalus!','1986','Atari Corp.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('River Raid','1983','Activision','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Robotron: 2084','1983','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Space Dungeon','1983','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Space Invaders','1982','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Space Shuttle','1983','Activision','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Star Raiders','1982','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Star Trek: Strategic Operations Simulator','1983','Sega','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Star Wars: Return of the Jedi Death Star Battle','1983','Parker Brothers','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Star Wars: The Arcade Game','1983','Parker Brothers','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Super Breakout','1982','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Super Cobra','1983','Parker Brothers','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Vanguard','1983','Atari, Inc.','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Wizard of Wor','1983','CBS Electronics','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Zaxxon','1984','Sega','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Zenji','1984','Activision','Atari 5200');
replace into games( name, year, publisher, console_name) values ('Zone Ranger','1984','Activision','Atari 5200');
