replace into games (name,publisher,year,console_name) values ("Games[edit]","","","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Title","Developer(s)","","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("ELSPA/","","","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("CERO rating","Genre","","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("AeroWings","CRI","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Airforce Delta","Konami Computer Entertainment Studios","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Blue Stinger","Climax Graphics","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("CART Flag To Flag","Zoom","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Expendable","Rage Software","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("The House of the Dead 2","AM1","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Hydro Thunder","Eurocom","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Monaco Grand Prix","Ubisoft","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Mortal Kombat Gold","Eurocom","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("NFL 2K","Visual Concepts","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("NFL Blitz 2000","Avalanche Software","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Pen Pen TriIcelon","General Entertainment","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Power Stone","Capcom","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Ready 2 Rumble Boxing","Midway","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Sonic Adventure","Sonic Team","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Soulcalibur","Namco","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("TNN Motorsports HardCore Heat","CRI","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Tokyo Xtreme Racer","Genki","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("TrickStyle","Criterion Games","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Jeremy McGrath Supercross 2000","Acclaim","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("The King of Fighters: Dream Match 1999","SNK","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Marvel vs. Capcom: Clash of Super Heroes","Capcom","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Sega Bass Fishing","Sims","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Time Stalkers","Climax Entertainment","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Toy Commander","No Cliche","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Speed Devils","Ubisoft Montreal","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Virtua Fighter 3tb","Genki","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Armada","Metro3D","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Centipede","Hasbro Interactive","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Dynamite Cop","Sega","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Jojo's Bizarre Adventure","Capcom","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Maken X","ATLUS","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("NBA Showtime: NBA on NBC","Avalanche Software","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("NFL Quarterback Club 2000","Acclaim","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Psychic Force 2012","Taito Corporation","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Sega Rally Championship 2","Sega AM3","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Slave Zero","Accolade","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Soul Fighter","Toka","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("South Park: Chef's Luv Shack","Acclaim","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("NBA 2K","Visual Concepts","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Rippin' Riders","UEP Systems","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("WWF Attitude","Acclaim","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Suzuki Alstare Extreme Racing","Criterion Games","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Fighting Force 2","Core Design","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Incoming","Rage Software","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Shadow Man","Acclaim","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Test Drive 6","Pitbull Syndicate","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Vigilante 8: 2nd Offense","Luxoflux, Inc.","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Worms Armageddon","Team17","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Evolution","Sting","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Re-Volt","Titanium Studios","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Elemental Gimmick Gear","Birthday","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Tee Off","Bottom Up","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Wetrix+","Crystal Dynamics","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Zombie Revenge","Sega","1999","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Sega Swirl","Tremor Entertainment","","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Seventh Cross Evolution","Atypical Alchemists Associate","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Crazy Taxi","Hitmaker","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Legacy of Kain: Soul Reaver","Crystal Dynamics","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Carrier","Jaleco Entertainment","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Wild Metal","DMA Design","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("NHL 2K","Black Box","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("ChuChu Rocket!","Sonic Team","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Dead or Alive 2","Team Ninja","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("ECW Hardcore Revolution","Acclaim","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Rayman 2: The Great Escape","Ubisoft Montpellier","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Resident Evil Code: Veronica","Capcom","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Sword of the Berserk: Guts' Rage","ASCII Entertainment","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Virtua Striker 2","Sega","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("MDK2","BioWare","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Plasma Sword: Nightmare of Bilstein","Capcom","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Tech Romancer","Capcom","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Star Wars Episode I Racer","LucasArts","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("F1 World Grand Prix","Video System","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Gundam Side Story 0079: Rise from the Ashes","Psikyo","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Grand Theft Auto 2","DMA Design","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("4 Wheel Thunder","Kalisto Entertainment","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Tom Clancy's Rainbow Six","Pipe Dream Interactive","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Gauntlet Legends","Atari Games (Midway)","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Bust-A-Move 4","Taito Corporation","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Street Fighter Alpha 3","Capcom","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Striker Pro 2000","Rage Software","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Cyber Troopers Virtual-On Oratorio Tangram","Sega","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Industrial Spy: Operation Espionage","NEC Interchannel","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Space Channel 5","UGA","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Nightmare Creatures II","Kalisto","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Super Magnetic Neo","Genki","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Street Fighter III: Double Impact","Capcom","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Draconus: Cult of the Wyrm","Treyarch","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Omikron: The Nomad Soul","Quantic Dream","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Mr. Driller","Namco","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Namco Museum","Mass Media","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Wacky Races","Infogrames","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Midway's Greatest Hits Volume 1","Digital Eclipse","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Evolution 2","Sting","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Marvel vs. Capcom 2","Capcom","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Silver","Spiral House","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Tony Hawk's Pro Skater","Treyarch","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Disney/Pixar Toy Story 2: Buzz Lightyear to the Rescue","Traveller's Tales","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Railroad Tycoon II","Tremor Entertainment","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("South Park Rally","Tantalus Interactive","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Test Drive V-Rally","Pitbull Syndicate","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Hidden & Dangerous","Illusion Softworks","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Fur Fighters","Bizarre Creations","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Virtua Tennis","Hitmaker","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Mag Force Racing","VCC Entertainment","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("World Series Baseball 2K1","Visual Concepts","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Giga Wing","Capcom","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Walt Disney World Quest: Magical Racing Tour","Crystal Dynamics","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("NFL QB Club 2001","High Voltage Software","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Spirit of Speed 1937","Broadsword Interactive","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("WWF Royal Rumble","Yuke's","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Seaman","Vivarium","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Sega Marine Fishing","Wow Entertainment","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("D2","WARP","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Deep Fighter","Criterion Games","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("The Ring: Terror's Realm","Asmik Ace Entertainment","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Power Stone 2","Capcom","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("AeroWings 2: Air Strike","CRI","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Sega GT","TOSE","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Ultimate Fighting Championship","Anchor","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Sydney 2000","Attention to Detail","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Tokyo Xtreme Racer 2","Genki","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("San Francisco Rush 2049","Midway","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("NFL 2K1","Visual Concepts","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Ecco the Dolphin: Defender of the Future","Appaloosa Interactive","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("NFL Blitz 2001","Avalanche Software","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("F355 Challenge","Sega","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Caesars Palace 2000: Millennium Gold Edition","Runecraft","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Disney/Pixar Buzz Lightyear of Star Command","Traveller's Tales","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("ESPN International Track & Field","Konami","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Hoyle Casino","Sierra Entertainment","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Frogger 2: Swampy's Revenge","Hasbro Interactive","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Spawn: In the Demon's Hand","Capcom","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Street Fighter III: 3rd Strike","Capcom","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Samba de Amigo","Sonic Team","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Star Wars Episode I: Jedi Power Battles","LucasArts","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Quake III Arena","Raster","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Demolition Racer: No Exit","Pitbull Syndicate","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Ready 2 Rumble Boxing: Round 2","Midway","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Silent Scope","Konami","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Spec Ops II: Omega Squad","Runecraft","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Super Runabout: San Francisco Edition","Climax Entertainment","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("KISS: Psycho Circus: The Nightmare Child","Tremor Entertainment","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("4x4 Evolution","Terminal Reality","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Army Men: Sarge's Heroes","Saffire","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Jet Grind Radio","Smilebit","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("The Grinch","Artificial Mind and Movement","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Red Dog: Superior Firepower","Argonaut Games","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("NBA 2K1","Visual Concepts","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Tony Hawk's Pro Skater 2","Treyarch","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Shenmue","Sega AM2","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Capcom vs. SNK","Psikyo","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("MTV Sports: Skateboarding Featuring Andy MacDonald","Darkblack","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Chicken Run","Blitz Games","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Ms. Pac-Man Maze Madness","Namco","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Skies of Arcadia","Overworks","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Sonic Shuffle","Sonic Team","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Test Drive Le Mans","Pitbull Syndicate","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Urban Chaos","Mucky Foot Productions","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Cannon Spike","Psikyo","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Dino Crisis","Capcom","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Disney's 102 Dalmatians: Puppies to the Rescue","Crystal Dynamics","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Gunbird 2","Psikyo","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Resident Evil 3: Nemesis","Capcom","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Star Wars: Demolition","Luxoflux, Inc.","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Tomb Raider: Chronicles","Core Design","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Dave Mirra Freestyle BMX","Z-Axis, Ltd.","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("ESPN NBA 2Night","Konami","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Tom Clancy's Rainbow Six: Rogue Spear","Pipe Dream Interactive","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Roadsters","UEP Systems","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Disney's Dinosaur","Disney Interactive Studios","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Looney Tunes: Space Race","Melbourne House","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("StarLancer","Digital Anvil","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Xtreme Sports","Innerloop","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Q*Bert","Artech Digital Entertainment","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Sno-Cross Championship Racing","UDS","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Who Wants to Beat Up a Millionaire?","Hypnotix","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Maximum Pool","Dynamix","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("POD: Speedzone","Capcom","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Grandia 2","Game Arts","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Prince of Persia: Arabian Nights","Avalanche Software","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Resident Evil 2","Capcom","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Coaster Works","Bimboosoft","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Championship Surfer","Krome Studios","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Disney's Donald Duck: Goin' Quackers","Ubisoft Montreal","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Speed Devils: Online Racing","Ubisoft Montreal","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Evil Dead: Hail to the King","Heavy Iron Studios","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Bang! Gunship Elite","Rayland Interactive","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("The Next Tetris: On-line Edition","Blue Planet Software","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Vanishing Point","Clockwork Games","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("ECW Anarchy Rulz","Acclaim","2000","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Metropolis Street Racer","Bizarre Creations","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("The Typing of the Dead","Smilebit","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Phantasy Star Online","Sonic Team","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Sega Smash Pack Vol. 1","Sega","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Iron Aces","Marionette","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Charge 'N Blast","Sims","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Ducati World Racing Challenge","Attention to Detail","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Kao the Kangaroo","X-Ray Interactive","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("NBA Hoopz","Eurocom","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Record of Lodoss War: Advent of Cardice","Neverland","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Surf Rocket Racers","CRI","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Daytona USA","Amusement Vision","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Unreal Tournament","Secret Level","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Bangai-O","Treasure","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Tomb Raider: The Last Revelation","Core Design","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Illbleed","Crazy Games","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Spider-Man","Treyarch","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Mars Matrix","Takumi Corporation","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("The King of Fighters '99: Evolution","SNK","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Confidential Mission","Hitmaker","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Giga Wing 2","Takumi Corporation","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Project Justice","Capcom","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("18 Wheeler: American Pro Trucker","Sega","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Crazy Taxi 2","Hitmaker","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Max Steel: Covert Missions","Treyarch","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Worms World Party","Team17","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Sonic Adventure 2","Sonic Team","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Stupid Invaders","Xilam","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Atari Anniversary Edition","Digital Eclipse","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Sports Jam","Wow Entertainment","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Outtrigger","Sega AM2","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Soldier of Fortune","Runecraft","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Reel Fishing: Wild","West One","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Floigan Bros. Episode 1","Visual Concepts","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("World Series Baseball 2K2","Visual Concepts","","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Death Crimson OX","Ecole","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("The Last Blade 2: Heart of the Samurai","SNK","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Razor Freestyle Scooter","Titanium Studios","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Alien Front Online","Sega","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Dragon Riders: Chronicles of Pern","Ubisoft","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Virtua Athlete 2000","Hitmaker","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Sega Bass Fishing 2","Wow Entertainment","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("NCAA College Football 2K2","Visual Concepts","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Mat Hoffman's Pro BMX","Runecraft","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Heavy Metal: Geomatrix","Capcom","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Ooga Booga","Quantic Dream","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("NFL 2K2","Visual Concepts","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Alone in the Dark: The New Nightmare","Darkworks","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Phantasy Star Online Ver. 2","Sonic Team","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("NBA 2K2","Visual Concepts","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Tennis 2K2","Hitmaker","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Bomberman Online","Hudson Soft","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Midway's Greatest Hits Volume 2","Digital Eclipse","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Fatal Fury: Mark of the Wolves","SNK","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Conflict Zone","MASA Group","2001","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("NHL 2K2","Treyarch","2002","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Feet of Fury","Crytpic Allusion, LLC","2003","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Inhabitants","S+F Productions","2005","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Cool Herders","HarmlessLion","2005","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Irides: Master of Blocks","Mad Peet","2005","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Sturmwind","Duranik","2013","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Redux: Dark Matters","","2014","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Ghost Blade","Hucast Games","2015","Sega Dreamcast");
replace into games (name,publisher,year,console_name) values ("Pier Solar and the Great Architects","Watermelon","2015","Sega Dreamcast");
