replace into games (name,console_name) values ( '3 Ninjas Kick Back', 'Genesis');
replace into games (name,console_name) values ( '6-Pak', 'Genesis');
replace into games (name,console_name) values ( '688 Attack Sub', 'Genesis');
replace into games (name,console_name) values ( 'A Dinosaurs Tale', 'Genesis');
replace into games (name,console_name) values ( 'ATP Tour Championship Tennis', 'Genesis');
replace into games (name,console_name) values ( 'AWS Pro Moves Soccer', 'Genesis');
replace into games (name,console_name) values ( 'Aaahh!!! Real Monsters', 'Genesis');
replace into games (name,console_name) values ( 'Aero the Acro-Bat', 'Genesis');
replace into games (name,console_name) values ( 'Aero the Acro-Bat 2', 'Genesis');
replace into games (name,console_name) values ( 'Aerobi', 'Genesis');
replace into games (name,console_name) values ( 'Aerobiz Supersonic', 'Genesis');
replace into games (name,console_name) values ( 'After Burner II', 'Genesis');
replace into games (name,console_name) values ( 'Air Buster: Trouble Specialty Raid Unit', 'Genesis');
replace into games (name,console_name) values ( 'Air Diver', 'Genesis');
replace into games (name,console_name) values ( 'Al Michaels Announces HardBall III', 'Genesis');
replace into games (name,console_name) values ( 'Alex Kidd in the Enchanted Castle', 'Genesis');
replace into games (name,console_name) values ( 'Alien 3', 'Genesis');
replace into games (name,console_name) values ( 'Alien Storm (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Alisia Dragoon', 'Genesis');
replace into games (name,console_name) values ( 'Altered Beast', 'Genesis');
replace into games (name,console_name) values ( 'American Gladiators', 'Genesis');
replace into games (name,console_name) values ( 'Andre Agassi Tennis', 'Genesis');
replace into games (name,console_name) values ( 'Animaniacs', 'Genesis');
replace into games (name,console_name) values ( 'Another World', 'Genesis');
replace into games (name,console_name) values ( 'Arcade Classics', 'Genesis');
replace into games (name,console_name) values ( 'Arch Rivals', 'Genesis');
replace into games (name,console_name) values ( 'Arcus Odyssey', 'Genesis');
replace into games (name,console_name) values ( 'Ariel the Little Mermaid', 'Genesis');
replace into games (name,console_name) values ( 'Arnold Palmer Tournament Golf', 'Genesis');
replace into games (name,console_name) values ( 'Arrow Flash', 'Genesis');
replace into games (name,console_name) values ( 'Art Alive!', 'Genesis');
replace into games (name,console_name) values ( 'Art of Fighting', 'Genesis');
replace into games (name,console_name) values ( 'Astérix and the Great Rescue (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Atomic Robo-Kid', 'Genesis');
replace into games (name,console_name) values ( 'Atomic Runner', 'Genesis');
replace into games (name,console_name) values ( 'Awesome Possum Kicks Dr. Machinos Butt!', 'Genesis');
replace into games (name,console_name) values ( 'Ayrton Sennas Super Monaco GP II', 'Genesis');
replace into games (name,console_name) values ( 'B.O.B.', 'Genesis');
replace into games (name,console_name) values ( 'Back to the Future Part III', 'Genesis');
replace into games (name,console_name) values ( 'Ballz 3D', 'Genesis');
replace into games (name,console_name) values ( 'Barbie Super Model', 'Genesis');
replace into games (name,console_name) values ( 'Barkley Shut Up and Jam 2', 'Genesis');
replace into games (name,console_name) values ( 'Barkley Shut Up and Jam!', 'Genesis');
replace into games (name,console_name) values ( 'Barneys Hide & Seek Game', 'Genesis');
replace into games (name,console_name) values ( 'Bass Masters Classic', 'Genesis');
replace into games (name,console_name) values ( 'Bass Masters Classic: Pro Edition', 'Genesis');
replace into games (name,console_name) values ( 'Batman', 'Genesis');
replace into games (name,console_name) values ( 'Batman Forever (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Batman Returns (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Batman: Revenge of The Joker', 'Genesis');
replace into games (name,console_name) values ( 'Battle Squadron', 'Genesis');
replace into games (name,console_name) values ( 'Battlemaster', 'Genesis');
replace into games (name,console_name) values ( 'Battletech: A Game of Armored Combat', 'Genesis');
replace into games (name,console_name) values ( 'Battletoads', 'Genesis');
replace into games (name,console_name) values ( 'Battletoads & Double Dragon: The Ultimate Team', 'Genesis');
replace into games (name,console_name) values ( 'Beast Wrestler', 'Genesis');
replace into games (name,console_name) values ( 'Beauty and the Beast: Belles Quest', 'Genesis');
replace into games (name,console_name) values ( 'Beauty and the Beast: Roar of the Beast', 'Genesis');
replace into games (name,console_name) values ( 'Beavis and Butt-Head (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Best of the Best: Championship Karate', 'Genesis');
replace into games (name,console_name) values ( 'Bill Walsh College Football', 'Genesis');
replace into games (name,console_name) values ( 'Bill Walsh College Football 95', 'Genesis');
replace into games (name,console_name) values ( 'Bimini Run', 'Genesis');
replace into games (name,console_name) values ( 'Bio-Hazard Battle', 'Genesis');
replace into games (name,console_name) values ( 'Blades of Vengeance', 'Genesis');
replace into games (name,console_name) values ( 'Blaster Master 2', 'Genesis');
replace into games (name,console_name) values ( 'Blockbuster World Video Game Championship II', 'Genesis');
replace into games (name,console_name) values ( 'Blockout', 'Genesis');
replace into games (name,console_name) values ( 'Bloodshot', 'Genesis');
replace into games (name,console_name) values ( 'Bonanza Bros.', 'Genesis');
replace into games (name,console_name) values ( 'Bonkers', 'Genesis');
replace into games (name,console_name) values ( 'Boogerman: A Pick and Flick Adventure', 'Genesis');
replace into games (name,console_name) values ( 'Boxing Legends of The Ring', 'Genesis');
replace into games (name,console_name) values ( 'Bram Stokers Dracula (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Brett Hull Hockey 95', 'Genesis');
replace into games (name,console_name) values ( 'Brutal: Paws of Fury', 'Genesis');
replace into games (name,console_name) values ( 'Bubba N Stix', 'Genesis');
replace into games (name,console_name) values ( 'Bubble and Squeak', 'Genesis');
replace into games (name,console_name) values ( 'Bubsy II', 'Genesis');
replace into games (name,console_name) values ( 'Bubsy in Claws Encounters of the Furred Kind', 'Genesis');
replace into games (name,console_name) values ( 'Buck Rogers: Countdown to Doomsday', 'Genesis');
replace into games (name,console_name) values ( 'Budokan: The Martial Spirit', 'Genesis');
replace into games (name,console_name) values ( 'Bugs Bunny in Double Trouble', 'Genesis');
replace into games (name,console_name) values ( 'Bulls versus Blazers and the NBA Playoffs', 'Genesis');
replace into games (name,console_name) values ( 'Bulls vs Lakers and the NBA Playoffs', 'Genesis');
replace into games (name,console_name) values ( 'Burning Force', 'Genesis');
replace into games (name,console_name) values ( 'Cadash', 'Genesis');
replace into games (name,console_name) values ( 'Caesars Palace', 'Genesis');
replace into games (name,console_name) values ( 'Cal Ripken Jr. Baseball', 'Genesis');
replace into games (name,console_name) values ( 'Caliber.50', 'Genesis');
replace into games (name,console_name) values ( 'California Games', 'Genesis');
replace into games (name,console_name) values ( 'Captain America and the Avengers', 'Genesis');
replace into games (name,console_name) values ( 'Castle of Illusion Starring Mickey Mouse (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Castlevania: Bloodlines', 'Genesis');
replace into games (name,console_name) values ( 'Centurion: Defender of Rome', 'Genesis');
replace into games (name,console_name) values ( 'Chakan', 'Genesis');
replace into games (name,console_name) values ( 'Champions World Class Soccer', 'Genesis');
replace into games (name,console_name) values ( 'Championship Bowling', 'Genesis');
replace into games (name,console_name) values ( 'Championship Pool', 'Genesis');
replace into games (name,console_name) values ( 'Championship Pro-Am', 'Genesis');
replace into games (name,console_name) values ( 'Chase H.Q. II', 'Genesis');
replace into games (name,console_name) values ( 'Chester Cheetah: Too Cool to Fool', 'Genesis');
replace into games (name,console_name) values ( 'Chester Cheetah: Wild Wild Quest', 'Genesis');
replace into games (name,console_name) values ( 'Chi Chis Pro Challenge Golf', 'Genesis');
replace into games (name,console_name) values ( 'Chiki Chiki Boys', 'Genesis');
replace into games (name,console_name) values ( 'Chuck Rock', 'Genesis');
replace into games (name,console_name) values ( 'Chuck Rock II: Son of Chuck', 'Genesis');
replace into games (name,console_name) values ( 'ClayFighter', 'Genesis');
replace into games (name,console_name) values ( 'Cliffhanger', 'Genesis');
replace into games (name,console_name) values ( 'Clue', 'Genesis');
replace into games (name,console_name) values ( 'Coach K College Basketball', 'Genesis');
replace into games (name,console_name) values ( 'College Football USA 96', 'Genesis');
replace into games (name,console_name) values ( 'College Football USA 97', 'Genesis');
replace into games (name,console_name) values ( 'College Footballs National Championship', 'Genesis');
replace into games (name,console_name) values ( 'College Footballs National Championship II', 'Genesis');
replace into games (name,console_name) values ( 'College Slam', 'Genesis');
replace into games (name,console_name) values ( 'Columns', 'Genesis');
replace into games (name,console_name) values ( 'Columns III: Revenge of Columns', 'Genesis');
replace into games (name,console_name) values ( 'Combat Cars', 'Genesis');
replace into games (name,console_name) values ( 'Comix Zone', 'Genesis');
replace into games (name,console_name) values ( 'Contra: Hard Corps', 'Genesis');
replace into games (name,console_name) values ( 'Cool Spot', 'Genesis');
replace into games (name,console_name) values ( 'Corporation', 'Genesis');
replace into games (name,console_name) values ( 'Cosmic Spacehead', 'Genesis');
replace into games (name,console_name) values ( 'Crack Down', 'Genesis');
replace into games (name,console_name) values ( 'Cross Fire', 'Genesis');
replace into games (name,console_name) values ( 'Crusader of Centy', 'Genesis');
replace into games (name,console_name) values ( 'Crystals Pony Tale', 'Genesis');
replace into games (name,console_name) values ( 'Crüe Ball', 'Genesis');
replace into games (name,console_name) values ( 'Cutthroat Island', 'Genesis');
replace into games (name,console_name) values ( 'CyberBall', 'Genesis');
replace into games (name,console_name) values ( 'Cyborg Justice', 'Genesis');
replace into games (name,console_name) values ( 'DJ Boy', 'Genesis');
replace into games (name,console_name) values ( 'Daikoukai Jidai II', 'Genesis');
replace into games (name,console_name) values ( 'Darius II', 'Genesis');
replace into games (name,console_name) values ( 'Dark Castle', 'Genesis');
replace into games (name,console_name) values ( 'Dashin Desperadoes', 'Genesis');
replace into games (name,console_name) values ( 'David Cranes Amazing Tennis', 'Genesis');
replace into games (name,console_name) values ( 'David Robinsons Supreme Court', 'Genesis');
replace into games (name,console_name) values ( 'Davis Cup Tennis', 'Genesis');
replace into games (name,console_name) values ( 'Deadly Moves', 'Genesis');
replace into games (name,console_name) values ( 'Death Duel', 'Genesis');
replace into games (name,console_name) values ( 'Decap Attack', 'Genesis');
replace into games (name,console_name) values ( 'Demolition Man', 'Genesis');
replace into games (name,console_name) values ( 'Desert Demolition Starring Road Runner and Wile E. Coyote', 'Genesis');
replace into games (name,console_name) values ( 'Desert Strike: Return to the Gulf', 'Genesis');
replace into games (name,console_name) values ( 'Devilish: The Next Possession', 'Genesis');
replace into games (name,console_name) values ( 'Dick Tracy', 'Genesis');
replace into games (name,console_name) values ( 'Dick Vitales "Awesome, Baby!" College Hoops', 'Genesis');
replace into games (name,console_name) values ( 'Dino Land', 'Genesis');
replace into games (name,console_name) values ( 'Dinosaurs for Hire', 'Genesis');
replace into games (name,console_name) values ( 'Disneys Aladdin', 'Genesis');
replace into games (name,console_name) values ( 'Doom Troopers', 'Genesis');
replace into games (name,console_name) values ( 'Double Dragon', 'Genesis');
replace into games (name,console_name) values ( 'Double Dragon 3: The Rosetta Stone', 'Genesis');
replace into games (name,console_name) values ( 'Double Dragon V: The Shadow Falls', 'Genesis');
replace into games (name,console_name) values ( 'Dr. Robotniks Mean Bean Machine', 'Genesis');
replace into games (name,console_name) values ( 'Dragon: The Bruce Lee Story', 'Genesis');
replace into games (name,console_name) values ( 'Dragons Fury', 'Genesis');
replace into games (name,console_name) values ( 'Dragons Revenge', 'Genesis');
replace into games (name,console_name) values ( 'Dune II: Battle for Arrakis', 'Genesis');
replace into games (name,console_name) values ( 'Dungeons & Dragons: Warriors of the Eternal Sun', 'Genesis');
replace into games (name,console_name) values ( 'Dynamite Duke', 'Genesis');
replace into games (name,console_name) values ( 'Dynamite Headdy', 'Genesis');
replace into games (name,console_name) values ( 'ESPN Baseball Tonight', 'Genesis');
replace into games (name,console_name) values ( 'ESPN National Hockey Night', 'Genesis');
replace into games (name,console_name) values ( 'ESPN Speedworld', 'Genesis');
replace into games (name,console_name) values ( 'ESPN Sunday Night NFL', 'Genesis');
replace into games (name,console_name) values ( 'ESWAT: City Under Siege', 'Genesis');
replace into games (name,console_name) values ( 'Earnest Evans', 'Genesis');
replace into games (name,console_name) values ( 'Earthworm Jim', 'Genesis');
replace into games (name,console_name) values ( 'Earthworm Jim 2', 'Genesis');
replace into games (name,console_name) values ( 'Ecco Jr.', 'Genesis');
replace into games (name,console_name) values ( 'Ecco the Dolphin', 'Genesis');
replace into games (name,console_name) values ( 'Ecco: The Tides of Time', 'Genesis');
replace into games (name,console_name) values ( 'El Viento', 'Genesis');
replace into games (name,console_name) values ( 'Elemental Master', 'Genesis');
replace into games (name,console_name) values ( 'Eternal Champions', 'Genesis');
replace into games (name,console_name) values ( 'Evander Holyfields Real Deal Boxing', 'Genesis');
replace into games (name,console_name) values ( 'Ex-Mutants', 'Genesis');
replace into games (name,console_name) values ( 'Exile', 'Genesis');
replace into games (name,console_name) values ( 'Exo Squad', 'Genesis');
replace into games (name,console_name) values ( 'F-117 Night Storm', 'Genesis');
replace into games (name,console_name) values ( 'F-15 Strike Eagle II', 'Genesis');
replace into games (name,console_name) values ( 'F-22 Interceptor: Advanced Tactical Fighter', 'Genesis');
replace into games (name,console_name) values ( 'F1', 'Genesis');
replace into games (name,console_name) values ( 'FIFA 97: Gold Edition', 'Genesis');
replace into games (name,console_name) values ( 'FIFA International Soccer', 'Genesis');
replace into games (name,console_name) values ( 'FIFA Soccer 95', 'Genesis');
replace into games (name,console_name) values ( 'FIFA Soccer 96', 'Genesis');
replace into games (name,console_name) values ( 'Family Feud', 'Genesis');
replace into games (name,console_name) values ( 'Fantasia', 'Genesis');
replace into games (name,console_name) values ( 'Fantastic Dizzy', 'Genesis');
replace into games (name,console_name) values ( 'Fatal Fury', 'Genesis');
replace into games (name,console_name) values ( 'Fatal Fury 2', 'Genesis');
replace into games (name,console_name) values ( 'Fatal Labyrinth', 'Genesis');
replace into games (name,console_name) values ( 'Fatal Rewind', 'Genesis');
replace into games (name,console_name) values ( 'Ferrari Grand Prix Challenge', 'Genesis');
replace into games (name,console_name) values ( 'Fever Pitch Soccer', 'Genesis');
replace into games (name,console_name) values ( 'Fighting Masters', 'Genesis');
replace into games (name,console_name) values ( 'Final Zone', 'Genesis');
replace into games (name,console_name) values ( 'Fire Shark', 'Genesis');
replace into games (name,console_name) values ( 'Flashback', 'Genesis');
replace into games (name,console_name) values ( 'Flicky', 'Genesis');
replace into games (name,console_name) values ( 'Foreman for Real', 'Genesis');
replace into games (name,console_name) values ( 'Forgotten Worlds', 'Genesis');
replace into games (name,console_name) values ( 'Frank Thomas Big Hurt Baseball', 'Genesis');
replace into games (name,console_name) values ( 'Frogger', 'Genesis');
replace into games (name,console_name) values ( 'Fun n Games', 'Genesis');
replace into games (name,console_name) values ( 'G-LOC: Air Battle', 'Genesis');
replace into games (name,console_name) values ( 'Gaiares', 'Genesis');
replace into games (name,console_name) values ( 'Gain Ground', 'Genesis');
replace into games (name,console_name) values ( 'Galaxy Force II', 'Genesis');
replace into games (name,console_name) values ( 'Garfield: Caught in the Act', 'Genesis');
replace into games (name,console_name) values ( 'Gargoyles', 'Genesis');
replace into games (name,console_name) values ( 'Garry Kitchens Super Battletank: War in the Gulf', 'Genesis');
replace into games (name,console_name) values ( 'Gauntlet IV', 'Genesis');
replace into games (name,console_name) values ( 'Gemfire', 'Genesis');
replace into games (name,console_name) values ( 'General Chaos', 'Genesis');
replace into games (name,console_name) values ( 'Generations Lost', 'Genesis');
replace into games (name,console_name) values ( 'Genghis Khan II: Clan of the Gray Wolf', 'Genesis');
replace into games (name,console_name) values ( 'George Foremans KO Boxing', 'Genesis');
replace into games (name,console_name) values ( 'Ghostbusters (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Ghoulsn Ghosts', 'Genesis');
replace into games (name,console_name) values ( 'Gods', 'Genesis');
replace into games (name,console_name) values ( 'Golden Axe', 'Genesis');
replace into games (name,console_name) values ( 'Golden Axe II', 'Genesis');
replace into games (name,console_name) values ( 'Goofys Hysterical History Tour', 'Genesis');
replace into games (name,console_name) values ( 'Granada', 'Genesis');
replace into games (name,console_name) values ( 'GrandSlam: The Tennis Tournament 92', 'Genesis');
replace into games (name,console_name) values ( 'Greatest Heavyweights', 'Genesis');
replace into games (name,console_name) values ( 'Greendog: The Beached Surfer Dude!', 'Genesis');
replace into games (name,console_name) values ( 'Grind Stormer', 'Genesis');
replace into games (name,console_name) values ( 'Growl', 'Genesis');
replace into games (name,console_name) values ( 'Gunstar Heroes', 'Genesis');
replace into games (name,console_name) values ( 'Gynoug', 'Genesis');
replace into games (name,console_name) values ( 'Hard Drivin', 'Genesis');
replace into games (name,console_name) values ( 'HardBall 94', 'Genesis');
replace into games (name,console_name) values ( 'HardBall 95', 'Genesis');
replace into games (name,console_name) values ( 'Haunting Starring Polterguy', 'Genesis');
replace into games (name,console_name) values ( 'Heavy Nova', 'Genesis');
replace into games (name,console_name) values ( 'Hellfire', 'Genesis');
replace into games (name,console_name) values ( 'Herzog Zwei', 'Genesis');
replace into games (name,console_name) values ( 'High Seas Havoc', 'Genesis');
replace into games (name,console_name) values ( 'Hit the Ice', 'Genesis');
replace into games (name,console_name) values ( 'Home Alone', 'Genesis');
replace into games (name,console_name) values ( 'Home Alone 2: Lost in New York', 'Genesis');
replace into games (name,console_name) values ( 'Hook', 'Genesis');
replace into games (name,console_name) values ( 'Hyper Dunk: The Playoff Edition', 'Genesis');
replace into games (name,console_name) values ( 'IMG International Tour Tennis', 'Genesis');
replace into games (name,console_name) values ( 'Indiana Jones and the Last Crusade', 'Genesis');
replace into games (name,console_name) values ( 'Insector X', 'Genesis');
replace into games (name,console_name) values ( 'Instruments of Chaos Starring Young Indiana Jones', 'Genesis');
replace into games (name,console_name) values ( 'Izzys Quest for the Olympic Rings', 'Genesis');
replace into games (name,console_name) values ( 'Jack Nicklaus Power Challenge Golf', 'Genesis');
replace into games (name,console_name) values ( 'James Bond 007: The Duel', 'Genesis');
replace into games (name,console_name) values ( 'James Buster Douglas Knockout Boxing (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'James Pond 3: Operation Starfish', 'Genesis');
replace into games (name,console_name) values ( 'James Pond II: Codename RoboCod', 'Genesis');
replace into games (name,console_name) values ( 'James Pond: Underwater Agent', 'Genesis');
replace into games (name,console_name) values ( 'Jammit', 'Genesis');
replace into games (name,console_name) values ( 'Jeopardy! (GameTek)', 'Genesis');
replace into games (name,console_name) values ( 'Jeopardy! Sports Edition', 'Genesis');
replace into games (name,console_name) values ( 'Jeopardy!: Deluxe Edition', 'Genesis');
replace into games (name,console_name) values ( 'Jerry Glanvilles Pigskin Footbrawl', 'Genesis');
replace into games (name,console_name) values ( 'Jewel Master', 'Genesis');
replace into games (name,console_name) values ( 'Joe & Mac', 'Genesis');
replace into games (name,console_name) values ( 'Joe Montana Football (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Joe Montana II Sports Talk Football', 'Genesis');
replace into games (name,console_name) values ( 'John Madden Football', 'Genesis');
replace into games (name,console_name) values ( 'John Madden Football 92', 'Genesis');
replace into games (name,console_name) values ( 'John Madden Football 93', 'Genesis');
replace into games (name,console_name) values ( 'John Madden Football: Championship Edition', 'Genesis');
replace into games (name,console_name) values ( 'Jordan vs Bird', 'Genesis');
replace into games (name,console_name) values ( 'Judge Dredd', 'Genesis');
replace into games (name,console_name) values ( 'Junction', 'Genesis');
replace into games (name,console_name) values ( 'Jungle Strike', 'Genesis');
replace into games (name,console_name) values ( 'Jurassic Park (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Jurassic Park: Rampage Edition', 'Genesis');
replace into games (name,console_name) values ( 'Justice League Task Force', 'Genesis');
replace into games (name,console_name) values ( 'Ka-Ge-Ki', 'Genesis');
replace into games (name,console_name) values ( 'Kawasaki Superbike Challenge', 'Genesis');
replace into games (name,console_name) values ( 'Kid Chameleon', 'Genesis');
replace into games (name,console_name) values ( 'King Salmon', 'Genesis');
replace into games (name,console_name) values ( 'King of the Monsters', 'Genesis');
replace into games (name,console_name) values ( 'King of the Monsters 2', 'Genesis');
replace into games (name,console_name) values ( 'Kings Bounty: The Conquerors Quest', 'Genesis');
replace into games (name,console_name) values ( 'Klax', 'Genesis');
replace into games (name,console_name) values ( 'Krustys Fun House', 'Genesis');
replace into games (name,console_name) values ( 'LHX Attack Chopper', 'Genesis');
replace into games (name,console_name) values ( 'La Russa Baseball 95', 'Genesis');
replace into games (name,console_name) values ( 'Lakers versus Celtics and the NBA Playoffs', 'Genesis');
replace into games (name,console_name) values ( 'Landstalker: The Treasures of King Nole', 'Genesis');
replace into games (name,console_name) values ( 'Langrisser', 'Genesis');
replace into games (name,console_name) values ( 'Last Action Hero', 'Genesis');
replace into games (name,console_name) values ( 'Last Battle', 'Genesis');
replace into games (name,console_name) values ( 'Lemmings', 'Genesis');
replace into games (name,console_name) values ( 'Lemmings 2: The Tribes', 'Genesis');
replace into games (name,console_name) values ( 'Lethal Enforcers', 'Genesis');
replace into games (name,console_name) values ( 'Lethal Enforcers II: Gun Fighters', 'Genesis');
replace into games (name,console_name) values ( 'Liberty or Death', 'Genesis');
replace into games (name,console_name) values ( 'Light Crusader', 'Genesis');
replace into games (name,console_name) values ( 'Lotus II: RECS', 'Genesis');
replace into games (name,console_name) values ( 'Lotus Turbo Challenge', 'Genesis');
replace into games (name,console_name) values ( 'M-1 Abrams Battle Tank', 'Genesis');
replace into games (name,console_name) values ( 'M.U.S.H.A.', 'Genesis');
replace into games (name,console_name) values ( 'MLBPA Baseball', 'Genesis');
replace into games (name,console_name) values ( 'Madden NFL 94', 'Genesis');
replace into games (name,console_name) values ( 'Madden NFL 95', 'Genesis');
replace into games (name,console_name) values ( 'Madden NFL 96', 'Genesis');
replace into games (name,console_name) values ( 'Madden NFL 97', 'Genesis');
replace into games (name,console_name) values ( 'Madden NFL 98', 'Genesis');
replace into games (name,console_name) values ( 'Marble Madness', 'Genesis');
replace into games (name,console_name) values ( 'Mario Andretti Racing', 'Genesis');
replace into games (name,console_name) values ( 'Mario Lemieux Hockey', 'Genesis');
replace into games (name,console_name) values ( 'Markos Magic Football', 'Genesis');
replace into games (name,console_name) values ( 'Marsupilami', 'Genesis');
replace into games (name,console_name) values ( 'Marvel Land', 'Genesis');
replace into games (name,console_name) values ( 'Mary Shelleys Frankenstein', 'Genesis');
replace into games (name,console_name) values ( 'Master of Monsters', 'Genesis');
replace into games (name,console_name) values ( 'Math Blaster: Episode 1', 'Genesis');
replace into games (name,console_name) values ( 'Mazin Saga: Mutant Fighter', 'Genesis');
replace into games (name,console_name) values ( 'McDonalds Treasure Land Adventure', 'Genesis');
replace into games (name,console_name) values ( 'Mega Bomberman', 'Genesis');
replace into games (name,console_name) values ( 'Mega Games I', 'Genesis');
replace into games (name,console_name) values ( 'Mega Lo Mania', 'Genesis');
replace into games (name,console_name) values ( 'Mega Turrican', 'Genesis');
replace into games (name,console_name) values ( 'Menacer 6-Game Cartridge', 'Genesis');
replace into games (name,console_name) values ( 'Mercs', 'Genesis');
replace into games (name,console_name) values ( 'MiG-29 Fighter Pilot', 'Genesis');
replace into games (name,console_name) values ( 'Michael Jacksons Moonwalker', 'Genesis');
replace into games (name,console_name) values ( 'Mick & Mack as the Global Gladiators', 'Genesis');
replace into games (name,console_name) values ( 'Mickey Mania: The Timeless Adventures of Mickey Mouse', 'Genesis');
replace into games (name,console_name) values ( 'Mickeys Ultimate Challenge', 'Genesis');
replace into games (name,console_name) values ( 'Micro Machines', 'Genesis');
replace into games (name,console_name) values ( 'Midnight Resistance', 'Genesis');
replace into games (name,console_name) values ( 'Midway Presents Arcades Greatest Hits', 'Genesis');
replace into games (name,console_name) values ( 'Might and Magic: Gates to Another World', 'Genesis');
replace into games (name,console_name) values ( 'Mighty Morphin Power Rangers (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Mighty Morphin Power Rangers: The Movie (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Monopoly (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Mortal Kombat', 'Genesis');
replace into games (name,console_name) values ( 'Mortal Kombat 3', 'Genesis');
replace into games (name,console_name) values ( 'Mortal Kombat II', 'Genesis');
replace into games (name,console_name) values ( 'Ms. Pac-Man', 'Genesis');
replace into games (name,console_name) values ( 'Muhammad Ali Heavyweight Boxing', 'Genesis');
replace into games (name,console_name) values ( 'Mutant League Football', 'Genesis');
replace into games (name,console_name) values ( 'Mutant League Hockey', 'Genesis');
replace into games (name,console_name) values ( 'Mystic Defender', 'Genesis');
replace into games (name,console_name) values ( 'Mystical Fighter', 'Genesis');
replace into games (name,console_name) values ( 'NBA Action 94', 'Genesis');
replace into games (name,console_name) values ( 'NBA Action 95 Starring David Robinson', 'Genesis');
replace into games (name,console_name) values ( 'NBA All-Star Challenge', 'Genesis');
replace into games (name,console_name) values ( 'NBA Hang Time', 'Genesis');
replace into games (name,console_name) values ( 'NBA Jam', 'Genesis');
replace into games (name,console_name) values ( 'NBA Jam Tournament Edition', 'Genesis');
replace into games (name,console_name) values ( 'NBA Live 95', 'Genesis');
replace into games (name,console_name) values ( 'NBA Live 96', 'Genesis');
replace into games (name,console_name) values ( 'NBA Live 97 (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'NBA Live 98 (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'NBA Showdown 94', 'Genesis');
replace into games (name,console_name) values ( 'NCAA Final Four Basketball', 'Genesis');
replace into games (name,console_name) values ( 'NCAA Football', 'Genesis');
replace into games (name,console_name) values ( 'NFL 95', 'Genesis');
replace into games (name,console_name) values ( 'NFL 98', 'Genesis');
replace into games (name,console_name) values ( 'NFL Football 94 Starring Joe Montana', 'Genesis');
replace into games (name,console_name) values ( 'NFL Quarterback Club', 'Genesis');
replace into games (name,console_name) values ( 'NFL Quarterback Club 96', 'Genesis');
replace into games (name,console_name) values ( 'NFL Sports Talk Football 93 Starring Joe Montana', 'Genesis');
replace into games (name,console_name) values ( 'NHL 95', 'Genesis');
replace into games (name,console_name) values ( 'NHL 96', 'Genesis');
replace into games (name,console_name) values ( 'NHL 97 (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'NHL 98 (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'NHL All-Star Hockey 95', 'Genesis');
replace into games (name,console_name) values ( 'NHL Hockey (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'NHL Hockey 94', 'Genesis');
replace into games (name,console_name) values ( 'NHLPA Hockey 93', 'Genesis');
replace into games (name,console_name) values ( 'Newman-Haas IndyCar Featuring Nigel Mansell', 'Genesis');
replace into games (name,console_name) values ( 'Nigel Mansells World Championship Racing', 'Genesis');
replace into games (name,console_name) values ( 'Nightmare Circus', 'Genesis');
replace into games (name,console_name) values ( 'No Escape', 'Genesis');
replace into games (name,console_name) values ( 'Nobunagas Ambition', 'Genesis');
replace into games (name,console_name) values ( 'Normys Beach Babe-O-Rama', 'Genesis');
replace into games (name,console_name) values ( 'Olympic Gold', 'Genesis');
replace into games (name,console_name) values ( 'Olympic Summer Games', 'Genesis');
replace into games (name,console_name) values ( 'Onslaught', 'Genesis');
replace into games (name,console_name) values ( 'Operation Europe: Path to Victory 1939-45', 'Genesis');
replace into games (name,console_name) values ( 'OutRun', 'Genesis');
replace into games (name,console_name) values ( 'OutRun 2019', 'Genesis');
replace into games (name,console_name) values ( 'OutRunners', 'Genesis');
replace into games (name,console_name) values ( 'Outback Joey', 'Genesis');
replace into games (name,console_name) values ( 'Outlander', 'Genesis');
replace into games (name,console_name) values ( 'P.T.O.: Pacific Theater of Operations', 'Genesis');
replace into games (name,console_name) values ( 'PGA European Tour', 'Genesis');
replace into games (name,console_name) values ( 'PGA Tour 96', 'Genesis');
replace into games (name,console_name) values ( 'PGA Tour Golf', 'Genesis');
replace into games (name,console_name) values ( 'PGA Tour Golf II', 'Genesis');
replace into games (name,console_name) values ( 'PGA Tour Golf III', 'Genesis');
replace into games (name,console_name) values ( 'Pac-Attack', 'Genesis');
replace into games (name,console_name) values ( 'Pac-Man 2: The New Adventures', 'Genesis');
replace into games (name,console_name) values ( 'Pac-Mania', 'Genesis');
replace into games (name,console_name) values ( 'Paperboy', 'Genesis');
replace into games (name,console_name) values ( 'Paperboy 2', 'Genesis');
replace into games (name,console_name) values ( 'Pebble Beach Golf Links', 'Genesis');
replace into games (name,console_name) values ( 'Pelé II: World Tournament Soccer', 'Genesis');
replace into games (name,console_name) values ( 'Pelé!', 'Genesis');
replace into games (name,console_name) values ( 'Pete Sampras Tennis', 'Genesis');
replace into games (name,console_name) values ( 'Phantasy Star II', 'Genesis');
replace into games (name,console_name) values ( 'Phantasy Star III: Generations of Doom', 'Genesis');
replace into games (name,console_name) values ( 'Phantasy Star IV: The End of the Millennium', 'Genesis');
replace into games (name,console_name) values ( 'Phantom 2040', 'Genesis');
replace into games (name,console_name) values ( 'Phelios', 'Genesis');
replace into games (name,console_name) values ( 'Pink Goes to Hollywood', 'Genesis');
replace into games (name,console_name) values ( 'Pinocchio', 'Genesis');
replace into games (name,console_name) values ( 'Pirates! Gold', 'Genesis');
replace into games (name,console_name) values ( 'Pit-Fighter', 'Genesis');
replace into games (name,console_name) values ( 'Pitfall: The Mayan Adventure', 'Genesis');
replace into games (name,console_name) values ( 'Pocahontas', 'Genesis');
replace into games (name,console_name) values ( 'Populous', 'Genesis');
replace into games (name,console_name) values ( 'Power Drive', 'Genesis');
replace into games (name,console_name) values ( 'Power Monger', 'Genesis');
replace into games (name,console_name) values ( 'Powerball', 'Genesis');
replace into games (name,console_name) values ( 'Predator 2', 'Genesis');
replace into games (name,console_name) values ( 'Primal Rage', 'Genesis');
replace into games (name,console_name) values ( 'Prime Time NFL Football Starring Deion Sanders', 'Genesis');
replace into games (name,console_name) values ( 'Prince of Persia', 'Genesis');
replace into games (name,console_name) values ( 'Pro Quarterback', 'Genesis');
replace into games (name,console_name) values ( 'Puggsy', 'Genesis');
replace into games (name,console_name) values ( 'Quackshot Starring Donald Duck', 'Genesis');
replace into games (name,console_name) values ( 'Quad Challenge', 'Genesis');
replace into games (name,console_name) values ( 'R.B.I. Baseball 3', 'Genesis');
replace into games (name,console_name) values ( 'R.B.I. Baseball 4', 'Genesis');
replace into games (name,console_name) values ( 'R.B.I. Baseball 93', 'Genesis');
replace into games (name,console_name) values ( 'R.B.I. Baseball 94', 'Genesis');
replace into games (name,console_name) values ( 'Race Drivin', 'Genesis');
replace into games (name,console_name) values ( 'Radical Rex', 'Genesis');
replace into games (name,console_name) values ( 'Raiden Trad', 'Genesis');
replace into games (name,console_name) values ( 'Rambo III (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Rampart', 'Genesis');
replace into games (name,console_name) values ( 'Ranger-X', 'Genesis');
replace into games (name,console_name) values ( 'Rastan Saga II', 'Genesis');
replace into games (name,console_name) values ( 'Red Zone', 'Genesis');
replace into games (name,console_name) values ( 'Revolution X', 'Genesis');
replace into games (name,console_name) values ( 'Richard Scarrys Busytown', 'Genesis');
replace into games (name,console_name) values ( 'Rings of Power', 'Genesis');
replace into games (name,console_name) values ( 'Risk', 'Genesis');
replace into games (name,console_name) values ( 'Risky Woods', 'Genesis');
replace into games (name,console_name) values ( 'Ristar', 'Genesis');
replace into games (name,console_name) values ( 'Road Blasters', 'Genesis');
replace into games (name,console_name) values ( 'Road Rash', 'Genesis');
replace into games (name,console_name) values ( 'Road Rash 3: Tour De Force', 'Genesis');
replace into games (name,console_name) values ( 'Road Rash II', 'Genesis');
replace into games (name,console_name) values ( 'RoboCop 3', 'Genesis');
replace into games (name,console_name) values ( 'RoboCop Versus The Terminator', 'Genesis');
replace into games (name,console_name) values ( 'Rock n Roll Racing', 'Genesis');
replace into games (name,console_name) values ( 'Rocket Knight Adventures', 'Genesis');
replace into games (name,console_name) values ( 'Roger Clemens MVP Baseball', 'Genesis');
replace into games (name,console_name) values ( 'Rolling Thunder 2', 'Genesis');
replace into games (name,console_name) values ( 'Rolling Thunder 3', 'Genesis');
replace into games (name,console_name) values ( 'Rolo to the Rescue', 'Genesis');
replace into games (name,console_name) values ( 'Romance of the Three Kingdoms II', 'Genesis');
replace into games (name,console_name) values ( 'Romance of the Three Kingdoms III: Dragon of Destiny', 'Genesis');
replace into games (name,console_name) values ( 'Rugby World Cup 1995', 'Genesis');
replace into games (name,console_name) values ( 'Saint Sword', 'Genesis');
replace into games (name,console_name) values ( 'Samurai Shodown', 'Genesis');
replace into games (name,console_name) values ( 'Saturday Night Slam Masters', 'Genesis');
replace into games (name,console_name) values ( 'Scholastics The Magic School Bus: Space Exploration Game', 'Genesis');
replace into games (name,console_name) values ( 'Scooby-Doo Mystery', 'Genesis');
replace into games (name,console_name) values ( 'SeaQuest DSV', 'Genesis');
replace into games (name,console_name) values ( 'Sesame Street Counting Cafe', 'Genesis');
replace into games (name,console_name) values ( 'Shadow Blasters', 'Genesis');
replace into games (name,console_name) values ( 'Shadow Dancer: The Secret of Shinobi', 'Genesis');
replace into games (name,console_name) values ( 'Shadow of the Beast', 'Genesis');
replace into games (name,console_name) values ( 'Shadow of the Beast II', 'Genesis');
replace into games (name,console_name) values ( 'Shadowrun (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Shanghai II: Dragons Eye', 'Genesis');
replace into games (name,console_name) values ( 'Shaq Fu', 'Genesis');
replace into games (name,console_name) values ( 'Shining Force', 'Genesis');
replace into games (name,console_name) values ( 'Shining Force II', 'Genesis');
replace into games (name,console_name) values ( 'Shining in the Darkness', 'Genesis');
replace into games (name,console_name) values ( 'Shinobi III: Return of the Ninja Master', 'Genesis');
replace into games (name,console_name) values ( 'Shove It! ...The Warehouse Game', 'Genesis');
replace into games (name,console_name) values ( 'Side Pocket', 'Genesis');
replace into games (name,console_name) values ( 'Side Pocket 2', 'Genesis');
replace into games (name,console_name) values ( 'Skeleton Krew', 'Genesis');
replace into games (name,console_name) values ( 'Skitchin', 'Genesis');
replace into games (name,console_name) values ( 'Slaughter Sport', 'Genesis');
replace into games (name,console_name) values ( 'Smash T.V.', 'Genesis');
replace into games (name,console_name) values ( 'Socket', 'Genesis');
replace into games (name,console_name) values ( 'Sol-Feace', 'Genesis');
replace into games (name,console_name) values ( 'Sonic & Knuckles', 'Genesis');
replace into games (name,console_name) values ( 'Sonic 3D: Flickies Island', 'Genesis');
replace into games (name,console_name) values ( 'Sonic Classics', 'Genesis');
replace into games (name,console_name) values ( 'Sonic the Hedgehog (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Sonic the Hedgehog 2 (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Sonic the Hedgehog 3', 'Genesis');
replace into games (name,console_name) values ( 'Sonic the Hedgehog Spinball', 'Genesis');
replace into games (name,console_name) values ( 'Sorcerers Kingdom', 'Genesis');
replace into games (name,console_name) values ( 'Space Harrier II', 'Genesis');
replace into games (name,console_name) values ( 'Space Invaders 90', 'Genesis');
replace into games (name,console_name) values ( 'Sparkster: Rocket Knight Adventures 2', 'Genesis');
replace into games (name,console_name) values ( 'Speedball 2: Brutal Deluxe', 'Genesis');
replace into games (name,console_name) values ( 'Spider-Man (Acclaim)', 'Genesis');
replace into games (name,console_name) values ( 'Spider-Man and Venom: Maximum Carnage', 'Genesis');
replace into games (name,console_name) values ( 'Spider-Man and the X-Men in Arcades Revenge', 'Genesis');
replace into games (name,console_name) values ( 'Spider-Man vs. The Kingpin', 'Genesis');
replace into games (name,console_name) values ( 'Splatterhouse 2', 'Genesis');
replace into games (name,console_name) values ( 'Splatterhouse 3', 'Genesis');
replace into games (name,console_name) values ( 'Sports Talk Baseball', 'Genesis');
replace into games (name,console_name) values ( 'Spot Goes to Hollywood', 'Genesis');
replace into games (name,console_name) values ( 'Star Trek: Deep Space Nine: Crossroads of Time', 'Genesis');
replace into games (name,console_name) values ( 'Star Trek: The Next Generation: Echoes from the Past', 'Genesis');
replace into games (name,console_name) values ( 'Starflight', 'Genesis');
replace into games (name,console_name) values ( 'Stargate (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Steel Talons', 'Genesis');
replace into games (name,console_name) values ( 'Stormlord', 'Genesis');
replace into games (name,console_name) values ( 'Street Fighter II: Special Champion Edition', 'Genesis');
replace into games (name,console_name) values ( 'Street Smart', 'Genesis');
replace into games (name,console_name) values ( 'Streets of Rage', 'Genesis');
replace into games (name,console_name) values ( 'Streets of Rage 2', 'Genesis');
replace into games (name,console_name) values ( 'Streets of Rage 3', 'Genesis');
replace into games (name,console_name) values ( 'Strider', 'Genesis');
replace into games (name,console_name) values ( 'Strider II', 'Genesis');
replace into games (name,console_name) values ( 'Sub-Terrania', 'Genesis');
replace into games (name,console_name) values ( 'Summer Challenge', 'Genesis');
replace into games (name,console_name) values ( 'Sunset Riders', 'Genesis');
replace into games (name,console_name) values ( 'Super Baseball 2020', 'Genesis');
replace into games (name,console_name) values ( 'Super Battleship: The Classic Naval Combat Game', 'Genesis');
replace into games (name,console_name) values ( 'Super Hang-On', 'Genesis');
replace into games (name,console_name) values ( 'Super High Impact', 'Genesis');
replace into games (name,console_name) values ( 'Super Hydlide', 'Genesis');
replace into games (name,console_name) values ( 'Super League (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Super Monaco GP', 'Genesis');
replace into games (name,console_name) values ( 'Super Off Road', 'Genesis');
replace into games (name,console_name) values ( 'Super Real Basketball', 'Genesis');
replace into games (name,console_name) values ( 'Super Street Fighter II: The New Challengers', 'Genesis');
replace into games (name,console_name) values ( 'Super Thunder Blade', 'Genesis');
replace into games (name,console_name) values ( 'Super Volley Ball', 'Genesis');
replace into games (name,console_name) values ( 'Superman: The Man of Steel', 'Genesis');
replace into games (name,console_name) values ( 'Sword of Sodan', 'Genesis');
replace into games (name,console_name) values ( 'Sword of Vermilion', 'Genesis');
replace into games (name,console_name) values ( 'Syd of Valis', 'Genesis');
replace into games (name,console_name) values ( 'Sylvester and Tweety in Cagey Capers', 'Genesis');
replace into games (name,console_name) values ( 'Syndicate', 'Genesis');
replace into games (name,console_name) values ( 'T2: The Arcade Game', 'Genesis');
replace into games (name,console_name) values ( 'TNN Bass Tournament of Champions', 'Genesis');
replace into games (name,console_name) values ( 'TNN Outdoors Bass Tournament 96', 'Genesis');
replace into games (name,console_name) values ( 'TaleSpin', 'Genesis');
replace into games (name,console_name) values ( 'Target Earth', 'Genesis');
replace into games (name,console_name) values ( 'Task Force Harrier EX', 'Genesis');
replace into games (name,console_name) values ( 'Taz in Escape from Mars', 'Genesis');
replace into games (name,console_name) values ( 'Taz-Mania', 'Genesis');
replace into games (name,console_name) values ( 'Team USA Basketball', 'Genesis');
replace into games (name,console_name) values ( 'Techno Cop', 'Genesis');
replace into games (name,console_name) values ( 'TechnoClash', 'Genesis');
replace into games (name,console_name) values ( 'Tecmo Super Baseball', 'Genesis');
replace into games (name,console_name) values ( 'Tecmo Super Bowl', 'Genesis');
replace into games (name,console_name) values ( 'Tecmo Super Bowl II: Special Edition', 'Genesis');
replace into games (name,console_name) values ( 'Tecmo Super Bowl III: Final Edition', 'Genesis');
replace into games (name,console_name) values ( 'Tecmo Super Hockey', 'Genesis');
replace into games (name,console_name) values ( 'Tecmo Super NBA Basketball', 'Genesis');
replace into games (name,console_name) values ( 'Tecmo World Cup 92', 'Genesis');
replace into games (name,console_name) values ( 'Teenage Mutant Ninja Turtles: The Hyperstone Heist', 'Genesis');
replace into games (name,console_name) values ( 'Teenage Mutant Ninja Turtles: Tournament Fighters', 'Genesis');
replace into games (name,console_name) values ( 'Terminator 2: Judgment Day', 'Genesis');
replace into games (name,console_name) values ( 'The Addams Family (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'The Adventures of Batman & Robin (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'The Adventures of Mighty Max', 'Genesis');
replace into games (name,console_name) values ( 'The Adventures of Rocky and Bullwinkle and Friends', 'Genesis');
replace into games (name,console_name) values ( 'The Aquatic Games Starring James Pond and The Aquabats', 'Genesis');
replace into games (name,console_name) values ( 'The Berenstain Bears Camping Adventure', 'Genesis');
replace into games (name,console_name) values ( 'The Chaos Engine', 'Genesis');
replace into games (name,console_name) values ( 'The Death and Return of Superman', 'Genesis');
replace into games (name,console_name) values ( 'The Duel: Test Drive II', 'Genesis');
replace into games (name,console_name) values ( 'The Faery Tale Adventure', 'Genesis');
replace into games (name,console_name) values ( 'The Flintstones (Taito)', 'Genesis');
replace into games (name,console_name) values ( 'The Gadget Twins', 'Genesis');
replace into games (name,console_name) values ( 'The Great Circus Mystery Starring Mickey & Minnie', 'Genesis');
replace into games (name,console_name) values ( 'The Great Waldo Search', 'Genesis');
replace into games (name,console_name) values ( 'The Humans', 'Genesis');
replace into games (name,console_name) values ( 'The Incredible Crash Dummies (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'The Incredible Hulk', 'Genesis');
replace into games (name,console_name) values ( 'The Jungle Book', 'Genesis');
replace into games (name,console_name) values ( 'The Lawnmower Man (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'The Legend of Galahad', 'Genesis');
replace into games (name,console_name) values ( 'The Lion King', 'Genesis');
replace into games (name,console_name) values ( 'The Lost Vikings', 'Genesis');
replace into games (name,console_name) values ( 'The Lost World: Jurassic Park (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'The Miracle Piano Teaching System (software)', 'Genesis');
replace into games (name,console_name) values ( 'The Ooze', 'Genesis');
replace into games (name,console_name) values ( 'The Pagemaster', 'Genesis');
replace into games (name,console_name) values ( 'The Pirates of Dark Water', 'Genesis');
replace into games (name,console_name) values ( 'The Punisher', 'Genesis');
replace into games (name,console_name) values ( 'The Ren & Stimpy Show Presents Stimpys Invention', 'Genesis');
replace into games (name,console_name) values ( 'The Revenge of Shinobi', 'Genesis');
replace into games (name,console_name) values ( 'The Simpsons: Bart vs. the Space Mutants', 'Genesis');
replace into games (name,console_name) values ( 'The Simpsons: Barts Nightmare', 'Genesis');
replace into games (name,console_name) values ( 'The Steel Empire', 'Genesis');
replace into games (name,console_name) values ( 'The Story of Thor: A Successor of the Light', 'Genesis');
replace into games (name,console_name) values ( 'The Terminator', 'Genesis');
replace into games (name,console_name) values ( 'The Tick', 'Genesis');
replace into games (name,console_name) values ( 'Theme Park', 'Genesis');
replace into games (name,console_name) values ( 'Thomas the Tank Engine & Friends', 'Genesis');
replace into games (name,console_name) values ( 'Thunder Force II', 'Genesis');
replace into games (name,console_name) values ( 'Thunder Force III', 'Genesis');
replace into games (name,console_name) values ( 'Thunder Force IV', 'Genesis');
replace into games (name,console_name) values ( 'Thunder Fox', 'Genesis');
replace into games (name,console_name) values ( 'Time Killers', 'Genesis');
replace into games (name,console_name) values ( 'Tinhead', 'Genesis');
replace into games (name,console_name) values ( 'Tiny Toon Adventures: ACME All-Stars', 'Genesis');
replace into games (name,console_name) values ( 'Tiny Toon Adventures: Busters Hidden Treasure', 'Genesis');
replace into games (name,console_name) values ( 'Todds Adventures in Slime World', 'Genesis');
replace into games (name,console_name) values ( 'ToeJam & Earl', 'Genesis');
replace into games (name,console_name) values ( 'ToeJam & Earl in Panic on Funkotron', 'Genesis');
replace into games (name,console_name) values ( 'Toki: Going Ape Spit', 'Genesis');
replace into games (name,console_name) values ( 'Tom and Jerry: Frantic Antics', 'Genesis');
replace into games (name,console_name) values ( 'Tony La Russa Baseball', 'Genesis');
replace into games (name,console_name) values ( 'Top Gear 2', 'Genesis');
replace into games (name,console_name) values ( 'Toughman Contest', 'Genesis');
replace into games (name,console_name) values ( 'Toxic Crusaders', 'Genesis');
replace into games (name,console_name) values ( 'Toy Story', 'Genesis');
replace into games (name,console_name) values ( 'Toys', 'Genesis');
replace into games (name,console_name) values ( 'Trampoline Terror!', 'Genesis');
replace into games (name,console_name) values ( 'Traysia', 'Genesis');
replace into games (name,console_name) values ( 'Triple Play 96', 'Genesis');
replace into games (name,console_name) values ( 'Triple Play: Gold Edition', 'Genesis');
replace into games (name,console_name) values ( 'Trouble Shooter', 'Genesis');
replace into games (name,console_name) values ( 'Troy Aikman NFL Football', 'Genesis');
replace into games (name,console_name) values ( 'True Lies', 'Genesis');
replace into games (name,console_name) values ( 'Truxton', 'Genesis');
replace into games (name,console_name) values ( 'Twin Cobra', 'Genesis');
replace into games (name,console_name) values ( 'Two Crude Dudes', 'Genesis');
replace into games (name,console_name) values ( 'Ultimate Mortal Kombat 3', 'Genesis');
replace into games (name,console_name) values ( 'Ultimate Qix', 'Genesis');
replace into games (name,console_name) values ( 'Uncharted Waters', 'Genesis');
replace into games (name,console_name) values ( 'Unnecessary Roughness 95', 'Genesis');
replace into games (name,console_name) values ( 'Urban Strike', 'Genesis');
replace into games (name,console_name) values ( 'VR Troopers', 'Genesis');
replace into games (name,console_name) values ( 'Valis III', 'Genesis');
replace into games (name,console_name) values ( 'Valis: The Fantasm Soldier', 'Genesis');
replace into games (name,console_name) values ( 'Vapor Trail: Hyper Offence Formation', 'Genesis');
replace into games (name,console_name) values ( 'Vectorman', 'Genesis');
replace into games (name,console_name) values ( 'Vectorman 2', 'Genesis');
replace into games (name,console_name) values ( 'Venom - Spider-Man: Separation Anxiety', 'Genesis');
replace into games (name,console_name) values ( 'Viewpoint', 'Genesis');
replace into games (name,console_name) values ( 'Virtua Fighter 2 (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'Virtua Racing', 'Genesis');
replace into games (name,console_name) values ( 'Virtual Bart', 'Genesis');
replace into games (name,console_name) values ( 'Virtual Pinball', 'Genesis');
replace into games (name,console_name) values ( 'WWF Raw', 'Genesis');
replace into games (name,console_name) values ( 'WWF Royal Rumble (Acclaim)', 'Genesis');
replace into games (name,console_name) values ( 'WWF Super WrestleMania', 'Genesis');
replace into games (name,console_name) values ( 'WWF WrestleMania: The Arcade Game', 'Genesis');
replace into games (name,console_name) values ( 'Wacky Worlds', 'Genesis');
replace into games (name,console_name) values ( 'Wardner', 'Genesis');
replace into games (name,console_name) values ( 'Warlock', 'Genesis');
replace into games (name,console_name) values ( 'WarpSpeed', 'Genesis');
replace into games (name,console_name) values ( 'Warrior of Rome', 'Genesis');
replace into games (name,console_name) values ( 'Warrior of Rome II', 'Genesis');
replace into games (name,console_name) values ( 'Wayne Gretzky and the NHLPA All-Stars', 'Genesis');
replace into games (name,console_name) values ( 'Waynes World', 'Genesis');
replace into games (name,console_name) values ( 'Weaponlord', 'Genesis');
replace into games (name,console_name) values ( 'Wheel of Fortune (GameTek)', 'Genesis');
replace into games (name,console_name) values ( 'Where in Time is Carmen Sandiego?', 'Genesis');
replace into games (name,console_name) values ( 'Where in the World is Carmen Sandiego?', 'Genesis');
replace into games (name,console_name) values ( 'Whip Rush', 'Genesis');
replace into games (name,console_name) values ( 'Will Harvey Presents The Immortal', 'Genesis');
replace into games (name,console_name) values ( 'Wimbledon Championship Tennis', 'Genesis');
replace into games (name,console_name) values ( 'Winter Challenge', 'Genesis');
replace into games (name,console_name) values ( 'Winter Olympics', 'Genesis');
replace into games (name,console_name) values ( 'Wiz n Li', 'Genesis');
replace into games (name,console_name) values ( 'Wolfchild', 'Genesis');
replace into games (name,console_name) values ( 'Wolverine: Adamantium Rage', 'Genesis');
replace into games (name,console_name) values ( 'Wonder Boy in Monster World', 'Genesis');
replace into games (name,console_name) values ( 'World Championship Soccer II', 'Genesis');
replace into games (name,console_name) values ( 'World Class Leader Board', 'Genesis');
replace into games (name,console_name) values ( 'World Cup Soccer', 'Genesis');
replace into games (name,console_name) values ( 'World Cup USA 94', 'Genesis');
replace into games (name,console_name) values ( 'World Heroes', 'Genesis');
replace into games (name,console_name) values ( 'World Series Baseball (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'World Series Baseball 95', 'Genesis');
replace into games (name,console_name) values ( 'World Series Baseball 96 (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'World Series Baseball 98 (Mega Drive)', 'Genesis');
replace into games (name,console_name) values ( 'World Trophy Soccer', 'Genesis');
replace into games (name,console_name) values ( 'World of Illusion Starring Mickey Mouse and Donald Duck', 'Genesis');
replace into games (name,console_name) values ( 'X-Men', 'Genesis');
replace into games (name,console_name) values ( 'X-Men 2: Clone Wars', 'Genesis');
replace into games (name,console_name) values ( 'X-Perts', 'Genesis');
replace into games (name,console_name) values ( 'Ys III: Wanderers from Ys', 'Genesis');
replace into games (name,console_name) values ( 'Zany Golf', 'Genesis');
replace into games (name,console_name) values ( 'Zero Tolerance', 'Genesis');
replace into games (name,console_name) values ( 'Zero the Kamikaze Squirrel', 'Genesis');
replace into games (name,console_name) values ( 'Zombies Ate My Neighbors', 'Genesis');
replace into games (name,console_name) values ( 'Zool', 'Genesis');
replace into games (name,console_name) values ( 'Zoom!', 'Genesis');
replace into games (name,console_name) values ( 'Zoop', 'Genesis');
